### DISCUSSION TITLE
Can RR compress (gzip) static content?

### DISCUSSION THREAD

**Discussion by nitrogenium** [roadrunner-server/roadrunner#1015] [Q&A] [answered]
For example static content such as js or css can be compressed (gzip).

It is a good idea to have text-based resources served with compression (gzip, deflate or brotli) to minimize total network bytes.

Thank you

**Comment by rustatian** [comment]
Hey @nitrogenium. Sure, just place `gzip` middleware before the `static` like this:
```yaml
http:
    address: xxxx
    middleware: ["static", "gzip" ] <----------- Request comes from here
```

**Reply by rustatian** [reply]
Also, you may use the `fileserver` plugin, which supports even more features for the static files serving: https://github.com/roadrunner-server/fileserver

**Comment by nitrogenium** [comment]
Thank you for your reply.

Before writing the question, I read the documentation, tried to figure it out myself, did a series of tests. No success.

Middleware: ["static", "gzip" ] - It works. But only for content which worker has generated.

But for static content it doesn't work.


My config:

```yaml
version: "2.7"
rpc:
  listen: 'tcp://127.0.0.1:6001'
server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///var/run/rr/rr-relay.sock"
  relay: "unix:///var/run/rr/rr-relay.sock"
  relay_timeout: 60s
logs:
  mode: production
  level: warning
  encoding: json
http:
  address: '0.0.0.0:8080'
  max_request_size: 256
  middleware: ["static", "headers", "gzip"]

  uploads:
    dir: /tmp
    forbid: [".php", ".exe", ".bat", ".sh"]
  headers:
    response:
      X-Powered-By: RoadRunner
  static:
    dir: /app/public
    forbid: [".htaccess", ".php"]
    
    response:
      X-Powered-By: RoadRunner
  pool:
    num_workers: 6
    max_jobs: 128
    allocate_timeout: 10s
    destroy_timeout: 10s
    supervisor:
      max_worker_memory: 256
      exec_ttl: 60s
  ssl:
    address: '0.0.0.0:8443'
    redirect: false
    cert: /etc/ssl/certs/selfsigned.crt
    key: /etc/ssl/private/selfsigned.key
  http2:
    h2c: false
    max_concurrent_streams: 128
status:
  address: '127.0.0.1:8082'
  unavailable_status_code: 503
endure:
  log_level: error

```


Request URL: http://127.0.0.1:8080/
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:8080
Referrer Policy: strict-origin-when-cross-origin
Cache-Control: no-cache, private
**Content-Encoding: gzip**

-----
But:

Request URL: http://127.0.0.1:8080/css/frontend.css
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:8080
Referrer Policy: strict-origin-when-cross-origin
Accept-Ranges: bytes
Content-Length: 90841
Content-Type: text/css; charset=utf-8
Date: Thu, 17 Feb 2022 11:11:44 GMT
Last-Modified: Wed, 16 Feb 2022 17:23:56 GMT
X-Powered-By: RoadRunner

----

I've tried everything I can. 
If you have any ideas, I would be very grateful.
