### DISCUSSION TITLE
Can I use xdebug with grpc rr?

### DISCUSSION THREAD

**Discussion by lanphan** [roadrunner-server/roadrunner#1074] [Q&A] [answered]
Hello,

I see that we have doc about enable XDebug for http plugin here: https://roadrunner.dev/docs/php-debugging

Is it possible to apply this to grpc plugin?

I tried but seems it doesn't work, here is my .rr.yaml:

```
version: '2.7'

rpc:
  listen: tcp://127.0.0.1:6001

status:
  address: 127.0.0.1:2114

server:
  command: "/usr/local/bin/php /source_code/worker.php"
  relay: "pipes"
  relay_timeout: "20s"
  env:
    XDEBUG_SESSION: 1

grpc:
  listen: "tcp://0.0.0.0:9001"
  proto: ${PROTO}

  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s

  pool:
    num_workers: ${NUM_WORKERS}
    max_jobs: ${MAX_JOBS}
    allocate_timeout: ${ALLOCATE_TIMEOUT}
    destroy_timeout: 60
    debug: true

logs:
  mode: development
  encoding: console
  level: debug
  output: stderr

metrics:
  address: 127.0.0.1:2112

```

My xdebug.ini:

```
zend_extension=xdebug

[xdebug]
xdebug.mode=develop,debug
xdebug.idekey=docker
xdebug.start_with_request=yes
xdebug.discover_client_host=1
xdebug.client_port = 9003
xdebug.start_with_request=yes
xdebug.log=/dev/stdout
xdebug.log_level=0
xdebug.connect_timeout_ms=2000
```

I use VSCode with PHP Debug extension, with debug launch config below:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for Xdebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/source_code/": "${workspaceFolder}"
            },
            "ignore": [
                "**/vendor/**/*.php"
            ]
        }
    ]
}
```
( value of "port", I tried both 9000 and 9003, but both don't work)

My RR runs in docker container, with docker-compose.yaml below:

```
app:
      container_name: app
      image: php8-rr
      restart: always
      environment:
        - PROTO=/source_code/protos/app/services.proto
        - NUM_WORKERS=2
        - MAX_JOBS=5
        - ALLOCATE_TIMEOUT=60s
      command: ["sh", "/source_code/docker/run-rr2.sh"]
      volumes:
        - ../:/source_code
        - ./xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      ports:
        - "9001:9001"
```
