### DISCUSSION TITLE
Using TLS to connect

### DISCUSSION THREAD

**Discussion by s1lver** [roadrunner-server/roadrunner#1102] [Q&A] [answered]
Hi! 

I'm trying to set up a connection using TLS for gRPC.

I set up the rr connection according to the configuration example: https://raw.githubusercontent.com/roadrunner-server/roadrunner/master/.rr.yaml

- Issued a root certificate.
- Issued a server certificate. 
- Issued a client certificate signed by the issued root certificate.

```yml
grpc:
  ...
  tls:
    key: "server.key"
    cert: "server.crt"
    root_ca: "ca.crt"
    client_auth_type: require_and_verify_client_cert
```

On the client side:

```php
$credentials = ChannelCredentials::createSsl(
    file_get_contents('ca.pem'), 
    file_get_contents('client.key'),
    file_get_contents('client.pem')
);
```

However, I am getting either handshake errors or a blank in response.

What is the difference between the options: `request_client_cert`, `require_any_client_cert`, `verify_client_cert_if_given`, `require_and_verify_client_cert` ?

How to set up TLS authorization correctly?

**Comment by rustatian** [comment]
Hey @s1lver, nice to meet you 👋🏻 
These options describe a TLS client authentication policy (during the handshake). You also missed the `no_client_cert` option.

For example, if you set the client_auth_type: `no_client_cert`, RR will not request the certificates from the client to verify.
`require_any_client_cert`: indicates, that a client certificate should be requested during the handshake.
`verify_client_cert_if_given`: certificate should be requested, but the server doesn't require that.
`require_and_verify_client_cert `: this is the most strict option. The certificate should be requested during the handshake and that should be at least 1 valid certificate.

**Reply by rustatian** [reply]
Also, keep in mind that the `root_ca` certificate is used to validate your client certificates.

**Reply by s1lver** [reply]
> Also, keep in mind that the `root_ca` certificate is used to validate your client certificates.

Yes, this is what I need. I want to validate the client certificate when establishing a connection

> You also missed the no_client_cert option.

This is the clearest option, everything works with her)

**Reply by rustatian** [reply]
> > Also, keep in mind that the `root_ca` certificate is used to validate your client certificates.
> 
> Yes, this is what I need. I want to validate the client certificate when establishing a connection
> 
> > You also missed the no_client_cert option.
> 
> This is the clearest option, everything works with her)

Yeah, to verify certs, try to bundle all certs into the `root_ca` in the RR.

**Reply by s1lver** [reply]
> > > Also, keep in mind that the `root_ca` certificate is used to validate your client certificates.
> > 
> > 
> > Yes, this is what I need. I want to validate the client certificate when establishing a connection
> > > You also missed the no_client_cert option.
> > 
> > 
> > This is the clearest option, everything works with her)
> 
> Yeah, to verify certs, try to bundle all certs into the `root_ca` in the RR.

options `key`, `cert` are not needed then? Connections will be with different certificates, but signed by the same root

**Reply by rustatian** [reply]
You need the key and certificate to establish an SSL connection. Just try to bundle all certs/keys into the RR's root_ca and then use one of the options with validation.

**Reply by s1lver** [reply]
Tried in different ways, but I only get handshake errors.

> E0427 12:37:22.918138400      43 ssl_transport_security.cc:1504] Handshake failed with fatal error SSL_ERROR_SSL: error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED.
> Status code: 14
> Details: failed to connect to all addresses

Perhaps I'm not using certificates in the server setup at all.

```yml
grpc:
  ...
  tls:
    key: "server.key" #Is the key used here when creating a request to issue a server certificate?
    cert: "server.crt" #Is the issued server certificate being used here?
    root_ca: "ca.crt" #Is the root certificate used here signed by the server and all client certificates?
    client_auth_type: require_and_verify_client_cert
```

```php
$credentials = ChannelCredentials::createSsl(
    file_get_contents('ca.pem'), //Is the root certificate used here that signed all certificates, both client and server?
    file_get_contents('client.key'), //Is the key used here when creating a request to issue a client certificate?
    file_get_contents('client.pem')  //Isthe client certificate signed by root is used?
);
```
