### DISCUSSION TITLE
Export Prometheus metrics when executing a job

### DISCUSSION THREAD

**Discussion by Baiquette** [roadrunner-server/roadrunner#1161] [Q&A] [answered]
Hello,

I'm running a PHP CronJob into a Kubernetes cluster and I would like to have the Prometheus Exporter during the execution.
The aim is to have an endpoint like http://localhost:2112/ read by Prometheus each X seconds.
I did some researchs by reading the documentation and I found 2 main solutions.
The best one seems to be the following:

In my .`rr.yaml` file:
```yaml

# RR configuration version
version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

service:
  some_service_1:
    command: "php my-script.php"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: false
    restart_sec: 0

metrics:
  address: localhost:2112
```

And inside `my-script.php`:
```php
<?php

require "vendor/autoload.php";

use Spiral\RoadRunner\Environment;
use Spiral\Goridge\RPC\RPC;
use Spiral\RoadRunner\Metrics\Metrics;

$rpc = RPC::create(Environment::fromGlobals()->getRPCAddress());

$metrics = new Metrics($rpc);
$metrics->add('app_metric_counter', 1);
```

This code works fine by starting the server with `./rr serve`, and I can see the metrics on http://localhost:2112/

Now, I would like to stop Roadrunner to "delete" the container (because it is a Kubernetes CronJob).
I read that I can "Terminate" the service through RPC with:
```php
// Kill the job
$manager = new Manager($rpc);
$manager->terminate('some_service_1');
```
But this code just terminate the service and not all the server.

Roadrunner has the `./rr reset` command to reset the workers but I didn't find something like `./rr stop`

Do you have an idea how to do it better?
