### DISCUSSION TITLE
[LOGS] How to output not decorated app logs?

### DISCUSSION THREAD

**Discussion by codercms** [roadrunner-server/roadrunner#1178] [Q&A] [answered]
Hi, guys! I want to make RR output my application's log messages from `stderr` without decorating them.
But I ran into problem:
It's impossible to disable RR access logs using the `http -> access_logs` parameter (this parameter is documented here - https://roadrunner.dev/docs/intro-config).
When I set log channel for server and set log level for it to "warn" (to suppress access logs) RR also hides my application's debug/info log messages. 
Actually I don't understand why the RR server log settings affect my application logs.

Is there any way to make RR just forward logs from my application without any processing/decorating?
rr ver: `rr.exe version 2.10.4 (build time: 2022-06-10T23:29:29+0000, go1.18.3)`

Here is my config:
```yaml
version: "2.7"

server:
  command: "php -d opcache.enable-cli=1 ./vendor/bin/rr-worker start --relay-dsn tcp://127.0.0.1:10000"
  relay: tcp://127.0.0.1:10000

http:
  address: 127.0.0.1:8001

  # override http error code for the internal RR errors (Default: 500)
  internal_error_code: 505

  # HTTP access logs (Default: false)
  access_logs: false

  # Maximal incoming request size in megabytes. Zero means no limit. (Default: 0)
  max_request_size: 100

  middleware: [ "static" ]
  pool:
    max_jobs: 10
    num_workers: ${HTTP_WORKERS_COUNT}
  static:
    dir: "public"
    forbid: [ ".php" ]

logs:
  output: stdout
#  encoding: json
  mode: raw
```

**Comment by rustatian** [comment, marked as answer]
Hey @codercms 👋🏻 

Just use `mode: raw` as specified in your configuration.

**Comment by codercms** [comment]
@rustatian but how can I hide RR access logs without hiding my application logs (debug/info)?
If I set level=warn in `logs` section it also hides my debug/info app logs.

**Reply by rustatian** [reply]
Do you want to hide logs from the particular plugin? (HTTP in your case)

**Reply by codercms** [reply]
@rustatian Yes, I want to hide access logs from http component

**Reply by rustatian** [reply]
Just use channels:
```yaml
logs:
  output: stdout
#  encoding: json
  mode: raw
  channels:
    http:
      mode: production
      level: error
      encoding: console
      output: stdout
      err_output: stderr
```
