### DISCUSSION TITLE
[HTTP] How to get client's real IP address?

### DISCUSSION THREAD

**Discussion by codercms** [roadrunner-server/roadrunner#1190] [Q&A] [answered]
There is the `trusted_subnets` parameter in config reference - https://roadrunner.dev/docs/intro-config/2.x/en
But this parameter is not respected in this https://github.com/roadrunner-server/http repository.

My RR is running behind nginx proxy.
Nginx sends X-Forwarded-For header to RR, but RR always returns 127.0.0.1 as REMOTE_ADDR.

P.S. Also, is it possible to make RR respect X-Real-IP header?

**Comment by rustatian** [comment, marked as answer]
Hey @codercms 👋🏻 
`trusted_subnets` activated by the separate middleware: https://github.com/roadrunner-server/proxy_ip_parser.

If `X-Forwarded-For` sits before `X-Real-IP`, then RR parses only `XFF` header.

**Reply by codercms** [reply]
@rustatian hi! Do I need to compile RR with this middleware?
I get warn message: `requested middleware does not exist     {"requested": "proxy_ip_parser"}`

**Reply by rustatian** [reply]
You should add configuration as well (`trusted_subnets`):

```yaml
http:
  address: 127.0.0.1:12811
  max_request_size: 1024
  middleware: [ "proxy_ip_parser" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  trusted_subnets:
    [
      "10.0.0.0/8",
      "127.0.0.0/8",
      "172.16.0.0/12",
      "192.168.0.0/16",
      "::1/128",
      "fc00::/7",
      "fe80::/10"
    ]
  pool:
    num_workers: 2
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
```
