### DISCUSSION TITLE
How to use websockets in RR2

### DISCUSSION THREAD

**Discussion by M-Porter** [roadrunner-server/roadrunner#1203] [Q&A] [answered]
Apologies if this was already discussed and answered elsewhere. I've searched all other rr2 related packages and plugins for answers but couldn't find one.

I'm trying to implement websockets in my application. Based on all other discussions, it seems as though they should be working, but no matter what i attempt (based on the examples in the various plugins repos), all i ever get is a `(index):30 WebSocket connection to 'ws://127.0.0.1:8000/ws' failed: ` error message with no error message. The rr output shows`{"level":"debug","ts":1657129358.8321888,"logger":"websockets","msg":"validation","topics":[]}`.

Start command: `./rr serve -c ./.rr.yaml`

<details>
<summary><h3>.rr.yaml</h3></summary>

```yaml
version: "2.7"

http:
  address: 0.0.0.0:8000
  pool:
    num_workers: 0
    max_jobs: 500
    supervisor:
      exec_ttl: 30s
  static:
    dir: "${PWD}/public"
  middleware: [ "static", "websockets" ]

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php ./vendor/bin/roadrunner-worker"
  env:
    - APP_ENV: "development"
    - APP_BASE_PATH: "${PWD}"
    - LARAVEL_OCTANE: "1"

websockets:
  broker: default
  allowed_origin: "*"
  path: "/ws"

broadcast:
  default:
    driver: memory
    config: { }

logs:
  mode: production
  level: debug
  output: stdout
  encoding: json
```

</details>

Then on my page in a script tag i have a very basic `new WebSocket('ws://localhost:8000/ws')` call which is where i get the connection failed error.

I feel like I'm missing something right in front of my face but I can't figure out what it is. Any nudge in the right direction would be appreciated.

```
$ ./rr -v
rr version 2.10.5 (build time: 2022-06-23T21:11:16+0000, go1.18.3)
```
