### DISCUSSION TITLE
GRPC Reflection server on 2.11.0-beta.1

### DISCUSSION THREAD

**Discussion by genhoi** [roadrunner-server/roadrunner#1223] [General]
I tried the new RoadRunner beta (2.11.0-beta.1) for GRPC Reflection for Postman and GrpcUI, for some reason it didn't work for me, is there any way to tell me what I'm doing wrong?

I added a flag to the settings to enable.

![image](https://user-images.githubusercontent.com/8273730/180600245-5b8e5229-5ca8-47a8-9cfe-ecde8d9be754.png)

RR log output:
`[INFO] RoadRunner server started; version: 2.11.0-beta.1, buildtime: 2022-07-18T14:43:58+0000`

Postman output:
![image](https://user-images.githubusercontent.com/8273730/180600267-cf6c7c73-ec6c-454a-9f99-152de373521f.png)

grpcui output:
```
docker compose logs grpcui
grpcui-1  | Failed to compute set of methods to expose: Symbol not found: utp.catalog_write.v1.CatalogWriteService
```

Although the methods themselves work, if you call the GRPC methods at this address

EDIT: issue: https://github.com/roadrunner-server/roadrunner/issues/1208

**Comment by rustatian** [comment]
Hey @genhoi 👋🏻 
Yeah, this is a known problem. You should specify a proto file to have this feature working. We are working on fixing that. Thanks for the report 👍🏻

**Reply by rustatian** [reply]
ref: #1224

**Reply by rustatian** [reply]
@genhoi Done: https://github.com/roadrunner-server/roadrunner/releases/tag/v2.11.0-beta.2

**Reply by rustatian** [reply]
Have you had a chance to try it?

**Reply by genhoi** [reply]
I tried it and the current implementation doesn't work for me, because RR can't find the imported proto files. To search for proto files correctly it is necessary to tell RR somehow about import proto path, relative to which RR will find import files

**Reply by genhoi** [reply]
Here are the details:
![image](https://user-images.githubusercontent.com/8273730/181575192-37af3c1c-dd65-46c2-a5ae-25b980921f45.png)

![image](https://user-images.githubusercontent.com/8273730/181574908-2cf3fc30-22ba-4d64-8de4-cd94e2dd396b.png)

My import proto path `/app/proto/utp`, but RR does not know about it and there is no setting to tell RoadRunner about it

**Reply by genhoi** [reply]
@rustatian I suggest adding the proto_path setting to the grpc settings section, relative to which to search for proto files to import

Like this:
```yaml
grpc:
  listen: "tcp://0.0.0.0:${RR_GRPC_PORT}"
  enable_reflection_server: true
  proto_path: "/app/proto/utp"
  proto:
    - "/app/proto/utp/catalog_write/catalog_write_service.v1.proto"
  pool:
    num_workers: ${RR_GRPC_WORKERS_COUNT}
    debug: ${RR_GRPC_WORKERS_DEBUG}
```


Or maybe there is another solution without modifying the code

**Reply by rustatian** [reply]
@genhoi Thanks for the feedback. We already parse the protofiles; we have the ability to include imports to the protoc `includes` to have full protodefinitions for the reflection server.

**Reply by rustatian** [reply]
@genhoi Hey 👋🏻 Could you please try `rc.1` release and new configuration for the reflection server? 
https://github.com/roadrunner-server/roadrunner/releases/tag/v2.11.0-rc.1

**Reply by genhoi** [reply]
I tried the new version with this configuration
```yaml
grpc:
  listen: "tcp://0.0.0.0:${RR_GRPC_PORT}"
  reflection_server:
    include: []
  proto:
    - "/app/proto/utp/catalog_write/catalog_write_service.v1.proto"
  pool:
    num_workers: ${RR_GRPC_WORKERS_COUNT}
    debug: ${RR_GRPC_WORKERS_DEBUG}
```

but RR does not start

```
catalog-write-service-app-1  | 2022-08-14T15:58:30.472+0300     DEBUG   server          worker is allocated     {"pid": 15, "internal_event_name": "EventWorkerConstruct"}
catalog-write-service-app-1  | common/error_details.v1.proto: File not found.
catalog-write-service-app-1  | common/error_status.v1.proto: File not found.
catalog-write-service-app-1  | catalog_write/methods/attribute/create_attribute.v1.proto: File not found.
catalog-write-service-app-1  | catalog_write/methods/attribute/delete_attribute.v1.proto: File not found.
...
...
catalog-write-service-app-1  | catalog_write_service.v1.proto:147:43: "GetSizeRangeValueListAutocompleteRequest" is not defined.
catalog-write-service-app-1  | catalog_write_service.v1.proto:147:94: "GetSizeRangeValueListAutocompleteResponse" is not defined.
catalog-write-service-app-1  | 2022-08-14T15:58:30.498+0300     DEBUG   server          worker destroyed        {"pid": 15, "internal_event_name": "EventWorkerDestruct"}
catalog-write-service-app-1  | handle_serve_command: Serve error:
catalog-write-service-app-1  |  endure_start:
catalog-write-service-app-1  |  endure_serve_internal: Function call error:
catalog-write-service-app-1  |  endure_call_serve_fn: got initial serve error from the Vertex grpc.Plugin, stopping execution, error: exit status 1
```
