### DISCUSSION TITLE
How to replace a array config options using environment variables ?

### DISCUSSION THREAD

**Discussion by lyt8384** [roadrunner-server/roadrunner#1307] [Q&A] [answered]
Sorry about my poor English~ I am try to using the environment variables to replace a array config options, but isn`t work, like this.
```yaml
redis:
  addrs:
    - "${REDIS_HOST_1}"
    - "${REDIS_HSOT_2}"
```

but it got 
`Error 'rpc_mget:  redis_driver_mget: dial tcp: address ${REDIS_HOST_1}: missing port in address'`

**Comment by rustatian** [comment, marked as answer]
Hey @lyt8384 👋🏻 
Let me check that. RR should expand all env variables in the configuration.

Done: https://github.com/roadrunner-server/config/releases/tag/v2.16.3
RR release tag: v2.11.3

**Reply by rustatian** [reply]
Could you please show the complete configuration and RR version you're using? (`./rr --version`)

**Reply by lyt8384** [reply]
rr version 2.11.2 (build time: 2022-09-15T08:48:00+0000, go1.19.1), OS: linux, arch: amd64

**Reply by lyt8384** [reply]
`.rr.yaml` file
```yaml
version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

grpc:
  listen: "tcp://0.0.0.0:8000"
  proto:
    - "mail.proto"
  ping_time: 1s
  timeout: 200s

redis:
  addrs: 
    - "${REDIS_HOST_1}"
    - "${REDIS_HSOT_2}"

kv:
  redis:
    driver: redis
```

`.env` file
```env
REDIS_HOST_1 = 192.168.0.30:6379
REDIS_HOST_2 = 192.168.0.31:6379
```
