### DISCUSSION TITLE
Maximize performance for Jobs plugin

### DISCUSSION THREAD

**Discussion by Kaspiman** [roadrunner-server/roadrunner#1535] [Q&A] [answered]
Hello! I use Jobs plugin with AMQP driver (RabbitMQ protocol) and move daemon from separate processes to Roadrunner workers.

Roadrunner version: 2.12.3

I expect performance improvement but degradation occurs. I'm trying to keep the performance up by changing the values in the config. So far nothing works, I'm looking for help.

More detailed information about queue and load:
* queue **http_requests** has rate 60 msg/sec with long http requests (working like a lazy bear)
* 4 performance servers with 12 cores

Old daemons:
* heavy legacy PHP-exemplar with AMQP-read by one message
* **http_requests** queue daemon executes synchronous http request by curl to external api's, average time is about to **850 ms**
*  75 daemons per server * 4 = 300 exemplars

New worker:
* lightweight worker with minimal overhead, Jobs plugin + `spiral/roadrunner-jobs` usages
* 40-80-100-200 workers on every server = 160-320-400-800 exemplars (experimented with different values)
* **http_requests** has the same http execution as before, but average time is about **10 seconds**

I assume that the workers block the execution of requests and wait for each other. Apparently this does not happen with separately running daemons?

I tried to increase or reduce: the number of workers, prefetch size and pollers number. The best result was shown by changing the prefetch size. But this is still very far from the previous result with separately running daemons.

My rr.yaml config looks like this:
```
version: '2.7'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
    command: 'php public/worker.php'
amqp:
    addr: 'dsn here'
logs:
    level: warn
    mode: production
    output: stdout
jobs:
    num_pollers: 32 # 12 (cores?) 32, 40, etc values
    pool:
        num_workers: 40 # 40, 80, 100, 200 values
        max_jobs: 1000
    consume:
        - http_requests
    pipelines:
        http_requests:
            driver: amqp
            config:
                queue: http_requests
                prefetch: 200                      # 1, 20, 100, 200 etc values
                priority: 10
                durable: true
                exchange_durable: true
                consume_all: true
```
