### DISCUSSION TITLE
Session doesn not work with Symfony

### DISCUSSION THREAD

**Discussion by speller** [roadrunner-server/roadrunner#1620] [Q&A]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Sessions in my Symfony are recreated on every request.

### Version (rr --version)

2.12.2

### How to reproduce the issue?

Not sure how to reproduce it. 

Environment: local HTTP
Symfony version: 6.2.5
baldinof/roadrunner-bundle: 2.2.4

In the `\Baldinof\RoadRunnerBundle\Http\KernelHandler::handle()` method, the request contains the session id cookie:

<img width="369" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/1829515/77182a0f-2905-4707-b900-3bae1741de02">

But there's no `$_COOKIE` array

<img width="169" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/1829515/33bc0820-b09c-445c-93cb-e3c7199e5c0d">

So when Symfony tries to start a session in `\Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage::start()`, it tries to get the session id value from `$_COOKIE` and gets nothing, creating a new session. How to fix this?

I found only this relevant issue #18 but it's quite old and closed.

**Comment by rustatian** [comment]
Hey @speller 👋🏻 
There are no superglobals in the RR. HTTP plugin supports PSR-7 standard. To get the cookies, you can use `getCookieParams` on the RR request.

**Reply by rustatian** [reply]
I'm not sure as I'm not a PHP developer. Maybe @Baldinof can help more here.

**Comment by rustatian** [comment]
Converting into a discussion, since this is not a bug.

**Comment by speller** [comment]
@rustatian I can do whatever I want. But how to make Symfony do this? That's the question. If out-of-the-box Symfony integration doesn't support sessions, this must be mentioned in the documentation.

**Reply by rustatian** [reply]
Have you tried to use `getCookieParams` method?

**Comment by Baldinof** [comment]
Hello, can you dump the content of your `.rr.yaml` and `baldinof_roadrunner.yaml` please?

**Reply by speller** [reply]
```yaml
version: "2.7"

server:
  command: "php -d max_execution_time=${HTTP_TIMEOUT} public/index.php"
  # If you are not using symfony 5.3+ and the new Runtime component:
  # remove the previous `command` line above and uncomment the line below to use the deprecated command.
  # command: "php bin/console baldinof:roadrunner:worker"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
    - SERVER_NAME: _pkg_mgr_

http:
  address: 0.0.0.0:8080
  middleware: [ "headers", "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    num_workers: ${RR_NUM_WORKERS}
    allocate_timeout: ${RR_ALLOCATE_TIMEOUT}s
    max_jobs: ${RR_MAX_JOBS}
    supervisor:
      exec_ttl: ${RR_JOB_TIMEOUT}s
  headers:
    response:
      X-App-Version: ${APP_VERSION}

logs:
  mode: ${RR_LOG_MODE}
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error

reload:
  enabled: ${RR_RELOAD_ENABLED}
  interval: 1s
  patterns: [".php", ".yaml", ".twig"]
  services:
    http:
      dirs: ["."]
      recursive: true
      ignore:
        - var
        - .php-cs-fixer.cache

# Uncomment to use metrics integration
# rpc:
#   listen: tcp://127.0.0.1:6001

# Uncomment to use metrics integration
# metrics:
#   # prometheus client address (path /metrics added automatically)
#   address: "0.0.0.0:9180"
```

```yaml
baldinof_road_runner:
    # When the kernel should be rebooted.
    # See https://github.com/baldinof/roadrunner-bundle#kernel-reboots
    kernel_reboot:
        # if you want to use a fresh container on each request, use the `always` strategy
        strategy: on_exception
        # Exceptions you KNOW that do not put your app in an errored state
        allowed_exceptions:
            - Symfony\Component\HttpKernel\Exception\HttpExceptionInterface
            - Symfony\Component\Serializer\Exception\ExceptionInterface
            - Symfony\Contracts\HttpClient\Exception\ExceptionInterface

    # Allow to send prometheus metrics to the main RoadRunner process,
    # via a `Spiral\RoadRunner\MetricsInterface` service.
    # See https://github.com/baldinof/roadrunner-bundle#metrics
    metrics:
        enabled: false
        # collect:
        #     my_counter:
        #         type: counter
        #         help: Some help


    # You can use middlewares to manipulate Symfony requests & responses.
    # See https://github.com/baldinof/roadrunner-bundle#middlewares
    # middlewares:
    #     - App\Middleware\YourMiddleware
```
