### DISCUSSION TITLE
Unable to load static assets

### DISCUSSION THREAD

**Discussion by nmeri17** [roadrunner-server/roadrunner#1622] [Q&A] [answered]
My project has the structure:

-RR.yaml
-Public
--assets/vendor/bunch of files

I have the following section under my http section of RR.yaml:

```
uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
```

In the html head, I have link tags attempting to access these files. I've tried different strategies but the requests keep hitting the framework rather than being handled by the RR server. So far, I've tried the following url patterns:

/assets/vendor/file
/public/assets/vendor/file
I'm using blade, so I've also tried without success to leverage their asset helper function https://laravel.com/docs/10.x/helpers#method-asset, wrapping both patterns above. The resulting path parsed was lacking the port so I figured adding it will assist.

ASSET_URL = localhost:8080

Even attempting to visit the raw path through the browser. They all yield same outcome ie hitting suphle's default 404 page. How do I load assets from my public folder?
