### DISCUSSION TITLE
Trigger Xdebug with cookie XDEBUG_SESSION

### DISCUSSION THREAD

**Discussion by andrei-piarainc** [roadrunner-server/roadrunner#1665] [Q&A] [answered]
I've used to trigger debugging on demand, using `XDEBUG_SESSION` cookie that I set in request with browser extension. So I can start and stop debugging mode any time, for any specific request. This approach works fine when I use `php artisan serve` command to start my Laravel application. But when I switched to Octane with RoadRunner `php artisan octane:start` or `php artisan octane:roadrunner`  I can not use this anymore. The only way that is working - set env variable `XDEBUG_SESSION='1'`, then Xdebug gets activated. But it activates for the whole `roadrunner-worker` process, and stays active all the time while process alive, processing all the requests not only specific ones that I wish to debug.

I was unable to activate debugging with a cookie, cookie just seemed to be ignored. I thought it is Octane, who probably filters, blocks or clears request cookies, but I've started RoadRunner directly with `rr -c .rr.yaml` and result is the same - cookie is ignored. I've noticed that `$_COOKIE` array is empty when request gets processed in `roadrunner-worker`, so I've tried to set `XDEBUG_SESSION` cookie directly in `$_COOKIE` array as soon as I get control in `roadrunner-worker.php` file, also I've found a place where worker gets payload of each request in `waitRequest()` method of `HttpWorker.php` file and set cookie in `$_COOKIE` array immediately after getting payload to make sure every request will have it. But this does not help. I've checked in Xdebug source code, that it reads `XDEBUG_SESSION` from env, url, and `$_COOKIE` array, so I think extension code just had no chance to run when RoadRunner start processing new request.

So the question is, is it possible to make RoadRunner pass control to Xdebug extension on each request processing, not only on worker startup? Or, maybe there is some easy place in RoadRunner's code where I could add such call for extensions (Xdebug) and make a build of RoadRunner with this feature for myself. Alternatively, could you please suggest some other way to trigger Xdebug on RoadRunner for specific requests using cookie?

Thanks!

**Comment by rustatian** [comment]
Hey @andrei-piarainc 👋🏻 
Could you please post your `.rr.yaml` file and `./rr --version` output?

**Comment by andrei-piarainc** [comment]
Hi @rustatian 
Sure.

Version:
```
# ./rr --version
rr version 2023.2.1 (build time: 2023-07-27T17:13:10+0000, go1.20.6), OS: linux, arch: amd64
```
.rr.yaml:
```
version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
    command: '/usr/bin/php8.2 /var/www/html/vendor/bin/roadrunner-worker'
    relay: pipes
    env:
      - APP_ENV: "local"
      - APP_BASE_PATH: "/var/www/html"
      - LARAVEL_OCTANE: "1"
      - XDEBUG_CONFIG: "client_host=host.docker.internal"
      - XDEBUG_MODE: "develop,debug"
      - LARAVEL_SAIL: "1"
      - SUPERVISOR_GROUP_NAME: "php"
      - SHLVL: "0"
      - HOME: "/root"
      - LC_CTYPE: "C.UTF-8"
      - SHELL_VERBOSITY: "0"
      - PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      - WWWUSER: "1000"
      - SUPERVISOR_ENABLED: "1"
      - DEBIAN_FRONTEND: "noninteractive"
      - SUPERVISOR_PROCESS_NAME: "php"
      - PWD: "/var/www/html"
      - TZ: "UTC"
http:
    address: '0.0.0.0:8000'
    middleware:
        - gzip
        - static
    static:
        dir: public
        forbid:
            - .php
            - .htaccess
    pool:
        num_workers: 1
        supervisor:
            max_worker_memory: 100
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
    consume: {  }
kv:
    local:
        driver: memory
        config:
            interval: 60
metrics:
    address: '127.0.0.1:2112'

```
Also some values got overwritten by command in `supervisord.conf` of Laravel Sail docker image:
(I've just checked what Octane normally sends to RoadRunner and tried to do similar)
```
[program:php]
# command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan serve --host=0.0.0.0 --port=80
# command=/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:start --workers=1 --server=roadrunner --host=0.0.0.0 --rpc-port=6001 --port=80
command=/var/www/html/rr -c /var/www/html/.rr.yaml -o version=3 -o http.address=0.0.0.0:80 -o server.command='/usr/bin/php8.2 /var/www/html/vendor/bin/roadrunner-worker' -o http.pool.num_workers=1 -o http.pool.max_jobs=500 -o rpc.listen=tcp://0.0.0.0:6001 -o http.pool.supervisor.exec_ttl=300s -o http.static.dir=/var/www/html/public -o http.middleware=static -o logs.mode=production -o logs.level=debug -o logs.output=stdout -o logs.encoding=json serve
user=sail
environment=LARAVEL_SAIL="1"
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
```

In Sail `docker-compose.yml` I have:
```
laravel.test:
    build:
        context: ./docker/8.2
        dockerfile: Dockerfile
        args:
            WWWGROUP: '${WWWGROUP}'
    image: sail-8.2/app
    extra_hosts:
        - 'host.docker.internal:host-gateway'
    ports:
        - '${APP_PORT:-80}:80'
        - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    environment:
        WWWUSER: '${WWWUSER}'
        LARAVEL_SAIL: 1
        XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        # XDEBUG_SESSION: '1'
        PHP_IDE_CONFIG: 'serverName=laravel.test'
        IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
        - '.:/var/www/html'
    networks:
        - sail
    depends_on:
        - mysql
        - redis
        - minio
```

In .env:
```
SAIL_XDEBUG_MODE="develop,debug"
SAIL_XDEBUG_CONFIG="client_host=host.docker.internal"
```
