### DISCUSSION TITLE
roadrunner consuming 100% cpu

### DISCUSSION THREAD

**Discussion by rickgarcia-lfg** [roadrunner-server/roadrunner#1702] [General]
Before creating a bug, I wanted to see if there was anything suspicious with my rr.yaml file.  One thing that I notice is that after running for a couple days, my road runner process eats up 100% cpu of a core 100% of the time.  It never recovers until I restart road runner.  Even tho it is consuming an entire core, it seems to be serving traffic just fine.  So it's not creating a service outage or degradation of services, but it is costing $$$ since I run it in a serverless environment that scales up based upon cpu usage.

I am running Laravel, using https://github.com/roadrunner-php/laravel-bridge.

Here is my rr.yaml:

```yaml
version: "3"

server:
  command: "php ./vendor/bin/rr-worker start --relay-dsn unix:///tmp/rr-relay.sock"
  relay: "unix:///tmp/rr-relay.sock"
  relay_timeout: 130s

http:
  address: 0.0.0.0:9000
  middleware: ["static","gzip"]
  pool:
    max_jobs: 25
    num_workers: 16
    supervisor:
      exec_ttl: 130s
      max_worker_memory: 256
  static:
    dir: "public"

status:
  address: 0.0.0.0:2114
```

Please let me know if there is something fundamental here that would cause the roadrunner binary to spin out of control... If not, maybe someone can help point me in the right direction for troubleshooting this.

Thanks!
