### DISCUSSION TITLE
Problems with consuming messages from the Kafka topic

### DISCUSSION THREAD

**Discussion by denyskanunnikov** [roadrunner-server/roadrunner#1740] [Q&A] [answered]
Good evening, I request assistance and advice in resolving the following issue. On the development host machine, a topic "se-collector.pt.event.out" has been created in the context of brokers, within which events are stored.

![2023-09-29_17-50](https://github.com/roadrunner-server/roadrunner/assets/92357925/935b2f77-d91c-40f0-a360-06aee4c1026c)

 I am using the following RoadRunner configuration:
```yaml
version: "3"

server:
  relay: pipes
  command: "/usr/bin/php -d xdebug.mode=debug -d xdebug.start_with_request=yes -d xdebug.client_host=host.docker.internal -d xdebug.client_port=\"9008\" /app/consumer.php"

kafka:
  brokers: ["dev-producer_api-1:8001"]

jobs:
  consume: ["complayer-queue"]
  num_pollers: 1
  pipeline_size: 1000
  pool:
    num_workers: 1
    allocate_timeout: 60s
  pipelines:
    complayer-queue:
      driver: kafka
      config:
        consumer_options:
          topics: ["se-collector.pt.event.out"]
        group_options:
          group_id: "complayerv2.0-test-consumer"
rpc:
  enable: true
  listen: tcp://127.0.0.1:6001
```

Example queue consumer
```<?php
use Spiral\RoadRunner\Jobs\Consumer;
use Spiral\RoadRunner\Jobs\Task\ReceivedTaskInterface;

require_once __DIR__.'/vendor/autoload.php';
$consumer = new Consumer();
echo "Consumer was created ...";
/** @var Spiral\RoadRunner\Jobs\Task\ReceivedTaskInterface $task */
while ($task = $consumer->waitTask()) {
    var_dump($task);
}
echo "Events were consumed ...";
```
![2023-09-29_17-48_1](https://github.com/roadrunner-server/roadrunner/assets/92357925/149cb6da-8a8d-42b1-a1a0-6d6eaad2af6c)

However, this script does not consume messages from the broker.
