### DISCUSSION TITLE
No workers after rr reset

### DISCUSSION THREAD

**Discussion by stevenbrookes** [roadrunner-server/roadrunner#1790] [General]
Hi

When I redeploy my application using deployer (https://deployer.org/) I have a step that calls rr reset but I don't see any workers after that so I have to restart via systemd.

RR version
`rr version 2023.3.6 (build time: 2023-11-23T16:35:33+0000, go1.21.4), OS: linux, arch: arm64`

Systemd config - note that the directory /var/www/test-tide/current is a symlink to the currently deployed version.  Each time deployer deploys it creates a new directory /var/www/test-tide/release/123 and puts link into current version.

```ini
[Unit]
Description=Roadrunner for Test Tide

[Service]
Type=simple
User=www-data
Group=www-data
EnvironmentFile=/var/www/test-tide/current/.env
EnvironmentFile=/var/www/test-tide/current/.env.local
ExecStart=/usr/bin/rr serve -w /var/www/test-tide/current
Restart=always
RestartSec=30

[Install]
WantedBy=default.target
```

.rr.yaml

```yaml
version: "3"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  fcgi:
    address: ${RR_FCGI_ADDRESS:-tcp://127.0.0.1:9000}
  pool:
    debug: false
    supervisor:
        num_workers: ${RR_POOL_NUM_WORKERS:-1}
        max_worker_memory: ${RR_MAX_WORKER_MEMORY:-2000}
        ttl: 600s
        idle_ttl: 600s
        exec_ttl: 10s

  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  mode: production
  channels:
    http:
      level: ${RR_LOG_HTTP_LEVEL:-info}
    server:
      level: ${RR_LOG_SERVER_LEVEL:-info}
      mode: raw
    metrics:
      level: ${RR_LOG_METRICS_LEVEL:-info}

rpc:
  listen:  tcp://127.0.0.1:6001

metrics:
  address:  ${RR_METRICS_ADDRESS:-0.0.0.0:9180}

```

Deployer step to reset 

```php
task('roadrunner:reset', function () {
    if (test('[ -x {{bin/rr}} ]')) {
        run('{{bin/rr}} -w  {{release_path}} reset');

    }
});
```

After systemd restart

```
systemctl status roadrunner-test-tide
● roadrunner-test-tide.service - Roadrunner for Test Tide
     Loaded: loaded (/etc/systemd/system/roadrunner-test-tide.service; enabled; preset: enabled)
     Active: active (running) since Mon 2023-11-27 15:17:54 UTC; 8s ago
   Main PID: 1284793 (rr)
      Tasks: 10 (limit: 4526)
     Memory: 124.7M
        CPU: 901ms
     CGroup: /system.slice/roadrunner-test-tide.service
             ├─1284793 /usr/bin/rr serve -w /var/www/test-tide/current
             ├─1284799 php public/index.php
             └─1284800 php public/index.php
```

`rr -w /var/www/test-tide/current workers`
```
Workers of [http]:
+---------+-----------+---------+---------+---------+--------------------+
|   PID   |  STATUS   |  EXECS  | MEMORY  |  CPU%   |      CREATED       |
+---------+-----------+---------+---------+---------+--------------------+
| 1284799 | ready     |       0 | 85 MB   |    0.97 | 43 seconds ago     |
| 1284800 | ready     |       0 | 85 MB   |    0.97 | 43 seconds ago     |
+---------+-----------+---------+---------+---------+--------------------+`
```

After deployment

systemctl status roadrunner-test-tide

```
● roadrunner-test-tide.service - Roadrunner for Test Tide
     Loaded: loaded (/etc/systemd/system/roadrunner-test-tide.service; enabled; preset: enabled)
     Active: active (running) since Sun 2023-11-26 08:50:47 UTC; 1 day 6h ago
   Main PID: 1126625 (rr)
      Tasks: 10 (limit: 4526)
     Memory: 21.3M
        CPU: 2min 44.886s
     CGroup: /system.slice/roadrunner-test-tide.service
             └─1126625 /usr/bin/rr serve -w /var/www/test-tide/current
```

`rr -w /var/www/test-tide/current workers` -> nothing

So it seems like RR gets confused, perhaps when the symlink changes to another directory when reset is called.
Happy to run some tests or get debugging if it can help

Thanks

Steve
