### DISCUSSION TITLE
External Kafka queue, Roadrunner, Temporal  workflows

### DISCUSSION THREAD

**Discussion by LeonidDereviankoCasafari** [roadrunner-server/roadrunner#1803] [Q&A] [answered]
Hi, i'm new to temporal and roadrunner and having some issues with it.
I have local environment started with docker-compose based on example from https://github.com/temporalio/samples-php/blob/master/docker-compose.yml
i take `elasticsearch`, 'postgresql', 'temporal', 'temporal-admin-tools', 'temporal-ui' from the example and also there is my own app container which is running consumer.
worker.php and saga:consumer cli command based on BookingSaga sample.
 I'm trying to run SagaWorkflow for each message consumed from Kafka queue but it won't take any message from Kafka with config i wrote. 
 If i'm trying to consume messages using Roadrunner When i start and open temporal-ui page i can't see any messages consumed and no workflows started. 
 But if i use in saga:consumer command consuming messages with RdKafka\KafkaConsumer i can see that there is Workflows in temporal but they are in "Running" state but no workers started, and to complete workers and activities i have to additionally run saga:consumer command in container and only than workflows passing to completed.
 
So there is two questions: 
 - How to manage correct consuming from Kafka (the messages should be published by thirdparty service i can't change it) by Roadrunner and start temporal's SagaWorkflow
 - How to start workers running automatically with temporal started
 
It will be excellent it there is example for such combo but i didn't found it

here is rr.yaml  and installed requirements with composer
```json
"require": {
        "symfony/dotenv": "^6.2",
        "symfony/console": "^6.3",
        "php": ">=8.2.0",
        "ext-curl": "*",
        "spiral/roadrunner": "^2023.3",
        "spiral/roadrunner-cli": "^2.5",
        "spiral/roadrunner-worker": "^3.2",
        "spiral/roadrunner-jobs": "^4.3",
        "spiral/tokenizer": "^3.9",
        "grpc/grpc": "^1.38",
        "google/protobuf": "^3.25",
        "jobcloud/php-kafka-lib": "^2.0",
        "temporal/sdk": "2.7.x-dev",
        "temporal/open-telemetry-interceptors": "dev-master",
        "guzzlehttp/promises": "^2.0",
        "php-http/httplug": "^2.4",
        "nyholm/psr7": "^1.8",
        "open-telemetry/transport-grpc": "^0.0.17",
        "open-telemetry/exporter-otlp": "^0.0.17"
    },
```
```yaml
version: "3"

server:
  relay: pipes
  command: "php /app/app.php saga:consumer queue-name"
  env:
    - TEMPORAL_CLI_ADDRESS: temporal:7233
    - RR_MODE: jobs

temporal:
  address: temporal:7233
  activities:
    num_workers: 1
    allocate_timeout: 3600s
    command: "php /app/worker.php"
    env:
      RR_MODE: temporal

kafka:
  brokers: ["kafka"]

jobs:
  consume: ["kafka-messages"]
  num_pollers: 1
  pipeline_size: 1000
  pool:
    num_workers: 4
    allocate_timeout: 1h
  pipelines:
    kafka-messages:
      driver: kafka
      config:
        brokers: [ kafka:9092 ]
        consumer_options:
          topics: ["queue-name"]
        group_options:
          group_id: "test-consumer"

rpc:
  listen: tcp://127.0.0.1:6001

logs:
  mode: raw
  output: stdout
  err_output: stderr
  encoding: json
  server:
    mode: raw
    level: info
    encoding: json
    output: stdout
    err_output: stderr
  temporal:
    mode: raw
    level: info
    encoding: json
    output: stdout
    err_output: stderr
  rpc:
    mode: raw
    level: info
    encoding: json
    output: stdout
    err_output: stderr
```

**Comment by rustatian** [comment]
Hey @LeonidDereviankoCasafari 👋 
1. 
```yaml
kafka:
  brokers: ["kafka:9092"] # Port should be used
```
2. What is your RR version?
3. Have you read this thread: https://github.com/orgs/roadrunner-server/discussions/1730 ?

**Reply by LeonidDereviankoCasafari** [reply]
Thanks for the answer @rustatian !

i'll check now fix with adding port, and there is a second part of question.
Yes i've read that thread,  correct, my `queue-name` it's a 'topic-name'  from Kafka, i missed naming in config  in question
but looks like it is a bit different i'm not pushing anything to Kafka but only Read it, and also question related to running workers with temporal  in different containers but they are not start automatically.
I'm using RR roadrunner:2023.3.5 version in app container

**Reply by rustatian** [reply, marked as answer]
Got u 👍 
You may read docs [here](https://roadrunner.dev/docs/queues-overview/current/en).

Issues in your config:
1. Use number of pollers at least +1 to number of workers.
2. You don't need to set the `RR_MODE` env variable. RR will set it automatically per pool of workers. By setting it to the `RR_MODE: temporal` you overwriting mode set by RR for all pools.
3. Simplify logs in the development mode:
```yaml
logs:
  mode: development
  level: debug
```
4. Check the docs about `kafka`. First of all, there is no `brokers` key. Check that the topic exists on the kafka broker. Or use `auto_create_topics_enable` pipeline option.

> workers with temporal in different containers but they are not start automatically.

Could you please rephrase, I'm not sure that I understand correctly. What is 'different containers' and why they should start automatically?
