### DISCUSSION TITLE
How to configure kafka job queue

### DISCUSSION THREAD

**Discussion by suityou01** [roadrunner-server/roadrunner#1820] [General]
I am having problems just getting the basic config set up.

```config
version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php consumer.php"

#http:
#  address: "0.0.0.0:8080"
kafka:
  addrs: 127.0.0.1:9092

jobs:
  num_pollers: 1
  pipeline_size: 100
  pool:
    num_workers: 1
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  consume: ["kafka"]
  pipelines:
    kafka:
      driver: kafka
      config:
        priority: 1
        topic: feeds.feeds.unit
        brokers: [ broker:9092 ]
        consumer_options:
          topics: [ "feeds", "feeds.feeds.unit", "^[a-zA-Z0-9._-]+$" ]
          consume_regexp: true
logs:
  level: error
```

Error "Did not find expected key by parsing a block mapping"

NB The example has a key called topic at the jobs.pipelines.queue-name.config level which is confusing
e.g.

```yaml
# Kafka jobs driver
#
# This option is required to use Kafka driver. Addrs can contain any number of addresses separated by comma (127.0.0.1:9092,127.0.0.1:9093,...)
kafka:
  addrs: 127.0.0.1:9092

jobs:
  num_pollers: 10
  pipeline_size: 100000
  pool:
    num_workers: 10
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

  pipelines:
    test-local-6:
      # Driver name
      #
      # This option is required
      driver: kafka

      # Driver's configuration
      #
      # Should not be empty
      config:

        # Pipeline priority
        #
        # If the job has priority set to 0, it will inherit the pipeline's priority. Default: 10.
        priority: 1

        # Topic name: https://kafka.apache.org/intro#intro_concepts_and_terms
        #
        # This option is required and should not be empty.
        topic: test-1
```
So we have to specify a topic here (single topic, which one??)
And for the consumer we have to specify a topics key

How does this work?

**Comment by rustatian** [comment]
Hey @suityou01 👋 
Ok, looks like you're using some outdated docs. There are no `topic`, `broker` and other options for the `kafka` driver.

You may find the correct options here: https://roadrunner.dev/docs/queues-kafka/current/en

**Comment by suityou01** [comment]
This makes sense. 

I have the worker package installed and yet I get this error

> Fatal error: Uncaught Error: Class "Spiral\RoadRunner\Environment" not found in /app/consumer.php:10

```json
{
    "require": {
        "spiral/roadrunner-cli": "^2.6",
        "spiral/roadrunner-http": "^3.3",
        "nyholm/psr7": "^1.8",
        "spiral/roadrunner-worker": "^3.3",
        "spiral/roadrunner-jobs": "^4.3",
        "spiral/roadrunner": "^2023.3"
    }
}
```
```php
<?php

use Spiral\RoadRunner\Environment;
use Spiral\RoadRunner\Environment\Mode;

// 1. Using global env variable
$isJobsMode = $_SERVER['RR_MODE'] === 'jobs';

// 2. Using RoadRunner's API
$env = Environment::fromGlobals();

$isJobsMode = $env->getMode() === Mode::MODE_JOBS;

$consumer = new Consumer();

/** @var Spiral\RoadRunner\Jobs\Task\ReceivedTaskInterface $task */
while ($task = $consumer->waitTask()) {
    var_dump($task);
}
```

Any ideas?

**Reply by rustatian** [reply]
Try to use `composer -u` to update deps. But this class belongs to the `spiral/roadrunner-worker` package.

**Reply by msmakouz** [reply]
@suityou01 Hi, try to add the Composer autoloader in your file:

```php
require __DIR__ . '/vendor/autoload.php';
```

**Comment by suityou01** [comment]
Yep problem exists between chair and monitor. :-)

working code looks like

```php
<?php

use Spiral\RoadRunner\Environment;
use Spiral\RoadRunner\Environment\Mode;
use Spiral\RoadRunner\Jobs\Consumer;
use Spiral\RoadRunner\Jobs\Task\ReceivedTaskInterface;

include "vendor/autoload.php";

// 1. Using global env variable
$isJobsMode = $_SERVER['RR_MODE'] === 'jobs';

// 2. Using RoadRunner's API
$env = Environment::fromGlobals();

$isJobsMode = $env->getMode() === Mode::MODE_JOBS;

$consumer = new Consumer();

/** @var Spiral\RoadRunner\Jobs\Task\ReceivedTaskInterface $task */
while ($task = $consumer->waitTask()) {
    var_dump($task);
}
```

**Comment by suityou01** [comment]
Not getting any output when the messages are flowing through kafka though...

```yaml
version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php consumer.php"

#http:
#  address: "0.0.0.0:8080"
kafka:
  brokers: ["broker:9092"]
  
jobs:
  num_pollers: 1
  pipeline_size: 100
  pool:
    num_workers: 1
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  pipelines:
    kafka:
      driver: kafka
      config:
        priority: 1
        brokers: [ broker:9092 ]
        consumer_options:
          topics: [ "feeds", "feeds.feeds.unit", "^[a-zA-Z0-9._-]+$" ]
          consume_regexp: true
logs:
  level: error
```

![image](https://github.com/roadrunner-server/roadrunner/assets/7422644/147c7db6-7a5f-4943-a09c-fbc267c6f5c5)

**Reply by rustatian** [reply]
You need `debug` log level to see your `var_dump`. Also, you have to complete the task by using `$task->complete();` 😃

**Comment by suityou01** [comment]
So here is what I get in my container log

```bash
2023-12-21T12:38:20+0000	DEBUG	rpc         	plugin was started	{"address": "tcp://127.0.0.1:6001", "list of the plugins with RPC methods:": ["lock", "resetter", "informer", "jobs", "app"]}
2023-12-21T12:38:20+0000	DEBUG	jobs        	initializing driver	{"pipeline": "kafka", "driver": "kafka"}
2023-12-21T12:38:20+0000	DEBUG	kafka       	ping kafka: ok	{"driver": "kafka", "pipeline": "kafka"}
2023-12-21T12:38:20+0000	DEBUG	jobs        	driver ready	{"pipeline": "kafka", "driver": "kafka", "start": "2023-12-21T12:38:20+0000", "elapsed": "3.843019ms"}
2023-12-21T12:38:20+0000	DEBUG	server      	worker is allocated	{"pid": 16, "internal_event_name": "EventWorkerConstruct"}
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
2023-12-21T12:38:20+0000	DEBUG	jobs        	exited from jobs pipeline processor
[INFO] RoadRunner server started; version: 2023.3.8, buildtime: 2023-12-14T16:05:26+0000
[INFO] sdnotify: not notified

```

Loop now looks like

```php
/** @var Spiral\RoadRunner\Jobs\Task\ReceivedTaskInterface $task */
while ($task = $consumer->waitTask()) {
    var_dump($task);
    $task->complete();
}
```

Config now looks like

```yaml
version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php consumer.php"

#http:
#  address: "0.0.0.0:8080"
kafka:
  brokers: ["broker:9092"]
  
jobs:
  num_pollers: 1
  pipeline_size: 100
  pool:
    num_workers: 1
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  pipelines:
    kafka:
      driver: kafka
      config:
        priority: 1
        consumer_options:
          topics: [ "feeds", "feeds.feeds.unit", "^[a-zA-Z0-9._-]+$" ]
          consume_regexp: true
logs:
  level: debug
```

Maybe something is coming through but I cannot see the output from var_dump if it is.
Or maybe nothing is coming through and those debug log entries are about something else. How do I tell?

**Comment by suityou01** [comment]
I think those debug messages are on startup. So no messages are coming through it seems.

**Comment by suityou01** [comment]
Kafka does not report it as a consumer so it looks like the handshake is failing. How do I get more output from this black box?

**Reply by rustatian** [reply]
If you see the `ping kafka: ok` - it means, that RR connected to Kafka. You may try to use our [kafka docker-compose](https://github.com/roadrunner-server/kafka/blob/master/tests/env/docker-compose-kafka.yaml) file to check if you set up everything correctly.
Also, make sure you're connected to the correct instance. Check if you need to set `group_options` as well. This is the preferred way (according to the Kafka docs) to work with the consumers.

**Reply by rustatian** [reply]
Make sure that you have selected topics on the server. Otherwise, you may use `auto_create_topics_enable: true` option.

**Reply by rustatian** [reply]
@suityou01 Oh, and do not forget to turn the consumer on: [link](https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1821). In your case, there should be your pipeline name: `kafka`. BTW, you may choose any pipeline name you want, it is not necessary to be `kafka`. It might be some domain-specific name, like, `kafka_feeds`, etc.

**Reply by suityou01** [reply]
In that last link about turning on the consumer I noted it said if you intend to start the consumption manually leave this blank. Is there any documentation on how to start the consumers manually? I don't want to do this in production but I thought it may help debug this problem?

**Reply by rustatian** [reply]
Sure: [link](https://roadrunner.dev/docs/queues-overview/current/en#pausing-a-queue). Queue, which is not in an active state, treated as paused. So, you need to call `resume` method and specify the pipeline name.

**Comment by suityou01** [comment]
OK here is the latest. It is *not* collecting any messages from kafka.

```yaml

version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php consumer.php"

#http:
#  address: "0.0.0.0:8080"
kafka:
  brokers: ["broker:9092"]
  
jobs:
  num_pollers: 1
  pipeline_size: 100
  pool:
    num_workers: 1
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  pipelines:
    kafka:
      driver: kafka
      config:
        priority: 1
        auto_create_topics_enable: true
        consumer_options:
          topics: [ "feeds", "feeds.feeds.unit", "^[a-zA-Z0-9._-]+$" ]
          consume_regexp: true
        group_options:
          group_id: connect-debezium

consume:
  [
    "kafka"
  ]
    
logs:
  level: debug
  output: stdout

```

I have a sink connector which sinks the messages with elasticsearch so I know that kafka is working. I can see the messages through the kafka-ui

Nothing is reaching the kafka driver in roadrunner.

I literally have no more clue what else to do to get this to work? I have followed all your instructions I think very well.

I really want to use this product in my project but if I cannot get it to work or get help to get it to work then I don't think it's ready for general use.

**Reply by rustatian** [reply]
`consume` section should be at the same level as the `pipeline` section.
```yaml

version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php consumer.php"

#http:
#  address: "0.0.0.0:8080"
kafka:
  brokers: ["broker:9092"]
  
jobs:
  num_pollers: 1
  pipeline_size: 100
  pool:
    num_workers: 1
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s

  consume: ["kafka"] # <--
  pipelines:
    kafka:
      driver: kafka
      config:
        priority: 1
        auto_create_topics_enable: true
        consumer_options:
          topics: [ "feeds", "feeds.feeds.unit", "^[a-zA-Z0-9._-]+$" ]
          consume_regexp: true
        group_options:
          group_id: connect-debezium

    
logs:
  level: debug
  output: stdout
```
