### DISCUSSION TITLE
Empty payload for SQS message

### DISCUSSION THREAD

**Discussion by QuietImprovement** [roadrunner-server/roadrunner#1866] [Q&A] [answered]
Hi,

When I try to send an SQS message with JSON content in the body, the payload string is always empty

`aws sqs send-message --region eu-central-1 --endpoint-url https://sqs.eu-central-1.amazonaws.com/ --queue-url https://sqs.eu-central-1.amazonaws.com/x/y --message-body '\{"test":"test"}\'` return this payload `"\"\\\\{\\\"test\\\":\\\"test\\\"}\\\\\""`

but if i try with `aws sqs send-message --region eu-central-1 --endpoint-url https://sqs.eu-central-1.amazonaws.com/ --queue-url https://sqs.eu-central-1.amazonaws.com/x/y --message-body '{"test":"test"}'` return this payload  []

any message body that starts by `{` and ends by `}` and is a valid JSON returns an empty payload

I'm using a custom serializer just to log the payload content

```
/**
     * {@inheritDoc}
     */
    public function deserialize(string $payload): array
    {
        $this->logger->info(
            'Deserialize SQS message received',
            [
                'payload' => $payload,
            ]
        );
        ....
    }
```

**Comment by rustatian** [comment]
Hey @QuietImprovement 👋 
Could you please share your `.rr.yaml` configuration?

**Reply by QuietImprovement** [reply]
Hey @rustatian 

This is my config

```YAML
version: "2.7"
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: php bin/console roadrunner:jobs-worker
  relay: pipes

sqs:
  key: mykey
  secret: mysecret
  region: eu-central-1
  endpoint: https://sqs.eu-central-1.amazonaws.com

jobs:
  num_pollers: 10
  pipeline_size: 100000
  pool:
    num_workers: 10
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
  consume: ["test-sqs-pipeline"]
  pipelines:
    test-sqs-pipeline:
      driver: sqs

      config:
        # Optional section.
        # Default: 10
        prefetch: 10

        # Consume any payload type (not only Jobs structured)
        # Default: false
        consume_all: true

        # Get queue URL only
        # Default: false
        skip_queue_declaration: true

        # Optional section.
        # Default: 0
        #visibility_timeout: 0

        # Optional section.
        # Default: 0
        #wait_time_seconds: 0

        # Optional section.
        # Default: default
        queue: "myqueue"

        # Message group ID: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html#SQS-SendMessage-request-MessageGroupId
        # Default: empty, should be set if FIFO queue is used
        # message_group_id: "test"

        # Optional section.
        # Default: empty
        #attributes:
        #  DelaySeconds: 42
        # etc... see https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html

        # Optional section.
        # Default: empty
        #tags:
        #  test: "tag"

logs:
  encoding: console
  level: debug
  mode: development
  err_output: stderr
  output: stderr

  channels:
    http:
      level: debug
    server:
      level: debug
      mode: raw

reload:
  enabled: true
  interval: 2s
  patterns: [".php", ".yaml"]
  services:
    http:
      dirs: ["."]
      recursive: true
```
