### DISCUSSION TITLE
Graceful shutdown of Symfony Messenger Consumer when started via RR systemd

### DISCUSSION THREAD

**Discussion by jelovac** [roadrunner-server/roadrunner#1880] [Q&A] [answered]
Hi,

I am using ApiPlatform/Symfony with the RoadRunner. In the rr.yaml I have number of symfony messenger consume commands defined like this for each transport:

```
service:
  mq_consumer_async_notification:
    command: "php bin/console messenger:consume --limit=100 async_notification"
    process_num: 1
    exec_timeout: 0s
    restart_sec: 1
    remain_after_exit: true
    env:
      APP_RUNTIME: Runtime\RoadRunnerSymfonyNyholm\Runtime
      APP_DEBUG: "0"
```

What I would like to do is when the Docker Container receives SIGTERM signal to gracefully shutdown the server by not accepting any more requests and finishing the ongoing ones. In addition I would like to stop any Symfony Messenger workers from processing new messages. 

Researching, I have found out that there is a Symfony command for stopping the workers to consume any new messages: `bin/console messenger:stop-workers`. Tested it and it works.

So currently what I do is:
- docker-compose exec myRRContainer php bin/console messenger:stop-workers
- wait a minute
- docker-compose stop myRRContainer

I would like to somehow integrate the first command to run automatically when a SIGTERM signal is received so I do not need to perform this manual step. Is this possible?

In addition starting RoadRunner from a bash script like this:

```start.sh
#!/bin/bash

if [ ! -f ".rr.yaml" ]; then cp .rr.example.yaml .rr.yaml; fi

rr serve -d -c .rr.yaml
```

Dockerfile:

```
CMD [ "./start.sh" ]
```
