### DISCUSSION TITLE
How to prevent RR from trying to process event ?

### DISCUSSION THREAD

**Discussion by QuietImprovement** [roadrunner-server/roadrunner#1885] [Q&A] [answered]
Hi, I'm using RR with Job configuration, but I want to use it only to send messages to SQS.

The problem is that RR is trying to process any message placed in the queue, in an infinite loop...

`2024-03-07 15:23:06 Missing RR worker implementation for jobs mode`

**Comment by rustatian** [comment]
Hey @QuietImprovement 👋 
1. What is your RR version + configuration.
2. Logs (because that log entry is not from the RR).
3. Do you use `->complete()` method inside the PHP Worker?

**Reply by QuietImprovement** [reply]
Hi @rustatian ,

The config that I use, and the version is v2023.3.12

```YAML
version: "3"

rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  middleware: ["static", "gzip"]
  uploads:
    forbid: [".php", ".exe", ".bat"]
  static:
    dir: "public"
    forbid: [".php"]
  pool:
    max_jobs: 1
    num_workers: 2
    supervisor:
      max_worker_memory: 128
      exec_ttl: 20s
      idle_ttl: 120s
      ttl: 3600s
      destroy_timeout: 60s
      watch_tick: 30s

sqs:
  key: key
  secret: secret
  region: us-east-2	
  endpoint: http://localstack:4566
jobs:
  num_pollers: 0
  pipeline_size: 100000
  pool:
    num_workers: 0
    max_jobs: 0
    debug: true
  consume: ["queue-name"]
  pipelines:
    queue-name:
      driver: sqs
      config:
        prefetch: 0
        consume_all: true
        skip_queue_declaration: true
        queue: queue-name

logs:
  encoding: console
  level: debug
  mode: development
  err_output: stderr
  output: stderr

  channels:
    http:
      level: debug
    server:
      level: debug
      mode: raw
```

2. So I think this log is coming from Baldinof\RoadRunnerBundle

3. I think complete is not used, [HttpWorker.php](https://github.com/Baldinof/roadrunner-bundle/blob/3.x/src/Worker/HttpWorker.php)
