### DISCUSSION TITLE
SQS message consumed but without any trace

### DISCUSSION THREAD

**Discussion by achref-riahi** [roadrunner-server/roadrunner#1888] [Q&A]
Hi, while testing a SQS message consumer using RR jobs, i found that some messages are consumed but without any trace.

For example, for 500 messages, ~ 450 are consumed correctly, because i can see the job plugin log of them, but 50 disappeared without any trace. For 100 messages  ~ 15 messages disappeared ...

My config,

```YAML
version: "3"

rpc:
  listen: "tcp://127.0.0.1:6001"

server:
  command: consumer.php
  relay: pipe

sqs:
  key: key
  secret: secret
  region: us-east-2	
  endpoint: https://sqs.us-east-2.amazonaws.com
jobs:
  num_pollers: 20
  pipeline_size: 100000
  pool:
    num_workers: 20
    max_jobs: 0
    allocate_timeout: 60s
    destroy_timeout: 60s
    debug: false
  consume: ["queue-name"]
  pipelines:
    queue-name:
      driver: sqs
      config:
        prefetch: 20
        consume_all: true
        skip_queue_declaration: true
        queue: queue-name

logs:
  encoding: console
  level: debug
  mode: development
  err_output: stderr
  output: stderr

  channels:
    jobs:
      level: debug
    server:
      level: debug
      mode: raw
```
