### DISCUSSION TITLE
I have a problem with starting RoadRunner

### DISCUSSION THREAD

**Discussion by frankii91** [roadrunner-server/roadrunner#1949] [Q&A] [answered]
I have a problem with starting RoadRunner

error I have during startup:
```
2024-06-22T22:19:52+0000        DEBUG   rpc             plugin was started      {"address": "tcp://127.0.0.1:8889", "list of the plugins with RPC methods:": ["lock", "informer", "app", "resetter"]}
handle_serve_command: Function call error:
        serve error from the plugin *http.Plugin stopping execution, error: static_pool_allocate_workers: WorkerAllocate:
        goridge_frame_receive: unexpected EOF
```

I will add that I do not have full access to the server environment but it is large ... I do not know what the problem is so I am not able to react and check ... I have dedicated ports for this service 8888 and 8889, but the service also tries to port 6061 and they failed I changed the configuration and had to reserve port 6061 for my freebsd server user, previously I had the error [ERROR] debug server stopped with error: listen tcp :6061: bind: operation not permitted

maybe someone can help?

or maybe I just need to compile my own php and have full control over it? I haven't tried it because it's a very tedious process and I wouldn't want to go through it...

.rr.yaml

```yaml
version: '3'

rpc:
  listen: "tcp://127.0.0.1:8889"

server:
  command: "php /home/..../public/index.php"

http:
  address: "0.0.0.0:8888"
  workers:
    command: "php /home/..../public/worker.php"
    pool:
      num_workers: 4

logs:
  mode: development
  level: debug
  output: stderr
```

worker.php

```php
<?php

use Spiral\RoadRunner\Worker;
use Spiral\RoadRunner\Http\PSR7Worker;
use Nyholm\Psr7\Factory\Psr17Factory;

require 'vendor/autoload.php';

$worker = Worker::create();
$psr17Factory = new Psr17Factory();
$psr7Worker = new PSR7Worker($worker, $psr17Factory, $psr17Factory, $psr17Factory);

while ($req = $psr7Worker->waitRequest()) {
    try {
        $response = new \Nyholm\Psr7\Response();
        $response->getBody()->write("Hello, World!");

        $psr7Worker->respond($response);
    } catch (\Throwable $e) {
        $psr7Worker->getWorker()->error((string)$e);
    }
}

```
index.php
```
<?php

echo "Hello, World!";
```
