### DISCUSSION TITLE
Problem with StartRoadRunnerCommand.php:188 - getPort() - Unsupported operand types: string - int

### DISCUSSION THREAD

**Discussion by JosephCastro** [roadrunner-server/roadrunner#1975] [General]
Hi

Anyone can help me this error please.

I trying to start RR (v2.12.3) with PHP 8.3 and Laravel 10.X.

I get this error: 

```
{"level":"info", "logger":"server", "msg":"{"message":"Unsupported operand types: string - int","context":{"exception":{"class":"TypeError","message":"Unsupported operand types: string - int","code":0,"file":"/var/www/html/vendor/laravel/octane/src/Commands/StartRoadRunnerCommand.php:188"}},"channel":"STAGING","extra":{},"severity":"ERROR","time":"2024-07-23T17:48:21.866-04:00"}
", "ts":1.7217713018670228E9}
```

AFAIK this try to get the port, but it's a string, instead of an int, but I check the roadrunner.yaml (below) and I pass the value as int.

This code in StartRoadRunnerCommand.php:
```php
protected function rpcPort()
    {
        return $this->option('rpc-port') ?: $this->getPort() - 1999;
    }
```

And this is the yaml:

```yaml
rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php /var/www/html/artisan octane:start --server=roadrunner --host=0.0.0.0 --port=${PORT:-8080}"

logs:
  mode: production
  encoding: json
  channels:
    stdout:
      type: stdout
      level: debug
    stderr:
      type: stderr
      level: error

http:
  address: 0.0.0.0:${PORT:-8080}
  workers:
    command: "php /var/www/html/artisan octane:start --server=roadrunner --host=0.0.0.0 --port=${PORT:-8080}"
  pool:
    num_workers: 4
```

**Comment by rustatian** [comment]
Hey @JosephCastro 👋 
RR v2.* is not supported and hugely outdated, please, update to v2024.1.x
IIRC, Laravel Octane doesn't use RR yaml configuration, and you can configure everything in PHP.

**Reply by JosephCastro** [reply]
Hi @rustatian 

Also the log config ? Because I have some troubles logging in cloud run (gcp), that's why I move to yml configuration.

I'll try the new version, thanks !!

**Reply by rustatian** [reply]
Also, keep in mind, your logger configuration is incorrect: 
```yaml
logs:
  mode: production
  encoding: json
  channels:
    stdout:
      type: stdout
      level: debug
    stderr:
      type: stderr
      level: error
```
Channels are not stdout/stderr. They are per-plugin channels. So, you can't use `stdout` for a channel, but you can use `http` (plugin) as a channel. You can read more here: https://docs.roadrunner.dev
