### DISCUSSION TITLE
URI not present in the HTTP access logs

### DISCUSSION THREAD

**Discussion by shieldz80** [roadrunner-server/roadrunner#1995] [Q&A] [answered]
Hello,

I've enabled access logs in my roadrunner configuration, but unfortunately the logs do not include the URI being requested. A log looks something like

```
2024-08-28T14:47:29+0000        INFO    http            http access log {"read_bytes": 0, "write_bytes": 0, "status": 204, "method": "GET", "URI": "", "remote_address": "172.19.30.5:60968", "query": "", "content_len": 0, "host": "my-test-host.wip", "user_agent": "", "referer": "", "time_local": "28/Aug/24:14:47:29 +0000", "request_time": "2024-08-28T14:47:29+0000", "start": "2024-08-28T14:47:29+0000", "elapsed": 0}
```

As you can see the URI field in the log is empty. Is there something I'm missing in the configuration? Config file looks like this

```yaml
version: "3"

server:
  command: "php bin/rr-http-worker.php"
  user: ${APP_USER}

rpc:
  listen: tcp://127.0.0.1:6001

status:
  address: 127.0.0.1:2114

http:
  address: 127.0.0.1:8080
  fcgi:
    address: tcp://0.0.0.0:9123
  pool:
    debug: ${RR_DEBUG:-false}
    max_jobs: 1000
    allocate_timeout: 30s
    reset_timeout: 30s
    destroy_timeout: 30s
    supervisor:
      ttl: 3600s
      idle_ttl: 120s
      max_worker_memory: 128
      exec_ttl: 60s
  access_logs: true

logs:
  output: stdout
```

Maybe it's relevant, I am running this setup in a docker container.

Thanks in advance for any clarifications.
