### DISCUSSION TITLE
Should we have cron jobs?

### DISCUSSION THREAD

**Discussion by graid2030** [roadrunner-server/roadrunner#2032] [Ideas]
It can be a new plugin like a service
example:
```yaml
version: "3"

cron:
  analytics:
    mask: "0 0 1 * *" // or "@monthly"
    cron_name_in_log: true
    timeout_stop_sec: 100
    run_once: true // or process_num=1
    exec_timeout: 0s
    command: "php analytics.php"
    env:
      - foo: "BAR"
    user: "www-data"
```

**Comment by graid2030** [comment]
And it's a bit inconsistent 
```
timeout_stop_sec: 100
exec_timeout: 0s
```
but we already have that.

**Reply by rustatian** [reply]
Hey @graid2030 👋 
We already have the `service` plugin where you can start any number of processes with the custom commands. Docs: https://docs.roadrunner.dev/docs/plugins/service

**Reply by graid2030** [reply]
As I said it's like service, but we can not schedule service command, right?
Most important part here
`mask: "0 0 1 * *" // or "@monthly"`

**Reply by rustatian** [reply]
You can do that inside your PHP script or basically in any program you execute in the `command` option. But honestly speaking, there are much more specialized tools to do that rather than RR.

**Reply by rustatian** [reply]
But, you know, I'm always open to PRs. We also have a special community plugins section in the documentation. Thus, if you create such a plugin, I'd be happy to add it to our docs (RR can be built with external plugins with Velox).

**Reply by graid2030** [reply]
This is the same idea for which the "service" plugin exists. For example, I can add CronJobs to Kuber or install cron iinside container. But we already have RR, which manages PHP processes.

**Reply by graid2030** [reply]
I'm still testing the idea that it's not just me who cares about this. Writing a plugin just for myself, especially since I've already found a workaround, is a thankless task =)

**Reply by rustatian** [reply]
This is your contribution to OSS, definitely not a thankless task :)

**Reply by hsemix** [reply]
I would be one of the happiest users if cron was part of RR, I mean, the queue plugin saves me a ton of issues, I don't have to worry about supervising the queue worker, I think it would be a good addition, but that's just me, I don't know about others.

**Reply by rustatian** [reply]
Feel free to create a feature request for that 😃

**Reply by ryan053857** [reply]
I recently wrote a simple cron plugin in my project. In two days I will try to submit a request.

**Comment by ryan053857** [comment]
I had the same problem. My solution is the roadrunner service.

First I install an extension package `jobbyphp/jobby` in php and write a console php program:

```php
<?php

declare(strict_types=1);

namespace App\Command;

use App\Libraries\Core\Yii;
use Jobby\Jobby;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'scheduler',
    description: '定时任务',
    hidden: false,
)]
final class SchedulerCommand extends Command
{
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $jobby = new Jobby();
        $this->registerTasks($jobby);

        while (true) {
            $waitTime = 60 - (time() % 60);
            sleep($waitTime);
            $jobby->run();
        }
    }

    private function registerTasks(Jobby $jobby)
    {
        $yii = Yii::aliases()->get('@root/yii');

        $jobby->add('HelloCommand', [
            'command' => "php {$yii} hello",
            'output' => Yii::aliases()->get('@runtime/logs/cron/hello.log'),
            'enable' => true,
            'schedule' => '* * * * *',
        ]);
    }
}


```

then add a cron service in rr.yml: 

```yaml
service:
  # 定时任务
  cron:
    service_name_in_log: true
    command: "php php/yii scheduler:run"
    timeout_stop_sec: 10
```

Isn't it more flexible to control how often timed tasks are executed in php?
