### DISCUSSION TITLE
AWS IAM Credentials override Credentials Defined in YAML File

### DISCUSSION THREAD

**Discussion by achref-riahi** [roadrunner-server/roadrunner#2036] [General]
Hi,

I have RR running in a pods running in AWS, i defined my config like this

```YAML
sqs:
  key: ${my_aws_access_key}
  secret: ${my_aws_secret}
  region: ${my_region}
  endpoint: ${my_secret}
```

If i use this creds to get the queue using aws cli, it works

`aws sqs get-queue-attributes --queue-url ...`

But RR show 400 Http error as error

I assume RR is trying to detect automaticly the aws creds from running env ? If yes how to solve this ?
