### DISCUSSION TITLE
Log Format

### DISCUSSION THREAD

**Discussion by ryan053857** [roadrunner-server/roadrunner#2044] [Q&A]
I know roadrunner uses a very powerful zaplogger internally, but there are some configurations that are not easy to customize. For example: time format, I want it to be in a readable local format in production, not an integer timestamp, and I also want to add caller configuration for my custom plugins. Is there any good way?

**Comment by rustatian** [comment]
Hey @shellphy 👋 
Not yet. You may check the PR in the `logger` repository. In the future, it'd be possible to provide a custom logger format.

**Reply by ryan053857** [reply]
channel cannot be configured separately for different services in the service plugin. Will it be supported in the future?

**Reply by rustatian** [reply]
Yep

**Reply by rustatian** [reply]
You mean, log format per channel?

**Reply by ryan053857** [reply]
I mean:

```yml
logs:
  channels:
    service.myservice1:
        log_output: "logs/myservice1.log"
    service.myservice2:
        log_output: "logs/myservice2.log"

services:
  myservice1:
    command: "xxx"
  myservice2:
    command: "yyy"
```
