### DISCUSSION TITLE
num_workers is invalid in nats jobs driver

### DISCUSSION THREAD

**Discussion by ryan053857** [roadrunner-server/roadrunner#2049] [Q&A] [answered]
When I use memory as the jobs driver, I have config:

```yml
jobs:
  consume: ["queue1", "queue2"]
  pool:
    num_workers: 1
  pipelines:
    queue1:
      driver: memory
      config:
        priority: 10
        prefetch: 1
    queue2:
      driver: memory
      config:
        priority: 10
        prefetch: 1
```

When I push 2 messages to queue1, I find that there is only one php worker.php process, which is ok.

But When I use nats as the jobs driver, I have config:

```yml
jobs:
  consume: ["queue1", "queue2"]
  pool:
    num_workers: 1
  pipelines:
    queue1:
      driver: nats
      config:
        priority: 10
        prefetch: 1
        delete_after_ack: true
        stream: default
    queue2:
      driver: nats
      config:
        priority: 10
        prefetch: 1
        delete_after_ack: true
        stream: default
```

I find that there are two php worker.php process. Unless I configure different streams for different pipelines. 

I don't really understand how the pool worker works, but I think it should be explicitly written in the documentation or restricted in the code to not allow the same stream to be used

**Comment by rustatian** [comment]
Hey @shellphy 👋 
What is the output of the `ps aux` ?

**Reply by ryan053857** [reply]
ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root          79  7.8  0.6 159792 47868 pts/3    S    20:47   0:00 php php/worker.php
root          80  7.8  0.6 159792 47944 pts/3    S    20:47   0:00 php php/worker.php

**Reply by ryan053857** [reply]
I know that in the nats jobs driver, each different pipeline should have a different stream name

**Reply by rustatian** [reply]
Are you sure that you stopped all RR instances? And have only 1. Driver does not have workers, only JOBS plugin allocates them. So, there is no difference what driver you'd use, memory, nats, etc.

**Reply by rustatian** [reply, marked as answer]
1. There is no bug: 
<img width="923" alt="image" src="https://github.com/user-attachments/assets/77b1d1d3-a95c-44d7-bcd7-8ef729148b1c">
I've double-checked, please, be sure that you don't have any other RR instances.

2. This PR is completely not related to the current discussion. RR purges messages only when it has attached listener. We can discuss this, and as the option - remove `Purge`.

**Reply by rustatian** [reply]
Again, how this related to the `num_workers` is invalid?

**Reply by rustatian** [reply]
Please move your messages to the correct thread. Then, create a ticket, describe your problem, and if you're willing to fix that problem (👍) create attach/create a PR.

**Comment by ryan053857** [comment]
config is:

```yml
nats:
  addr: nats://nats:4222

jobs:
  consume: ["queue1", "queue2"]
  num_workers: 1
  pipelines:
    queue1:
      driver: nats
      config:
        priority: 10
        prefetch: 1
        delete_after_ack: true
        subject: default_queue
        stream: default_queue
    queue2:
      driver: nats
      config:
        priority: 10
        prefetch: 1
        delete_after_ack: true
        subject: default_queue
        stream: default_queue
```

send `one` message to queue1, then there are `two` `php worker.php` processes. 

If I configure different streams for different pipelines, it will be normal:

```yml
...
    queue1:
         ...
         stream: default_queue1
         ...
    queue2:
         ...
         stream: default_queue2
        ...
```

So I think we should explain this situation in the documentation, with special attention.

**Reply by rustatian** [reply]
There is no connection between the number of workers and the stream name in the NATS plugin. I've double-checked that case, shared a screenshot with you above. In your case, this is either a misconfiguration or 2 RR instances running (might be one of it in the background).

**Reply by rustatian** [reply]
Moreover, you have an invalid configuration: https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1236, num_workers should be under the pool section.

**Reply by ryan053857** [reply]
I ran the test again

If I configured debug:

```yml
jobs
    pool:
        num_workers: 1
        debug: true
```

There will be two worker process. but if I set debug=false, it will be fine.

**Comment by ryan053857** [comment]
config is:

```yml
version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
    command: 'php worker.php'
nats:
    addr: nats://127.0.0.1:4222
logs:
    mode: development
    level: debug
jobs:
    consume: ["queue1", "queue2"]
    pool:
        num_workers: 1
        debug: true
    pipelines:
        queue1:
            driver: nats
            config:
                priority: 10
                prefetch: 1
                delete_after_ack: true
                subject: default_queue
                stream: default_queue
        queue2:
            driver: nats
            config:
                priority: 10
                prefetch: 1
                delete_after_ack: true
                subject: default_queue
                stream: default_queue
```

producer.php:

```php
<?php

use Spiral\Goridge\RPC\RPC;
use Spiral\RoadRunner\Jobs\Jobs;

require "vendor/autoload.php";


$jobs = new Jobs(
    RPC::create('tcp://127.0.0.1:6001')
);
$queue = $jobs->connect('queue1');
$task = $queue->create("dummy", 'hello');
$result = $queue->dispatch($task);
var_dump($result);
```

worker.php

```yml
<?php

use Spiral\Goridge;

ini_set('display_errors', 'stderr');
require "vendor/autoload.php";

$consumer = new Spiral\RoadRunner\Jobs\Consumer();

while ($task = $consumer->waitTask()) {
    try {
        echo "received " . $task->getPayload();
        sleep(20);
    } catch (\Throwable $e) {
        var_dump($e->getMessage());
    }
}
```

**Reply by rustatian** [reply]
Please, **read the docs** about the debug mode: https://docs.roadrunner.dev/docs/php-worker/developer#debug-mode

**Reply by rustatian** [reply]
This is how **DEBUG** mode works.

**Reply by ryan053857** [reply]
Yeah, but in debug mode, if I set the stream to a different value, or change the driver from nats to memory, there's still only one worker.

**Reply by rustatian** [reply]
Because you've received only 1 message from the queue. Again, in the debug mode, a new worker would be created per-message from the driver. You may see that in the logs.

**Reply by ryan053857** [reply]
➜  php-test ps aux | grep worker.php
shellphy         88307   0.0  0.0 410723792   1456 s091  S+    5:27PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox --exclude-dir=.venv --exclude-dir=venv worker.php
➜  php-test php producer.php        
object(Spiral\RoadRunner\Jobs\Task\QueuedTask)#594 (5) {
  ["name":protected]=>
  string(5) "dummy"
  ["payload":protected]=>
  string(5) "hello"
  ["headers":protected]=>
  array(0) {
  }
  ["id":protected]=>
  string(36) "b2a7ea78-b146-497c-803f-ca08fa887bd0"
  ["pipeline":protected]=>
  string(6) "queue1"
}
➜  php-test ps aux | grep worker.php
shellphy         88326   0.0  0.0 410723792   1456 s091  S+    5:27PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox --exclude-dir=.venv --exclude-dir=venv worker.php
shellphy         88318   0.0  0.1 411087488  19920 s092  S     5:27PM   0:00.02 php worker.php
shellphy         88316   0.0  0.1 411086464  19808 s092  S     5:27PM   0:00.02 php worker.php





➜  php-test rr serve
2024-11-21T09:28:33+0000        DEBUG   rpc             plugin was started      {"address": "tcp://127.0.0.1:6001", "list of the plugins with RPC methods:": ["app", "lock", "informer", "jobs", "resetter"]}
2024-11-21T09:28:33+0000        DEBUG   jobs            initializing driver     {"pipeline": "queue1", "driver": "nats"}
2024-11-21T09:28:33+0000        DEBUG   jobs            initializing driver     {"pipeline": "queue2", "driver": "nats"}
2024-11-21T09:28:33+0000        DEBUG   jobs            driver ready    {"pipeline": "queue2", "driver": "nats", "start": "2024-11-21T09:28:33+0000", "elapsed": 2}
2024-11-21T09:28:33+0000        DEBUG   jobs            driver ready    {"pipeline": "queue1", "driver": "nats", "start": "2024-11-21T09:28:33+0000", "elapsed": 3}
2024-11-21T09:28:33+0000        DEBUG   nats            pipeline was started    {"driver": "nats", "pipeline": "queue2", "start": "2024-11-21T09:28:33+0000", "elapsed": 2}
2024-11-21T09:28:33+0000        DEBUG   nats            pipeline was started    {"driver": "nats", "pipeline": "queue1", "start": "2024-11-21T09:28:33+0000", "elapsed": 2}
[INFO] RoadRunner server started; version: 2024.2.1, buildtime: 2024-09-12T16:07:07Z
[INFO] sdnotify: not notified
2024-11-21T09:28:36+0000        DEBUG   jobs            job was pushed successfully     {"ID": "28306db8-512b-47fa-bc5c-96ed08c9cf01", "pipeline": "queue1", "driver": "nats", "start": "2024-11-21T09:28:36+0000", "elapsed": 0}
2024-11-21T09:28:36+0000        DEBUG   jobs            job processing was started      {"ID": "28306db8-512b-47fa-bc5c-96ed08c9cf01", "start": "2024-11-21T09:28:33+0000", "elapsed": 3026}
2024-11-21T09:28:36+0000        DEBUG   server          executing in debug mode, worker will be destroyed after response is received
2024-11-21T09:28:36+0000        DEBUG   jobs            job processing was started      {"ID": "28306db8-512b-47fa-bc5c-96ed08c9cf01", "start": "2024-11-21T09:28:33+0000", "elapsed": 3027}
2024-11-21T09:28:36+0000        DEBUG   server          executing in debug mode, worker will be destroyed after response is received
2024-11-21T09:28:36+0000        DEBUG   server          worker is allocated     {"pid": 88361, "max_execs": 1, "internal_event_name": "EventWorkerConstruct"}
2024-11-21T09:28:36+0000        DEBUG   server          worker is allocated     {"pid": 88360, "max_execs": 1, "internal_event_name": "EventWorkerConstruct"}
2024-11-21T09:28:36+0000        INFO    server          received hello
2024-11-21T09:28:36+0000        INFO    server          received hello

**Reply by ryan053857** [reply]
.rr.yaml:

```yml
version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
    command: 'php worker.php'
nats:
    addr: nats://127.0.0.1:4222
logs:
    mode: development
    level: debug
jobs:
    consume: ["queue1", "queue2"]
    pool:
        num_workers: 2
        debug: false
    pipelines:
        queue1:
            driver: nats
            config:
                priority: 10
                prefetch: 1
                delete_after_ack: true
                subject: default_queue
                stream: default_queue
        queue2:
            driver: nats
            config:
                priority: 10
                prefetch: 1
                delete_after_ack: true
                subject: default_queue
                stream: default_queue
```

producer.php:

```yml
<?php

use Spiral\Goridge\RPC\RPC;
use Spiral\RoadRunner\Jobs\Jobs;

require "vendor/autoload.php";


$jobs = new Jobs(
    RPC::create('tcp://127.0.0.1:6001')
);
$queue = $jobs->connect('queue1');
$task = $queue->create("dummy", 'hello');
$result = $queue->dispatch($task);
var_dump($result);
```

worker.php:

```yml
<?php

use Spiral\Goridge;

ini_set('display_errors', 'stderr');
require "vendor/autoload.php";

$consumer = new Spiral\RoadRunner\Jobs\Consumer();

while ($task = $consumer->waitTask()) {
    try {
        echo "received " . $task->getPayload();
        sleep(20);
    } catch (\Throwable $e) {
        var_dump($e->getMessage());
    }
}
```

test:

```
➜  php-test ps aux | grep worker.php
shellphy         89308   0.0  0.0 410731984   1472 s091  S+    5:43PM   0:00.00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn --exclude-dir=.idea --exclude-dir=.tox --exclude-dir=.venv --exclude-dir=venv worker.php
shellphy         89303   0.0  0.1 410956976  20048 s092  S     5:43PM   0:00.03 php worker.php
shellphy         89302   0.0  0.1 411094656  20048 s092  S     5:43PM   0:00.03 php worker.php
➜  php-test php producer.php 
object(Spiral\RoadRunner\Jobs\Task\QueuedTask)#594 (5) {
  ["name":protected]=>
  string(5) "dummy"
  ["payload":protected]=>
  string(5) "hello"
  ["headers":protected]=>
  array(0) {
  }
  ["id":protected]=>
  string(36) "eaeb906a-9644-4bae-a20e-fec5ea7988c1"
  ["pipeline":protected]=>
  string(6) "queue1"
}
```

log: 

```
➜  php-test rr serve
2024-11-21T09:43:46+0000        DEBUG   rpc             plugin was started      {"address": "tcp://127.0.0.1:6001", "list of the plugins with RPC methods:": ["informer", "jobs", "resetter", "lock", "app"]}
2024-11-21T09:43:46+0000        DEBUG   jobs            initializing driver     {"pipeline": "queue1", "driver": "nats"}
2024-11-21T09:43:46+0000        DEBUG   jobs            initializing driver     {"pipeline": "queue2", "driver": "nats"}
2024-11-21T09:43:46+0000        DEBUG   jobs            driver ready    {"pipeline": "queue2", "driver": "nats", "start": "2024-11-21T09:43:46+0000", "elapsed": 1}
2024-11-21T09:43:46+0000        DEBUG   jobs            driver ready    {"pipeline": "queue1", "driver": "nats", "start": "2024-11-21T09:43:46+0000", "elapsed": 2}
2024-11-21T09:43:46+0000        DEBUG   nats            pipeline was started    {"driver": "nats", "pipeline": "queue2", "start": "2024-11-21T09:43:46+0000", "elapsed": 1}
2024-11-21T09:43:46+0000        DEBUG   nats            pipeline was started    {"driver": "nats", "pipeline": "queue1", "start": "2024-11-21T09:43:46+0000", "elapsed": 1}
2024-11-21T09:43:46+0000        DEBUG   server          worker is allocated     {"pid": 89303, "max_execs": 0, "internal_event_name": "EventWorkerConstruct"}
2024-11-21T09:43:46+0000        DEBUG   server          worker is allocated     {"pid": 89302, "max_execs": 0, "internal_event_name": "EventWorkerConstruct"}
[INFO] RoadRunner server started; version: 2024.2.1, buildtime: 2024-09-12T16:07:07Z
[INFO] sdnotify: not notified
2024-11-21T09:43:52+0000        DEBUG   jobs            job was pushed successfully     {"ID": "eaeb906a-9644-4bae-a20e-fec5ea7988c1", "pipeline": "queue1", "driver": "nats", "start": "2024-11-21T09:43:52+0000", "elapsed": 1}
2024-11-21T09:43:52+0000        DEBUG   jobs            job processing was started      {"ID": "eaeb906a-9644-4bae-a20e-fec5ea7988c1", "start": "2024-11-21T09:43:46+0000", "elapsed": 5670}
2024-11-21T09:43:52+0000        DEBUG   jobs            job processing was started      {"ID": "eaeb906a-9644-4bae-a20e-fec5ea7988c1", "start": "2024-11-21T09:43:46+0000", "elapsed": 5670}
2024-11-21T09:43:52+0000        INFO    server          received hello
2024-11-21T09:43:52+0000        INFO    server          received hello
```

You can see two messages: `received hello`
