### DISCUSSION TITLE
How to add queues dynamically

### DISCUSSION THREAD

**Discussion by ryan053857** [roadrunner-server/roadrunner#2101] [Q&A]
I want to create queues to rr dynamically in php. But it seems that the queue name must be added to the consume configuration in .rr.yaml in advance.

My .rr.yaml:

```yaml
version: '3'
rpc:
    listen: 'tcp://127.0.0.1:6001'
server:
    command: 'php worker.php'
    relay: pipes
jobs:
    pool:
        num_workers: 2
        max_worker_memory: 100
```

worker.php:

```php
<?php

ini_set('display_errors', 'stderr');
require "vendor/autoload.php";

$consumer = new Spiral\RoadRunner\Jobs\Consumer();

while ($task = $consumer->waitTask()) {
    try {
        var_dump($task->getPayload());
        $task->ack();
    } catch (\Throwable $e) {
        $task->error((string)$e);
    }
}
```

producer.php

```php
<?php

use Spiral\Goridge\RPC\RPC;
use Spiral\RoadRunner\Jobs\Jobs;
use Spiral\RoadRunner\Jobs\Queue\MemoryCreateInfo;

ini_set('display_errors', 'stderr');
require "vendor/autoload.php";

$jobs = new Jobs(RPC::create('tcp://127.0.0.1:6001'));

$queue = $jobs->create(new MemoryCreateInfo(
    name: 'example',
    priority: 42,
    prefetch: 10,
));
$task = $queue->create("test", 'payload');
$result = $queue->dispatch($task);
var_dump($result);
```

If I add configuration ` consume: [ 'example' ]` in jobs section, the job processing was started. Is there any way I can start the job without adding configuration to consume?
