### DISCUSSION TITLE
Loss messages from Priority Queue

### DISCUSSION THREAD

**Discussion by Buravenkov** [roadrunner-server/roadrunner#2120] [Q&A] [answered]
Hello, we have encountered the following issue. When redeploying the application, the old k8s pod stops working, and a new one is deployed. During this process, we lose messages from the priority queue. To process the queues, we use the jobs plugin with the Kafka driver configured with the following settings.

```
kafka:
  brokers: "${KAFKA_BROKER}"

jobs:
  num_pollers: 6
  timeout: 10
  pipeline_size: 3000
  pool:
    num_workers: 5
    allocate_timeout: 30s
    supervisor:
      max_worker_memory: 128
      watch_tick: 30s
  pipelines:
    topic1:
      driver: kafka
      config:
        priority: 1
        prefetch: 100
        consumer_options:
          topics: ["topic1"]
          consume_regexp: false
        group_options:
          group_id: php_kafka_consumer
    topic2:
      driver: kafka
      config:
        priority: 1
        prefetch: 500
        consumer_options:
          topics: [ "topic2" ]
          consume_regexp: false
        group_options:
          group_id: php_kafka_consumer
    topic3:
      driver: kafka
      config:
        priority: 1
        prefetch: 500
        consumer_options:
          topics: [ "topic3" ]
          consume_regexp: false
        group_options:
          group_id: php_kafka_consumer
    topic4:
      driver: kafka
      config:
        priority: 1
        prefetch: 500
        consumer_options:
          topics: [ "topic4" ]
          consume_regexp: false
        group_options:
          group_id: php_kafka_consumer
    topic5:
      driver: kafka
      config:
        priority: 1
        prefetch: 100
        consumer_options:
          topics: [ "topic5" ]
          consume_regexp: false
        group_options:
          group_id: php_kafka_consumer
  consume:
    - topic1
    - topic2
    - topic3
    - topic4
    - topic5
```

As far as I understand, when messages enter the PQ, the offsets in the topics are immediately shifted. Could you please tell me if it’s possible to set `enable.auto.commit = false` and commit the offset only after the message has been processed by the worker? Or at least after the message has been loaded into the worker's memory?

Php worker execute following code:
```
        try {
            while ($task = $this->consumer->waitTask()) {
                try {
                    $handler = $this->getHandler($task->getQueue());
                    $handler->handle($task);
                } catch (Throwable $e) {
                    $this->logger->error(
                        "Task processing error: {$e->getMessage()}",
                        ['payload' => $task->getPayload()]
                    );
                    $task->fail($e->getMessage());
                    continue;
                }
                $task->complete();
            }
        } catch (Throwable $e) {
            $this->logger->error('Consumer error:', ['message' => $e->getMessage()]);
        }
```
And we use a 2023.1.1 version of roadrunner app and this `"spiral/roadrunner-jobs": "^3.0"` composer-package. Please let me know if you need any additional information.
