### DISCUSSION TITLE
Possible to test Google Pub/Sub against real google project?

### DISCUSSION THREAD

**Discussion by titzel24** [roadrunner-server/roadrunner#2153] [Q&A]
Hello there :wave: 

I am evaluating Google Pub/Sub and I would need to implement consumers into my existing application using roadrunner server.

I found that you recently added native support for GPS ( https://docs.roadrunner.dev/docs/queues-and-jobs/google-pub-sub ) and wanted to try this with my real google cloud project.

But unfortunately I fail setting it up. I only get the following error in the console while booting the server:
```
{
  "level": "ERROR",
  "ts": "2025-03-18T05:08:12+0000",
  "logger": "jobs        ",
  "msg": "failed to initialize driver",
  "pipeline": "exchangerates",
  "driver": "google_pub_sub",
  "error": "google_pub_sub_consumer: context deadline exceeded"
}
```
There are no further error details visible.

In the docs you mention configuring a GPS host (example is set to `127.0.0.1:8085`). I tried using `pubsub.googleapis.com`.

My config currently looks like this:
```
google_pub_sub:
  insecure: true
  host: pubsub.googleapis.com

jobs:
  pool:
    num_workers: 10

  pipelines:
    exchangeRates:
      driver: google_pub_sub
      config:
        priority: 1
        project_id: dev-66321
        topic: exchangeRate-modified
        max_delivery_attempts: 3

```

Is it even possible to use the current GPS beta integration with a real google project?

If yes, I would highly appreciate if somebody could help me setting it up correctly :slightly_smiling_face:

**Comment by rustatian** [comment]
Hey @titzel24 👋🏻 
I'm using a `gcloud` emulator to test the driver (you may check my [docker-compose](https://github.com/roadrunner-server/google-pub-sub/blob/master/tests/env/docker-compose-emulator-local.yaml)).
And config:
```yaml
google_pub_sub:
  insecure: true
  host: 127.0.0.1:8085
```
Could you please try to use an emulator with that configuration?

**Reply by titzel24** [reply]
@rustatian Practically there is no error starting up the server when I use the emulator with the config you posted.

But I don't have any worker, too so I don't know whether it's possibly working or not.
When trying to add a worker I get the same error message like in my initial post.

```
jobs:
  pool:
    num_workers: 1

  pipelines:
    exchangeRates:
      driver: google_pub_sub
      config:
        priority: 1
        project_id: test
        topic: exchangeRate
        max_delivery_attempts: 3
```

I also created a topic and subscription named `exchangeRate` in the pubSub fake.
