### DISCUSSION TITLE
[Q] why rr workers not working with Laravel Octane?

### DISCUSSION THREAD

**Discussion by litan1106** [roadrunner-server/roadrunner#684] [Q&A] [answered]
I tried the rr command with Laravel Octane

## rr reset
```bash
rr reset -o rpc.listen=tcp://localhost:6001
```
### expected result
Resetting plugin: [http]  ∙∙●

## rr workers
```bash
rr workers -o rpc.listen=tcp://localhost:6001
```
### expected result
workers table

### instead I got an error
show_workers: informer_plugin_workers: no such service: server; informer_plugin_workers: no such service: server

**Comment by rustatian** [comment]
Hello @litan1106. Could you please show your `.rr.yaml` ?

**Reply by rustatian** [reply]
Ahh, I guess it's because you use Octane. Octane does not have a `.rr.yaml`. To see the `workers` table, you have to create a `.rr.yaml` with `server` and `rpc` sections OR specify `server` config with `-o` flags (`-o server.command=...`).

**Reply by rustatian** [reply]
We will make that simpler in future versions.

**Comment by litan1106** [comment]
@48d90782 @nunomaduro
I copied the Laravel Octane config to .rr.yaml during the testing.

```bash
rr workers -o rpc.listen=tcp://localhost:18001 -o server.command="php ./vendor/bin/roadrunner-worker"
```
I still got the error.
**show_workers: informer_plugin_workers: no such service: server; informer_plugin_workers: no such service: server**

here was my .rr.yaml
```yaml
rpc:
  listen: tcp://127.0.0.1:18001

server:
  command: "php ./vendor/bin/roadrunner-worker"
  env:
    - XDEBUG_SESSION: 1

http:
  address: 0.0.0.0:18000
  pool:
    num_workers: 1
    debug: "true"
    max_jobs: 250
    supervisor:
      exec_ttl: 90s
  static:
    dir: "public"
  middleware: ["static"]
  logs:
    mode: "development"
    level: "debug"
    output: "stdout"
    encoding: "json"

status:
  address: 127.0.0.1:2114
```
