### DISCUSSION TITLE
[Q] Docker error logs

### DISCUSSION THREAD

**Discussion by andreev1024** [roadrunner-server/roadrunner#689] [Q&A] [answered]
I have a Symfony app with `index.php`
```
while ($req = $httpFoundationWorker->waitRequest()) {
    try {
        $request = $httpFoundationFactory->createRequest($req);
        $response = $kernel->handle($request);
        $httpFoundationWorker->respond($psrHttpFactory->createResponse($response));
        $kernel->terminate($request, $response);
        $kernel->reboot(null);
    } catch (\Throwable $e) {
        $kernel->reboot(null);
        $logger = $kernel->getContainer()->get('logger.public')->error($e);
        $httpFoundationWorker->getWorker()->error($kernel->isDebug() ? (string) $e : 'Internal server error');
    }
}
```
and `.rr.yaml`
```
rpc:
    listen: tcp://:6001
server:
    command: "php /server/public/index.php"
http:
    address: "0.0.0.0:80"
    pool:
        num_workers: 1
logs:
    mode: production
    encoding: json
    level: debug
```

When I've got a Fatal for not Debug, the server returns:
```
http_plugin_serve_http: SoftJobError:
	error encoder:
	sync_worker_exec_payload: Internal server error
```
How could I get something like:
```
{"error": "internal server error"}
```

**Comment by rustatian** [comment, marked as answer]
You may use `raw` mode to get raw output from the worker.

**Reply by andreev1024** [reply]
config updated
```
logs:
    mode: production
    channels:
        http:
            level: debug
            mode: raw
        server:
            level: info
            mode: raw
```

It seems that nothing changed. I have the same HTTP response.
