### DISCUSSION TITLE
[Q] Run scripts (Linux/Windows) in the server's command

### DISCUSSION THREAD

**Discussion by rustatian** [roadrunner-server/roadrunner#796] [Q&A] [answered]
Hey, RR community. I want to ask you about one feature.
How likely do you guys need to have the ability to execute scripts in the `server` plugin, like this:
Script sample:
```bash
#!/usr/bin/env bash
setenv, generate config, etc etc etc
php ../roadrunner/tests/jobs_ok.php <- run PHP or bin
```

`rr.yaml` sample:
```yaml
server:
    command: "./start.sh" <-- script
    relay: "pipes"
    relay_timeout: "20s"
```

At the moment we have a limitation around such configuration because we check for the process PID and worker's PID to properly attach relay and they are mismatches. However, for such configuration, the child process will inherit process descriptors from the parent and we may safely send data to the script fd without checking the worker's FD.
