### DISCUSSION TITLE
[Q] Performance(RPS) is lower then expected. Why and what to do?

### DISCUSSION THREAD

**Discussion by dorantor** [roadrunner-server/roadrunner#876] [Q&A]
Context:

> $ rr -v
> rr version 2.6.6 (build time: 2021-12-15T10:32:57+0000, go1.17.4)

> $ php -v
> PHP 7.4.24 (cli) (built: Sep 23 2021 22:09:39) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.24, Copyright (c), by Zend Technologies
>     with blackfire v1.72.0~linux-x64-non_zts74, https://blackfire.io, by Blackfire

    
    
Q: **Why peak performance could be lower than expected?** 
Under average load response time is less then 20ms(nginx `$request_time`). Same values can be seen with Blackfire (3-10ms). Some network overhead and something for rr itself. 20-30 is fine. 230 workers and CPU load is 50% at max. Expected RPS 7500-11500(1000/responseTime_ms * workers). But peak RPS I can see in our VictoriaMetrics reported by rr - 5k-6k RPS. 2-4 times less then expected. Why could it be? Where to look? 
I understand why response time is growing under load - it's starting to queue requests(btw, how to monitor size of this queue?). But I don't understand why peak performance so low(about the same as we had with fpm, but a lot of network requests removed with rr, thanks to local in-memory cache). And what to do in order to fix it.

**Comment by rustatian** [comment]
Hey @dorantor. 98% of the performance is made by your worker (if we don't take into account OS, hardware, etc). You may read this tread -> https://github.com/spiral/roadrunner/discussions/799 it may give your some assumptions.
To see the queue size, use the `http` plugin with the `http_metrics` middleware with the `metrics` plugin.
```yaml
http:
  address: 127.0.0.1:15389
  middleware: [ "http_metrics" ]
  .....
```

metrics:
```yaml
  metrics:
    # Server metrics address
    #
    # Required for the production. Default: 127.0.0.1:9091, for the metrics 127.0.0.1:9091/metrics
    address: 127.0.0.1:3001
```

Then use can use grafana/Prometheus/curl -> `curl http://127.0.0.1:3001/metrics`. `rr_http_requests_queue` metric will point you to the actual queue size.

> 230 workers and CPU load is 50% at max

That says nothing. Because your workers might be blocked by some IO operations and become slow to respond. So it's near impossible to say what's wrong with your environment (or might be nothing wrong).

Try to share your config, your env, worker, as many details as you can. Also, take into account, that just multiplying response time by the number of workers is not a formula at all -> https://www.davepacheco.net/blog/2019/performance-puzzler-the-slow-server/.
It works only on the constant latency, which is almost impossible to achieve.

**Comment by rustatian** [comment]
Also, try to use a smaller number of workers. Should be a good reason to use such a big number. Try to use 10, then 20, and go on. Check the queue size at the same time. If you see, that with the 10 workers the queue size is 0, there is no sense to increase the number of workers (under high load for sure). Also, 10 workers are approx. 25MB/sec of throughput (network), with a simple `hello world` payload, might be the bottleneck in some other place (disk io, net).

**Reply by dorantor** [reply]
With 128 workers performance dropped to 3.5k RPS(vs 5.5k RPS with 230). So number of workers seems to be correct.

**Comment by dorantor** [comment]
Thx for `rr_http_requests_queue`!

Response time is quite consistent, so I made this rough assumption with some added extra. 
> That says nothing. Because your workers might be blocked by some IO operations and become slow to respond. So it's near impossible to say what's wrong with your environment (or might be nothing wrong).

You see, under 6k RPS response time is ~20ms. When there are more(than 6k) requests it is still ~20ms(according to blackfire). My understanding that it should be able to work with higher RPS. With rr lots of data moved from memc to local(array) storage, thus reducing network induced latency.
Will try to reduce amount of workers. We have quite capable server (64HT cores), so we set workers more than cores assuming that when some network operations will happen, another worker will be working.

rr config:
```yaml
server:
  # optional, only for linux under sudo user
  user: "exampleuser"
  command:  "php -dopcache.enable=1 -dopcache.enable_cli=1 /home/exampleuser/example.com/current/rr2-worker.php"

http:
  address: 10.42.2.11:8080
  pool:
    num_workers: 230
    max_jobs:    20480

  middleware: http_metrics

rpc:
  # TCP address:port for listening.
  #
  # Default: "tcp://127.0.0.1:6001"
  listen: tcp://127.0.0.1:6001

metrics:
  # prometheus client address (path /metrics added automatically)
  address: 10.42.2.11:2112

logs:
  mode: production
  level: warn
  channels:
    http:
      level: warn
      output: /var/log/rr.log
    server:
      output: /var/log/rr.log
```


Worker:
```php
<?php
/**
 * @var Goridge\RelayInterface $relay
 */

use Spiral\RoadRunner;
use Nyholm\Psr7;

ini_set('display_errors', 'stderr');

require_once __DIR__ . '/vendor/autoload.php';

$worker = RoadRunner\Worker::create();
$psrFactory = new Psr7\Factory\Psr17Factory();

$worker = new RoadRunner\Http\PSR7Worker($worker, $psrFactory, $psrFactory, $psrFactory);

$framework = new Project\Framework();
$framework->registerDebugHandlers();


// let's create a blackfire client
$config = new \Blackfire\ClientConfiguration();
$config->setClientId('....');
$config->setClientToken('....');

$blackfire = new \Blackfire\Client($config);

while ($req = $worker->waitRequest()) {
    try {
        $cookies = $req->getCookieParams();
        $probe = null;
        if (\array_key_exists('blackfire', $cookies) && '1' == $cookies['blackfire']) {
            // start blackfire probe
            try {
                $probe = $blackfire->createProbe();
            } catch (\Blackfire\Exception\ExceptionInterface $e) {
                // @see https://blackfire.io/docs/php/integrations/sdk#error-management
            }
        }
        // Send request to framework
        $frameworkResponse = $framework
            ->processHttpServerRequest($req)
        ;

        $resp = new Psr7\Response(
            $frameworkResponse->getStatusCode(),
            $frameworkResponse->getHeaders(),
            (string) $frameworkResponse->getBody()
        );

        $worker->respond($resp);

        if ($probe && \array_key_exists('blackfire', $cookies) && '1' == $cookies['blackfire']) {
            $profile = $blackfire->endProbe($probe);
        }
    } catch (\Throwable $e) {
        $worker->getWorker()->error((string) $e);
    }
}
```
