### ISSUE TITLE
[💡FEATURE REQUEST]: Add OpenTelemetry API support

### ISSUE THREAD

**Issue by litan1106** [roadrunner-server/roadrunner#1027]
### Plugin

Server

### I have an idea!

Please add OpenTelemetry support. With OpenTelemetry https://opentelemetry.io/, you don't have to add the support for each vendor. aka: NewRelic, Datadog, AppInsight, etc.

EDIT (@rustatian):
Update middleware:
- [x] gzip
- [x] headers
- [x] static
- [x] sendfile
- [x] cache

**Comment by rustatian** [comment]
Hey @litan1106. Yeah, we have plans about adding a unified standard for the traces and metrics information. But, still, vendor-specific drivers have better support for its API. I'll put that ticket for the ~`v2.10.0` RR version initially. Thanks for the proposal 👍🏻

**Comment by rustatian** [comment]
repo for the middleware: https://github.com/roadrunner-server/otel

**Comment by brettmc** [comment]
Hello, I'm a maintainer of [opentelemetry-php](https://github.com/open-telemetry/opentelemetry-php). I love the idea of having otel support in roadrunner.
I'd be happy to help/test/collaborate to try to ensure that code instrumented with the php library plays nicely with RR's implementation. Also as an FYI, there is a PSR proposal being worked on for tracing (I'm assuming we're talking about open telemetry's tracing signal, not metrics or logs).

**Comment by rustatian** [comment]
Hey @brettmc, nice to meet you 👋🏻 . That's great, thank you very much 👍🏻 I plan to start working on that plugin somewhere at the end of April (Go part). That would be nice if you could review the otel PHP part or test the beta version of the RR; when it is ready ⚡

**Comment by rustatian** [comment]
Update: In the initial implementation, RR via `rr-otel` HTTP middleware will support the following exporters:
1. All who support the OTLP protocol (datadog, new_relic, etc).
2. `stdout` exporter.
3. [Zipkin](https://zipkin.io)

I have plans to add support for the OTLP protocol also to the `gRPC` and `jobs` plugins (likely in the v2.11)

Draft configuration:

```yaml
otel:
  insecure: true
  compress: true
  exporter: zipkin
  service_name: rr_test
  service_version: 1.0.0
  endpoint: localhost:9411
  headers:
    - api-key: xxxx # needed for the new_relic
```

![image](https://user-images.githubusercontent.com/8040338/165189966-f3d1f8cd-04ac-46b1-90f4-3bd279e6bc80.png)

**Comment by brettmc** [comment]
If I were to instrument PHP code using opentelemetry-php, how would I get access to the parent trace id (probably the `http` span in the image above) from RR? I think that's critical to enable the [distributed trace part of the otel spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#tracing-signal).
Also, either RR or opentelemetry-php (or userland code which is sending outgoing http requests) would need to be responsible for injecting HTTP trace headers, distributed tracing of services further down the line.

**Comment by rustatian** [comment]
In the next alpha/beta release you'll be able to get the spans from the `OTLP` http request [field](https://github.com/roadrunner-server/http/blob/master/handler/request.go#L60). At the moment, it exists only on the RR side, but the idea is to use `opentelemetry-php` to extend these spans inside the PHP code.
OTLP structure field looks like [this](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#spancontext): `{"TraceID":"5d7d1faf902d6e0fa50e98e0b0a83454","SpanID":"30f396620dab37d0","TraceFlags":"01","TraceState":"","Remote":false}`

**Comment by brettmc** [comment]
That sounds like what otel calls "trace context propagation" - the data an otel trace implementation passes along that is understood by all other implementations. e.g PHP's implementation of the feature is https://github.com/open-telemetry/opentelemetry-php/blob/main/src/API/Trace/Propagation/TraceContextPropagator.php - note that it's agnostic as to where the info comes from, provided the keys match.
I think that if the OTLP fields above were injected into the http request via https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/trace_context.go#L47 using [w3c tracecontext headers](https://www.w3.org/TR/trace-context/#trace-context-http-headers-format), then PHP code doesn't need to be aware of whether it's a RR request or not. Conceptually RR is a separate service in a distributed system, which I think fits in with this design as RR is exporting its own traces.
IMO this is more closely aligned to spec (although you're not obligated to follow the spec).

**Comment by rustatian** [comment]
> That sounds like what otel calls "trace context propagation" 

This is a little bit different. I meat OTEL structure field, from the Go's POV this is `SpanContext` in the [docs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/overview.md#spancontext). They are similar from the information POV, but has a different structure.

> I think that if the OTLP fields above were injected into the http request via https://github.com/open-telemetry/opentelemetry-go/blob/main/propagation/trace_context.go#L47 using [w3c tracecontext headers](https://www.w3.org/TR/trace-context/#trace-context-http-headers-format), then PHP code doesn't need to be aware of whether it's a RR request or not. Conceptually RR is a separate service in a distributed system, which I think fits in with this design as RR is exporting its own traces.

Yeah, you're right. We use propagators as well: https://github.com/roadrunner-server/otel/blob/master/plugin.go#L102. My bad, I forgot to mention that. That's information duplication (I mean OTEL structure field and w3c headers), but this is an early draft. I wanted to try different ways to deliver the information to the PHP workers. Thanks for noting that 👍🏻 

We may agree on using only w3c propagators, so the PHP worker requires no modifications from the PHP worker side. Only get the needed headers, process and return them in the response.

**Comment by rustatian** [comment]
Ok, guys, this is the almost final configuration version:
```yaml
http:
  address: 127.0.0.1:15389
  middleware: [gzip, otel] # otel middleware should be applied first in the line (from right to left). Middleware order is: `request` --> `otel` -> `gzip` -> `http-plugin` -> `PHP worker`.
  pool:
    num_workers: 10

otel:
  insecure: false # HTTP OR HTTPS
  compress: true # use gzip compression
  client: http # http client (connect via http) or grpc
  custom_url: "" # applied only to the http client, if you use a non standard endpoint to receive traces
  exporter: otlp # otlp (datadog, new_relic (who support the OTLP protocol)), zipkin or stdout
  service_name: rr_test # your app name
  service_version: 1.0.0 # your app version
  endpoint: otlp.eu01.nr-data.net:4318 (new_relic) # zipkin - http://localhost:9411/api/v2/spans
  headers:
    - api-key: xxx (used for the new_relic)
```

The `v2.10.0-beta.1` will be available early next week.
All the tracing data as we agreed (w3c) will be in the request headers and can be accessed w/o any modifications on the PHP worker's side. 

I'll also provide a docker-compose.yaml with preconfigured zipkin endpoint. So, to test, you'll need to exec `docker compose up` and start rr via `./rr server -c .rr.yaml` (as usual).

CC: @brettmc

**Comment by rustatian** [comment]
@brettmc Here you are: https://github.com/roadrunner-server/roadrunner/releases/tag/v2.10.0-rc.2
With pre-release notes: https://github.com/roadrunner-server/roadrunner/releases/tag/v2.10.0-rc.1

**Comment by brettmc** [comment]
Hi @rustatian - it integrates well with opentelemetry-php!
![Screenshot from 2022-05-11 14-17-15](https://user-images.githubusercontent.com/4978962/167768223-e074730e-8b7b-4bb0-99bb-b163ca54e74f.png)

My only observation is that the incoming trace parent is the "gzip" span, but I would have thought the "http" one would make more sense (ie, in the above screenshot, both "rr/http" and "php/root" have "rr/gzip" as a parent span).

My example is available in github if you wanted something you can run quickly: https://github.com/brettmc/rr-otel-demo

**Comment by rustatian** [comment]
Hey @brettmc 👋🏻. Thank you very much for your help. I'll investigate the issue with the wrong parent span.

**Comment by rustatian** [comment]
@brettmc Found the issue, fixed:

![image](https://user-images.githubusercontent.com/8040338/167820692-77effecc-e7f9-4624-b06a-dbe242e552cd.png)

Now everything looks pretty 😄

**Comment by rustatian** [comment]
One note on how-to-use env variables:
Option1 (`.rr.yaml`):

```yaml
server:
  command: "php ../rr-e2e-tests/php_test_files/otel_worker.php"
  env:
    - OTEL_SERVICE_NAME: php
    - OTEL_TRACES_EXPORTER: otlp
    - OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
    - OTEL_EXPORTER_OTLP_ENDPOINT: http://127.0.0.1:4318
    - OTEL_PHP_TRACES_PROCESSOR: simple
  relay: pipes
```
Option2: (via docker-compose):

```docker
    environment:
      OTEL_SERVICE_NAME: php
      OTEL_TRACES_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: http://collector:4318
      OTEL_PHP_TRACES_PROCESSOR: simple
```

Both are valid.
