### ISSUE TITLE
[🐛 BUG]: Env variables values from global env is not used in server.env

### ISSUE THREAD

**Issue by tony-sol** [roadrunner-server/roadrunner#1034]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

System env vars are not used in config file server.env section.

Config example:
```
version: '2.7'

server:
    command: "php /var/www/app/public/index.php"
    env:
        - APP_RUNTIME: "Baldinof\\RoadRunnerBundle\\Runtime\\Runtime"
           REDIS_DSN: ${REDIS_DSN}
# other stuff
```
Env is definitely exists:

![Снимок экрана 2022-03-03 в 18 53 27](https://user-images.githubusercontent.com/33671815/156601078-2c52569e-7feb-4e94-933b-279fd98b4807.png)

but after run server, i've checked $_SERVER and got this:

![Снимок экрана 2022-03-03 в 18 51 46](https://user-images.githubusercontent.com/33671815/156600828-153ad4b7-4ee5-421c-a9de-d5baa42100e4.png)

Is this a real bug?

### Version

2.8.2

### Relevant log output

```shell
2022-03-03T18:38:24.892+0300    INFO    server          {"message":"An error occured: Unsupported DSN: \"${REDIS_DSN}\".","context":{"throwable":{"class":"Symfony\\Component\\Cache\\Exception\\InvalidArgumentException","message":"Unsupported DSN: \"${REDIS_DSN}\".","code":0,"file":"/var/www/app/vendor/symfony/cache/Adapter/AbstractAdapter.php:141"}},"level":400,"level_name":"ERROR","channel":"app","datetime":"2022-03-03T18:38:24.872590+03:00","extra":{"cm_x_trace_id":"3de0c6c0197a52062a22215f2e28e258","cm_environment":"dev","cm_type":"ERROR","cm_time":"2022-03-03T18:38:24+03:00","cm_service":"php-blank","cm_version":"0.0.1","cm_x_pub":false}}
```

**Comment by rustatian** [comment]
Hey, @Tony-Sol. The config should be as follows:

```yaml
version: '2.7'

server:
    command: "php /var/www/app/public/index.php"
    env:
        - APP_RUNTIME: "Baldinof\\RoadRunnerBundle\\Runtime\\Runtime"
        - REDIS_DSN: ${REDIS_DSN}
# other stuff
```
But, to use the `${}` notation, you should set that by yourself via: https://github.com/spiral/roadrunner-docs/blob/master/php/environment.md#using-environment-variables-in-the-configuration
