### ISSUE TITLE
[💡 FEATURE REQUEST]:  Substitute system env variables in *.env section in config

### ISSUE THREAD

**Issue by tony-sol** [roadrunner-server/roadrunner#1035]
### Plugin

Server

### Substitute system env variables in processing *.env section in config file
Like:
 - server.env
 - server.on_init.env

### When it may be useful:

For example, app has 2 config files depend of env - dev or prod and for better maintainability, assume that both files has exactly the same structure.

Also, dev environment is provided by docker-compose with passing env via `env_file`, example:
```env
MYSQL_ROOT_PASSWORD=temprootpassword
MYSQL_DATABASE=db
MYSQL_USER=user
MYSQL_PASSWORD=password
MYSQL_HOST=mysql
MYSQL_PORT=3306
```

So, according to this, configs are going to look like this or similar

dev.yaml:
```yaml
version: '2.7'
server:
  command: "php /var/www/app/public/index.php"
  env:
    - APP_ENV: dev
    - DATABASE_URL: "mysql://user:password@mysql:3306/db?serverVersion=5.7"
```
prod.yaml:
```yaml
server:
  command: "php /var/www/app/public/index.php"
  env:
    - APP_ENV: prod
    - DATABASE_URL: !vault |
         $ANSIBLE_VAULT;1.1;AES256 ...
```

This approach forces to duplicate knowledge about dev credentials in dev.yaml and .env - for app and for docker.

With env substitution, dev.yaml could written as:
```yaml
version: '2.7'
server:
  command: "php /var/www/app/public/index.php"
  env:
    - APP_ENV: dev
    - DATABASE_URL: "mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?serverVersion=5.7"
```
so every docker restart, `DATABASE_URL` always will be correct.

Just out of curiosity, i did a little research of [roadrunner-server/server](https://github.com/roadrunner-server/server) and it looks like this:
```patch
diff --git a/oninit.go b/oninit.go
index ef955d6..66c4d0b 100644
--- a/oninit.go
+++ b/oninit.go
@@ -66,7 +66,7 @@ func (p *Plugin) createProcess(env map[string]string, cmd string) *exec.Cmd {
 	// set env variables from the config
 	if len(env) > 0 {
 		for k, v := range env {
-			command.Env = append(command.Env, fmt.Sprintf("%s=%s", strings.ToUpper(k), v))
+			command.Env = append(command.Env, fmt.Sprintf("%s=%s", strings.ToUpper(k), os.ExpandEnv(v)))
 		}
 	}
 
diff --git a/plugin.go b/plugin.go
index e273175..356727f 100644
--- a/plugin.go
+++ b/plugin.go
@@ -91,7 +91,7 @@ func (p *Plugin) Init(cfg config.Configurer, log *zap.Logger) error {
 	// set env variables from the config
 	if len(p.cfg.Env) > 0 {
 		for k, v := range p.cfg.Env {
-			p.preparedEnvs = append(p.preparedEnvs, fmt.Sprintf("%s=%s", strings.ToUpper(k), v))
+			p.preparedEnvs = append(p.preparedEnvs, fmt.Sprintf("%s=%s", strings.ToUpper(k), os.ExpandEnv(v)))
 		}
 	}
 
@@ -159,7 +159,7 @@ func (p *Plugin) CmdFactory(env map[string]string) func() *exec.Cmd {
 		// append external envs
 		if len(env) > 0 {
 			for k, v := range env {
-				cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", strings.ToUpper(k), v))
+				cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", strings.ToUpper(k), os.ExpandEnv(v)))
 			}
 		}
 
@@ -203,7 +203,7 @@ func (p *Plugin) customCmd(env map[string]string) func(command string) *exec.Cmd
 		// append external envs
 		if len(env) > 0 {
 			for k, v := range env {
-				cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", strings.ToUpper(k), v))
+				cmd.Env = append(cmd.Env, fmt.Sprintf("%s=%s", strings.ToUpper(k), os.ExpandEnv(v)))
 			}
 		}
 
```
may be a solution, but also may cause some backward compatibility issues for users, who relies on current behavior.

What do you think?
