### ISSUE TITLE
[🐛 BUG]: Workers command fails if RPC port is not 6001 and using RR_RPC environment variable

### ISSUE THREAD

**Issue by jeremy-smith-maco** [roadrunner-server/roadrunner#1043]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

We are running roadrunner workers using Laravel Octane. We are running the `rpc.listen` setting on port 6002. We are able to run the `rr workers` command just fine and returns the correct results. If we then add the `RR_RPC` environment variable it tries to dial port 6001 for some reason. We don't normally set the `RR_RPC` variable but it is set inside of the roadrunner workers which causes the workers command to break but it should be a valid environment variable. It is set to the correct address but still dials the default port. It's only a problem because we are trying to call `rr workers` from inside an already running worker which has that variable set.

To get around it we are checking if the `RR_RPC` environment variable is set and if it is then call `rr workers` with `-o rpc.listener=$RR_RPC` instead which works correctly.

### Version

2.7.4

### Relevant log output

`.rr.yaml`

```
http:
  address: 127.0.0.1:9000
  pool:
    num_workers: 10
    max_jobs: 5000
    supervisor:
      exec_ttl: 3000s
  middleware: [ "static" ]

status:
  address: 127.0.0.1:2115

server:
  command: "php ./vendor/bin/roadrunner-worker"
  env:
    - APP_ENV: production
    - APP_BASE_PATH: "/home/jeremy/projects/name"
    - LARAVEL_OCTANE: "1"

rpc:
  listen: tcp://127.0.0.1:6002

logs:
  mode: production
  level: debug
  output: "/home/jeremy/projects/name/storage/logs/rr.log"
  err_output: "/home/jeremy/projects/name/storage/logs/rr_errors.log"
  encoding: console
```

Without `RR_RPC` set

```
 % ./rr workers
Workers of [http]:
+---------+-----------+---------+---------+---------+--------------------+
|   PID   |  STATUS   |  EXECS  | MEMORY  |  CPU%   |      CREATED       |
+---------+-----------+---------+---------+---------+--------------------+
|   28266 | ready     |       0 | 47 MB   |    0.00 | 46 minutes ago     |
|   28264 | ready     |       0 | 47 MB   |    0.00 | 46 minutes ago     |
|   28263 | ready     |       0 | 47 MB   |    0.00 | 46 minutes ago     |
|   28265 | ready     |       0 | 47 MB   |    0.00 | 46 minutes ago     |
|   28260 | ready     |       0 | 47 MB   |    0.00 | 46 minutes ago     |
+---------+-----------+---------+---------+---------+--------------------+
```

With `RR_RPC` set

```
 % export RR_RPC=tcp://127.0.0.1:6002
 % echo $RR_RPC
tcp://127.0.0.1:6002
 % ./rr workers
dial tcp 127.0.0.1:6001: connect: connection refused
```
