### ISSUE TITLE
[🐛 BUG]:  configuration version can't be greater that RR version

### ISSUE THREAD

**Issue by sergey-telpuk** [roadrunner-server/roadrunner#1050]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?
See error after updating RR from 2.7.1 to 2.8.2 my config bellow 
```yaml
version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001
```

### Version

2.8.2

### Relevant log output

```shell
configuration version can't be greater that RR version
```

**Comment by rustatian** [comment]
Hey @sergey-telpuk.
Everything is fine with the `v2.8.2`. I made the following steps:
1. Download `v2.8.2` from the releases page
2. Used your configuration:
```yaml
version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001
```

Output:
![image](https://user-images.githubusercontent.com/8040338/158024591-4fce3733-d3f9-472b-893d-a740b1a917cd.png)
