### ISSUE TITLE
[💡 FEATURE REQUEST]: WorkersPool supervisor config separation for workers/jobs or etc.

### ISSUE THREAD

**Issue by OO00O0O** [roadrunner-server/roadrunner#1054]
### Plugin

HTTP

### I have an idea!

It's very easy to misuse/misunderstand this config value, because it's only one for job. Everything else is for workers.

Example:
```yaml
http:  
  pool:
    supervisor:
      watch_tick: 1s 
      ttl: 20s <-- setting for worker
      idle_ttl: 5s <-- setting for worker
      exec_ttl: 10s <-- setting for job
      max_worker_memory: 1024 <-- setting for worker
```

Long term proposal:
```yaml
http:
  worker:
    num: 4
    ttl: 10s
    idle_ttl: 20s
    max_memory: 1024
  job:
    ttl: 60s
```

MVP would be renaming `exec_ttl` to `job_exec_ttl`
