### ISSUE TITLE
[🐛 BUG]: No longer able to set environment variables for service

### ISSUE THREAD

**Issue by andrei-dascalu** [roadrunner-server/roadrunner#1055]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Service configuration:

```yaml
service:
  svc:
    command: "some command to run a php"
    env:
      - MY_VAR: "one"
```

in 2.8.2, the php script running could access the value of MY_VAR
in 2.8.3, the value of MY_VAR is always seen as empty

### Version

2.8.3
