### ISSUE TITLE
[💡 FEATURE REQUEST]: auto-reload for the `service` plugin

### ISSUE THREAD

**Issue by steffendietz** [roadrunner-server/roadrunner#1080]
### Plugin

Service

### I have an idea!

It would be very convenient if the `reload` plugin would support restarting services defined using the `service` plugin.

A challenge is certainly to decide how services which should be reloaded are targeted. Reload all services vs. targeting specific service by name.

```yaml
service:
  some_service_1:
    command: php service1.php
  some_service_2:
    command: php service2.php
reload:
  interval: 1s
  patterns: [ ".php" ]
  # List of included for sync services (this is a map, where key name is a plugin name).
  services:
    http:
      dirs: [ "." ]
      recursive: true
      ignore: [ "vendor" ]
      patterns: [ ".php", ".go", ".md" ]
    # maybe using a prefix?
    service-some_service_1:
    # or reload all services?
    service:
    # or directly use service names?
    some_service_1:
    # or maybe specify in sub configuration?
    service:
      some_service_1:
        dirs: ...
```

This was also [discussed](https://discord.com/channels/538114875570913290/538114876497723392/960269269088747561) on discord. Thanks for consideration.
