### ISSUE TITLE
[🐛 BUG]: Grpc plugin crashes the server

### ISSUE THREAD

**Issue by rauanmayemir** [roadrunner-server/roadrunner#1101]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

My rr grpc plugin config is:
```
grpc:
  listen: tcp://0.0.0.0:35071
  proto:
  - proto/server.proto
```

RR server is failing to start with:
```
ERROR container/endure.go:406 error during the internal_init {"error": "endure_internal_init: Function call error:
    endure_call_init_fn:
    grpc_plugin_init:
    grpc_plugin_config: proto file 'proto/server.proto' does not exists"}
```

The path `proto/server.proto` is relative to the server root (as well as CWD).

It also fails with `/absolute/path/to/proto/server.proto`:
```
handle_serve_command: Serve error:
 endure_start:
 endure_serve_internal: Function call error:
 endure_call_serve_fn: got initial serve error from the Vertex grpc.Plugin, stopping execution, error: grpc_plugin_serve: WorkerAllocate:
 static_pool_allocate_workers: context deadline exceeded
```

### Version

2.9.1
