### ISSUE TITLE
[🐛 BUG]: Jobs plugin stops consuming tasks from RabbitMQ after reaching consumer_timeout

### ISSUE THREAD

**Issue by tntrex** [roadrunner-server/roadrunner#1103]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I got some kind of task that could run for a long time. I haven't know before that RabbitMQ has `consumer_timeout` option which is 30 minutes by default. And it seems that connection from RoadRunner to RabbitMQ breaks after reaching this timeout while processing this greedy task. I'm still able to push new task through RoadRunner, but them won't be consumed by the application.

Jobs configuration

```yml
jobs:
  consume: [ default ]
  pool:
    supervisor:
      max_worker_memory: 1024
  pipelines:
    default:
      driver: amqp
      config:
        priority: 10
        prefetch: 10
        queue: default
        durable: true
```

### Version

2.9.1
