### ISSUE TITLE
[💡 FEATURE REQUEST]: mTLS authentication

### ISSUE THREAD

**Issue by fwolfsjaeger** [roadrunner-server/roadrunner#1111]
### Plugin

HTTP

### I have an idea!

mTLS authentication is available for NGINX or Apache, it would be a nice addition to RoadRunner.
- NGINX: https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_verify_client
- Apache: https://httpd.apache.org/docs/current/mod/mod_ssl.html#sslverifyclient

Configuration could be similar to the gRPC plugin: grpc.tls.client_auth_type

**Comment by rustatian** [comment]
Hey @fwolfsjaeger, nice to meet you. Yeah, recently, we discussed that feature. It would be nice to have it. I'll plan for the versions `2.11` or `2.12` approx (1-2 months).

**Comment by fwolfsjaeger** [comment]
That is good news, thank you!

Let me know if I can help in any way.

**Comment by rustatian** [comment]
Sure, thank you 🤝

**Comment by rauanmayemir** [comment]
I wonder if it's possible to do termination on the dispatcher part, or make it somewhat compliance-friendly, i.e pass-through mTLS requests to the gRPC server so that termination happens there.

**Comment by rustatian** [comment]
@rauanmayemir The dispatcher part? I'm not sure that I understand you correctly.

**Comment by rustatian** [comment]
@fwolfsjaeger Hey, the feature will be available in the `2.10.1` (release date: 19.05).

**Comment by rustatian** [comment]
config: 
```yaml
  ssl:
    address: :8895
    redirect: false
    key: "fixtures/test-certs/test.key"
    cert: "fixtures/test-certs/test.pem"
    root_ca: "fixtures/test-certs/ca.cert"
    client_auth_type: require_and_verify_client_cert # <---- NEW
```
