### ISSUE TITLE
[🐛 BUG?]: TLS connection not working for PHP client using with gRPC plugin

### ISSUE THREAD

**Issue by s1lver** [roadrunner-server/roadrunner#1159]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

- Docker
- PHP 8.0.16
- gRPC 1.44.0

Continued discussion https://github.com/roadrunner-server/roadrunner/discussions/1102

I am trying to use TLS connection but I am getting an error:

> Status code: 14
> Status details: failed to connect to all addresses

I have created two containers. One is running a server application with rr. The other is running a client application.Combined containers into a common network
```bash
docker network connect server_network client_app
```

## Insecure connection

To test the connection, I took the implementation of the ping service in PHP

My rr config
```yaml
version: '2.8.4'

metrics:
  address: "0.0.0.0:2112"

server:
  command: "php server.php"
  relay: "pipes"
  relay_timeout: "20s"

grpc:
  listen: "tcp://0.0.0.0:9001"
  proto:
    - ./grpc/service/ping/proto/ping.proto
  tls:
    client_auth_type: no_client_certs
  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s
  pool:
    num_workers: 10
    max_jobs: 20
    allocate_timeout: 60s
    destroy_timeout: 60
```

In the client application I use `'credentials' => Grpc\ChannelCredentials::createInsecure()` as described in the documentation https://grpc.io/docs/languages/php/basics/

I call a test console command to test the service and connection in the client container

```bash
php ping.php
```
... and I get an answer

> Status code: 0
> Status details: 
> 2022-05-30 10:04:05: PONG

rr log:

> [INFO] RoadRunner server started; version: 2.10.2, buildtime: 2022-05-26T12:30:20+0000
> method was called successfully {"method": "/ping.Echo/ping", "start": 1653905045733453100, "elapsed": 25335300}

It also works in the IDE
```
GRPC localhost:9001/ping.Echo/ping

{
  "msg": "ping"
}
```
response

> localhost:9001/ping.Echo/ping
> 
> {
>   "msg": "2022-05-30 10:08:33: PONG"
> }

rr log output

> [INFO] RoadRunner server started; version: 2.10.2, buildtime: 2022-05-26T12:30:20+0000
> method was called successfully {"method": "/ping.Echo/ping", "start": 1653905045733453100, "elapsed": 25335300}
> method was called successfully {"method": "/ping.Echo/ping", "start": 1653905313772189400, "elapsed": 13165500}

## TLS connection

I change the rr configuration. I don't need to authorize the client, I just want to raise a secure connection. I generate self-signed certificates

```yaml
tls:
    key: "./docker/local/grpc/cert/test/server-key.pem"
    cert: "./docker/local/grpc/cert/test/bundle.pem"
    client_auth_type: no_client_certs
```

for simplicity I created a bash script

**server and root**
```bash
rm *.pem

echo "Generate CA's private key and self-signed certificate"
openssl req -x509 -newkey rsa:4096 -days 365 -nodes -keyout ca-key.pem -out ca-cert.pem -subj "/C=FR/ST=Occitanie/L=Toulouse/O=TestO/OU=Test/CN=grpc_server1/emailAddress=grpc_server@example.com"

echo "CA's self-signed certificate"
openssl x509 -in ca-cert.pem -noout -text

echo "Generate web server's private key and certificate signing request (CSR)"
openssl req -newkey rsa:4096 -nodes -keyout server-key.pem -out server-req.pem -subj "/C=FR/ST=Occitanie/L=Toulouse/O=TestO/OU=Test/CN=grpc_server/emailAddress=grpc_server@example.com"

echo "Use CA's private key to sign web server's CSR and get back the signed certificate"
openssl x509 -req -in server-req.pem -days 60 -CA ca-cert.pem -CAkey ca-key.pem -CAcreateserial -out server-cert.pem -extfile server-ext.cnf

echo "Server's signed certificate"
openssl x509 -in server-cert.pem -noout -text

echo "Create server bundle certificate"
cat server-cert.pem ca-cert.pem >> bundle.pem

echo "Verify a certificate"
openssl verify -CAfile ca-cert.pem server-cert.pem

```
**server-ext.cnf**
```ini
subjectAltName = @alt_names

[alt_names]
DNS.1 = grpc_server
DNS.2 = grpc_server:9001
IP = 0.0.0.0
```

**client**
```bash
echo "Generate client's private key and certificate signing request (CSR)"
openssl req -newkey rsa:4096 -nodes -keyout client-key.pem -out client-req.pem -subj "/C=FR/ST=Occitanie/L=Toulouse/O=TestO/OU=Test/CN=*.localhost/emailAddress=client@example.com"

echo "Use CA's private key to sign client's CSR and get back the signed certificate"
openssl x509 -req -in client-req.pem -days 60 -CA ca-cert.pem -CAkey ca-key.pem -CAcreateserial -out client-cert.pem -extfile client-ext.cnf

echo "Client's signed certificate"
openssl x509 -in client-cert.pem -noout -text
```
**client-ext.cnf**
```
subjectAltName=DNS:localhost,DNS:*.localhost,IP:0.0.0.0
```

In the PHP client
```php
'credentials' => ChannelCredentials::createInsecure()
```
and i get response

> Status code: 14
> Status details: failed to connect to all addresses

ok, change crendentials in SSL without params
```php
'credentials' => ChannelCredentials::createSsl()
```
and i get response

> Status code: 14
> Status details: failed to connect to all addresses

and with CA 
```php
'credentials' => ChannelCredentials::createSsl(file_get_contents('/var/www/ca-cert.pem')),
```

get response

> Status code: 14
> Status details: failed to connect to all addresses

I went through all possible options in rr grpc plufin : `request_client_cert, require_any_client_cert, verify_client_cert_if_given, require_and_verify_client_cert, no_client_certs` https://raw.githubusercontent.com/roadrunner-server/roadrunner/master/.rr.yaml - no effect

I checked the mTLS connection with different set of parameters

```yaml
tls:
    key: "./docker/local/grpc/cert/test/server-key.pem"
    cert: "./docker/local/grpc/cert/test/bundle.pem"
    root_ca: "./docker/local/grpc/cert/test/ca-cert.pem"
```

and 

```php
'credentials' => ChannelCredentials::createSsl(
    file_get_contents('/var/www/ca-cert.pem'),
    file_get_contents('/var/www/server-key.pem'),
    file_get_contents('/var/www/bundle.pem')
),
```

no effect...

i use trace GRPC option for runnig command
```bash
GRPC_VERBOSITY=debug GRPC_TRACE=all php ping.php
```
to make sure that the certificates are transmitted and it is possible to understand what's wrong... but rr output log is empty
I also checked the received certificates using curl requests and netcat
I tried to use the certificates obtained with https://github.com/FiloSottile/mkcert - no effect

I have no idea why this is happening. Perhaps there is some error in the rr or I'm doing something wrong(

### Version

2.10.2
