### ISSUE TITLE
[💡 FEATURE REQUEST]: Create a "stop" command

### ISSUE THREAD

**Issue by Baiquette** [roadrunner-server/roadrunner#1162]
### I have an idea!

Hey,
I have an idea!

**Introduction**
Roadrunner is able to reset the workers with `./rr reset` command but there is no command to "stop" the main process and the running workers.
It will be great to have a command like `./rr stop` to stop RR and the workers.

**Why ?**
In some case we need to start some custom services defined in the `.rr.yaml` file and start (for eg) the metrics in the meantime:
```yaml
# RR configuration version
version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

service:
  some_service_1:
    command: "php my-script.php"
    process_num: 1
    exec_timeout: 0
    remain_after_exit: false
    restart_sec: 0

metrics:
  address: localhost:2112
```

In this case we can in the `php my-script.php` call via RPC the Metrics plugin and add some defined/custom metrics:
```php
<?php

require "vendor/autoload.php";

use Spiral\RoadRunner\Environment;
use Spiral\Goridge\RPC\RPC;
use Spiral\RoadRunner\Metrics\Metrics;

$rpc = RPC::create(Environment::fromGlobals()->getRPCAddress());

$metrics = new Metrics($rpc);
$metrics->add('app_metric_counter', 1);
```

Once the PHP script executed, we cannot stop Roadrunner. The main process and the workers are still running.
When we want to execute a custom service into a Kubernetes Pod, we need to send a SIGINT or SIGTERM signal to Roadrunner. 
Thus Kubernetes will flag the pod as "Succeded" and will delete it.

**Other cases**
Also and for example, Laravel Octane kills the main process of RR to stop it when an user is entering the `php artisan octane:stop` command (https://github.com/laravel/octane/blob/1.x/src/RoadRunner/ServerProcessInspector.php#L69).
The `./rr stop`  would be "clearer" and will avoid to "kill" RR.

Thank you!!
