### ISSUE TITLE
[🐛 BUG]: Use amqp queue name as routing key by default

### ISSUE THREAD

**Issue by rauanmayemir** [roadrunner-server/roadrunner#1181]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

If one specifies a pipeline config like this:

```
jobs:
  pipelines:
    pipeline1:
      driver: amqp
      config:
        queue: queue1
    pipeline2:
      driver: amqp
      config:
        queue: queue2
```

Both queues will be bound to the `direct` exchange without routing key. This could lead to issues and even undesirable outcomes when pipelines process different kinds of messages.

I think amqp queue name should be used as a routing key by default.
This way, both pipelines will correctly process their corresponding queues.

### Version

2.10.4
