### ISSUE TITLE
[🐛 BUG]: Let's Encrypt certificate not issued in Docker

### ISSUE THREAD

**Issue by voskobovich** [roadrunner-server/roadrunner#1191]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I try to set up SSL for my project on RR. I follow this [documentation](https://roadrunner.dev/docs/app-server-https/2.x/en#let-s-encrypt), but after day I don`t have success result.

## Case 1 (main)

If I run the RR server with this config, the ports `80` and `443` are not reachable:

.rr.yaml:
```
version: "2.7"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  ssl:
    address: 0.0.0.0:8443
    redirect: false
    acme:
      certs_dir: rr_le_certs
      email: project@mail.com
      alt_http_port: 80
      alt_tlsalpn_port: 443
      challenge_type: http-01
      use_production_endpoint: false
      domains:
        - mydomain.com

logs:
  mode: production
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error
```

```
> curl http://mydomain.com/
curl: (7) Failed to connect to mydomain.com port 80 after 70 ms: Connection refused
```

```
> curl https://mydomain.com/
curl: (7) Failed to connect to mydomain.com port 443 after 76 ms: Connection refused
```

## Case 2

But if I remove a section with SSL params, then port `80` will be reachable.

.rr.yaml:
```
version: "2.7"

server:
  command: "php public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]

logs:
  mode: production
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error
```

```
> curl http://mydomain.com/
Normal response
```

```
> curl https://mydomain.com/
curl: (7) Failed to connect to mydomain.com port 443 after 76 ms: Connection refused
```

## Environment

My project work in an environment based on Docker (Linux Alpine).

Dockerfile:
```
FROM spiralscout/roadrunner:2.10.5 AS roadrunner
...

COPY --from=roadrunner /usr/bin/rr /usr/bin/rr
COPY --chown=82:82 ./public ./public
...

USER 82

WORKDIR /app

EXPOSE 8080
EXPOSE 8443

CMD ["/usr/bin/rr", "serve", "-c", "/app/.rr.yaml"]
```

docker-compose.yml:
```
version: '3.7'

services:
  app:
    restart: unless-stopped
    image: registry.gitlab.com/project/name/app:latest
    volumes:
      - ./.rr.yaml:/app/.rr.yaml:ro
    ports:
      - 80:8080
      - 443:8443
    environment:
      APP_ENV: prod
```

### Version

RoadRunner: 2.10.4
Docker image: php:8.1-alpine3.16
Docker version: 20.10.14, build a224086

### Relevant log output

```shell
app-1  | [INFO] RoadRunner server started; version: 2.10.4, buildtime: 2022-06-10T23:29:27+0000
app-1  | 2022-06-27T18:25:30.382+0300	INFO	http.obtain 	acquiring lock	{"identifier": "mydomain.com"}
app-1  | 2022-06-27T18:25:30.392+0300	INFO	http.obtain 	lock acquired	{"identifier": "mydomain.com"}
app-1  | 2022-06-27T18:25:30.416+0300	DEBUG	http.obtain 	trying issuer 1/2	{"issuer": "acme-v02.api.letsencrypt.org-directory"}
app-1  | 2022-06-27T18:25:35.116+0300	ERROR	http.obtain 	could not get certificate from issuer	{"identifier": "mydomain.com", "issuer": "acme-v02.api.letsencrypt.org-directory", "error": "HTTP 400 urn:ietf:params:acme:error:connection - 111.222.333.444: Connection refused"}
app-1  | 2022-06-27T18:25:35.116+0300	DEBUG	http.obtain 	trying issuer 2/2	{"issuer": "acme-staging-v02.api.letsencrypt.org-directory"}
app-1  | 2022-06-27T18:25:35.630+0300	DEBUG	http.acme_client	http request	{"method": "GET", "url": "https://acme-staging-v02.api.letsencrypt.org/directory", "headers": {"User-Agent":["CertMagic acmez (linux; amd64)"]}, "response_headers": {"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["822"],"Content-Type":["application/json"],"Date":["Mon, 27 Jun 2022 15:25:35 GMT"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
app-1  | 2022-06-27T18:25:35.799+0300	DEBUG	http.acme_client	http request	{"method": "HEAD", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/new-nonce", "headers": {"User-Agent":["CertMagic acmez (linux; amd64)"]}, "response_headers": {"Cache-Control":["public, max-age=0, no-cache"],"Date":["Mon, 27 Jun 2022 15:25:35 GMT"],"Link":["<https://acme-staging-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["000177i7a0b4upl6qrmBlt65R4JILJ9xcQIhIwr9J1ISfSU"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
app-1  | 2022-06-27T18:25:35.979+0300	DEBUG	http.acme_client	http request	{"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/new-acct", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["CertMagic acmez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["58819154"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["320"],"Content-Type":["application/json"],"Date":["Mon, 27 Jun 2022 15:25:35 GMT"],"Link":["<https://acme-staging-v02.api.letsencrypt.org/directory>;rel=\"index\"","<https://letsencrypt.org/documents/LE-SA-v1.2-November-15-2017.pdf>;rel=\"terms-of-service\""],"Location":["https://acme-staging-v02.api.letsencrypt.org/acme/acct/58819354"],"Replay-Nonce":["0001z-kkGgPN51DwZXHat9a1gyLlYsJ-tddGlNk0wd-pnxs"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 201}
app-1  | 2022-06-27T18:25:35.980+0300	INFO	http        	waiting on internal rate limiter	{"identifiers": ["mydomain.com"], "ca": "https://acme-staging-v02.api.letsencrypt.org/directory", "account": "project@mail.com"}
app-1  | 2022-06-27T18:25:35.980+0300	INFO	http        	done waiting on internal rate limiter	{"identifiers": ["mydomain.com"], "ca": "https://acme-staging-v02.api.letsencrypt.org/directory", "account": "project@mail.com"}
app-1  | 2022-06-27T18:25:36.169+0300	DEBUG	http.acme_client	http request	{"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/new-order", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["CertMagic acmez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["58819154"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["351"],"Content-Type":["application/json"],"Date":["Mon, 27 Jun 2022 15:25:36 GMT"],"Link":["<https://acme-staging-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Location":["https://acme-staging-v02.api.letsencrypt.org/acme/order/58819154/2964866584"],"Replay-Nonce":["0001S4J0Kk-Kc_AxkUWGDDoxbvcmjddcgiQ5tSv5K9VKVbM"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 201}
app-1  | 2022-06-27T18:25:36.342+0300	DEBUG	http.acme_client	http request	{"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2828347424", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["CertMagic acmez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["58819154"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["817"],"Content-Type":["application/json"],"Date":["Mon, 27 Jun 2022 15:25:36 GMT"],"Link":["<https://acme-staging-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["0001BqkgVvYHOxDu0ps3zyBucTkpf9Whjx2_uocc0KnQxPM"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
app-1  | 2022-06-27T18:25:36.342+0300	DEBUG	http.acme_client	no solver configured	{"challenge_type": "dns-01"}
app-1  | 2022-06-27T18:25:36.342+0300	DEBUG	http.acme_client	no solver configured	{"challenge_type": "tls-alpn-01"}
app-1  | 2022-06-27T18:25:36.342+0300	INFO	http.acme_client	trying to solve challenge	{"identifier": "mydomain.com", "challenge_type": "http-01", "ca": "https://acme-staging-v02.api.letsencrypt.org/directory"}
app-1  | 2022-06-27T18:25:36.515+0300	DEBUG	http.acme_client	http request	{"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/2828347424/xdTyjQ", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["CertMagic acmez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["58819154"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["193"],"Content-Type":["application/json"],"Date":["Mon, 27 Jun 2022 15:25:36 GMT"],"Link":["<https://acme-staging-v02.api.letsencrypt.org/directory>;rel=\"index\"","<https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2828347424>;rel=\"up\""],"Location":["https://acme-staging-v02.api.letsencrypt.org/acme/chall-v3/2828347424/xdTyjQ"],"Replay-Nonce":["0002AFEvPra3Uimv304zettKagcwkKRlti5iU5AcUjdODX8"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
app-1  | 2022-06-27T18:25:36.515+0300	DEBUG	http.acme_client	challenge accepted	{"identifier": "mydomain.com", "challenge_type": "http-01"}
app-1  | 2022-06-27T18:25:36.936+0300	DEBUG	http.acme_client	http request	{"method": "POST", "url": "https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/2828347424", "headers": {"Content-Type":["application/jose+json"],"User-Agent":["CertMagic acmez (linux; amd64)"]}, "response_headers": {"Boulder-Requester":["58819154"],"Cache-Control":["public, max-age=0, no-cache"],"Content-Length":["1034"],"Content-Type":["application/json"],"Date":["Mon, 27 Jun 2022 15:25:36 GMT"],"Link":["<https://acme-staging-v02.api.letsencrypt.org/directory>;rel=\"index\""],"Replay-Nonce":["0001pfWdkl0tIpzMGdAZ8NBICv_dt_-obCCFhgb8fi_e0DA"],"Server":["nginx"],"Strict-Transport-Security":["max-age=604800"],"X-Frame-Options":["DENY"]}, "status_code": 200}
app-1  | 2022-06-27T18:25:36.937+0300	ERROR	http.acme_client	challenge failed	{"identifier": "mydomain.com", "challenge_type": "http-01", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "111.222.333.444: Fetching http://mydomain.com/.well-known/acme-challenge/HqJ88-TLTHLAf5L-UBxXlcNbWHhmvKCxQM4iqkgf3q3: Connection refused", "instance": "", "subproblems": []}}
app-1  | 2022-06-27T18:25:36.937+0300	ERROR	http.acme_client	validating authorization	{"identifier": "mydomain.com", "problem": {"type": "urn:ietf:params:acme:error:connection", "title": "", "detail": "111.222.333.444: Fetching http://mydomain.com/.well-known/acme-challenge/HqJ88-TLTHLAf5L-UBxXlcNbWHhmvKCxQM4iqkgf3q3: Connection refused", "instance": "", "subproblems": []}, "order": "https://acme-staging-v02.api.letsencrypt.org/acme/order/58319154/2364866584", "attempt": 1, "max_attempts": 3}
app-1  | 2022-06-27T18:25:36.937+0300	ERROR	http.obtain 	could not get certificate from issuer	{"identifier": "mydomain.com", "issuer": "acme-staging-v02.api.letsencrypt.org-directory", "error": "HTTP 400 urn:ietf:params:acme:error:connection - 111.222.333.444: Fetching http://mydomain.com/.well-known/acme-challenge/HqJ88-TLTHLAf5L-UBxXlcNbWHhmvKCxQM4iqkgf3q3: Connection refused"}
app-1  | 2022-06-27T18:25:36.937+0300	ERROR	http.obtain 	will retry	{"error": "[mydomain.com] Obtain: [mydomain.com] solving challenge: mydomain.com: [mydomain.com] authorization failed: HTTP 400 urn:ietf:params:acme:error:connection - 111.222.333.444: Fetching http://mydomain.com/.well-known/acme-challenge/HqJ88-TLTHLAf5L-UBxXlcNbWHhmvKCxQM4iqkgf3q3: Connection refused (ca=https://acme-staging-v02.api.letsencrypt.org/directory)", "attempt": 1, "retrying_in": "1m0s", "elapsed": "6.544812003s", "max_duration": "720h0m0s"}
```
