### ISSUE TITLE
[🐛 BUG, PLATFORM: Windows]: the gRPC plugin prints a cutted error message on server starting

### ISSUE THREAD

**Issue by roxblnfk** [roadrunner-server/roadrunner#1193]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I want to know, how to be cool. But RoadRunner doesn't tell me. He cuts the message. Can you help me?

![{D8702E5E-1294-444E-8FBA-3B08C6C622C4}](https://user-images.githubusercontent.com/4152481/176140812-358d89fb-5013-4366-b261-9c3bfa91a7dd.png)

### FIles:

`rr.yaml`

```yaml
version: '2.7'

rpc:
    listen: tcp://127.0.0.1:6001

server:
    command: "php app.php"
    relay: pipes

grpc:
    listen: "tcp://0.0.0.0:9001"
    proto:
        - "service.proto"
    tls:
        client_auth_type: no_client_certs

    max_send_msg_size: 50
    max_recv_msg_size: 50
    max_connection_idle: 0s
    max_connection_age: 0s
    max_connection_age_grace: 0s
    max_concurrent_streams: 10

    ping_time: 1s
    timeout: 200s
    pool:
        num_workers: 1
        max_jobs: 0
        allocate_timeout: 60s
        destroy_timeout: 60

metrics:
    address: localhost:2112
```

---

`service.proto`

```protobuf
syntax = "proto3";

package api.test;

message foo {
  string bar = 1;
}
```

---

`app.php`

```php
<?= 'If you want to be c001 you just need to contribute to 0pensource.' ?>
```

### Version

rr version 2.10.5 (build time: 2022-06-23T21:11:16+0000, go1.18.3)
OS: Windows 10

### Relevant log output

```shell
handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex grpc.Plugin, stopping execution, error: grpc_plugin_serve: WorkerAllocate:
        static_pool_allocate_workers:
        goridge_frame_receive: CRC verification failed, bad header: If you wont to be c001 you just need
```
