### ISSUE TITLE
[🧹 CHORE]: OTEL UDP Client

### ISSUE THREAD

**Issue by L3tum** [roadrunner-server/roadrunner#1205]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

We're trying to use the Jaeger Agent with Roadrunner, but it seems like this is not supported by the OTEL Plugin for Roadrunner.
Specifically the Agent only [exposes UDP ports](https://www.jaegertracing.io/docs/1.6/deployment/#agent) while Roadrunner needs HTTP or gRPC.

I don't think this is a big change and if I were more proficient in Go I'd even make a PR but as I'm not I really hope you could make that change.

**Comment by rustatian** [comment]
Hey @L3tum 👋🏻 
`HTTP` or `gRPC` clients are used only for the `OTLP` protocol and do not affect Jaeger. You may try to remove the `client` option and set a UDP endpoint for the Jaeger exporter.

**Comment by L3tum** [comment]
Hey @rustatian ,
unfortunately I'm getting an `unsupported protocol schema "udp"` in that case. Same with adding `http://` in front of the host.
So far I've tried:
- udp://jaeger:6831 -> Unsupported protocol schema "udp"
- http://jaeger:6831 -> Connection Refused
- jaeger:6831 -> Unsupported protocol schema "jaeger"
- jaeger -> Unsupported protocol schema ""
- http://jaeger -> Connection Refused
- udp://jaeger -> Unsupported protocl schema "udp"

Each of these as the value for the `endpoint` key. I've also tried the port 6382, but that doesn't change anything. 

The whole config is the following:
````yaml
otel:
    insecure: true
    compress: false
    exporter: jaeger
    service_name: myproject
    service_version: 1.0.0
    endpoint: jaeger:6832
````
I've also tried removing the other two options (incure and compress) but that didn't change anything either.

This is all with a local jaeger/all-in-one but also with the K8s Operator and a manually deployed Agent Sidecar.

**Comment by rustatian** [comment]
Got u. I'll try to reproduce the problem, thanks for the report.

**Comment by rustatian** [comment]
@L3tum Hey 👋🏻 
I guess that the Jaeger OTEL client doesn't support UDP protocol because there is no sense in keeping it since we have the `gRPC` and `HTTP` endpoints.

The endpoint for the `Jaeger` should be in the following form (example):
http://localhost:14268/api/traces (full endpoint URL)

**Comment by rustatian** [comment]
RR sends the traces directly to the Jaeger. However, Jaeger **agent** and OTEL SDK support the UDP protocol. The problem is that RR doesn't support agents.

**Comment by rustatian** [comment]
I'll add a new `jaeger_agent` exporter to support the `udp` agents.

**Comment by L3tum** [comment]
Hey @rustatian !

Ah, it's one of those mismatches. Sometimes I'd like my org to switch to anything else from Jaeger^^

The `jaeger_agent` sounds good, thank you!
Will that be part of 2.10.7 or the next minor release? It's not time critical for us though, so no worries

**Comment by rustatian** [comment]
np 😃 It'll be part of the `2.10.7` ⚡

**Comment by rustatian** [comment]
```yaml
  otel:
    insecure: false
    compress: true
    exporter: jaeger_agent
    endpoint: localhost:6831
    service_name: rr_test
    service_version: 1.0.0
```
