### ISSUE TITLE
[🐛 BUG]: RR doesn't respect logs.output *[correct docs]*.

### ISSUE THREAD

**Issue by Warxcell** [roadrunner-server/roadrunner#1225]
### No duplicates 🥲.

- [x] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I have following config:

```

logs:
    mode: ${RR_LOGS}
    output: /app/tests/Codeception/_output/stderr.log
    err_output: /app/tests/Codeception/_output/stderr.log
```

After starting road runner I see the output in the console, rather than in the file.

### Version (rr --version)

2.7.5
2.11.0-beta.1

### Relevant log output

```shell
After starting road runner I see the output in the console, rather than in the file.
```
