### ISSUE TITLE
[🐛 BUG]: Environment variables in services are lowecased

### ISSUE THREAD

**Issue by viktorprogger** [roadrunner-server/roadrunner#1262]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

This sample config
```yaml
version: '2.7'

service:
  test:
    command: php test.php
    env:
      XDEBUG_MODE: off
```

`test.php` file contents:L
```php
<?php

var_export(getenv());
```

`rr serve` will output environment variables in php process. You'll see `xdebug_mode` instead of `XDEBUG_MODE`.

### Version (rr --version)

2.10.6
