### ISSUE TITLE
[💡 FEATURE REQUEST]: Add automatic retry on Kafka connection failure

### ISSUE THREAD

**Issue by Baiquette** [roadrunner-server/roadrunner#1267]
### Plugin

JOBS

### I have an idea!

I have an idea, listen to me!!

Hey!
When we start RoadRunner with Kafka not available yet (for eg when it is starting), the RR binary stops immediately with the following error:
```
handle_serve_command: Serve error:
    endure_start:
    endure_serve_internal: Function call error:
    endure_call_serve_fn: got initial serve error from the Vertex jobs.Plugin, stopping execution, error: jobs_plugin_serve:
    new_kafka_consumer: kafka: client has run out of available brokers to talk to: dial tcp: lookup kafka-brokers on 127.0.0.53:53: server misbehaving
```
It will be great to have an automatic retry with options configurable in the `.rr.yaml` file, for eg:
```yaml
connection.retry.attempts: 1 # 0 means forever
connection.retry.timeout: 10 # in seconds
```

Thank you
