### ISSUE TITLE
[🐛 BUG]: PHP ReflectionException on Google\Protobuf\GPBEmpty when using Dependency Injection

### ISSUE THREAD

**Issue by route33** [roadrunner-server/roadrunner#1270]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

The following error occurred after RR upgrade to V2, on V1 works fine.
 
I created also a ticket on protobuf's side https://github.com/protocolbuffers/protobuf/issues/10465, as I don't know exactly who's the culprit here. You may check it for additional screenshots.

```bash
method call was finished with error
rpc error:
 code = Internal desc = sync_worker_exec:
 SoftJobError:
  sync_worker_exec_payload:
 DI\\Definition\\Exception\\InvalidDefinition:
 Entry \"Google\\Protobuf\\GPBEmpty\" cannot be resolved:
 The parameter \"data\" of __construct() has no type defined or guessable. It has a default value, but the default value can't be read through Reflection because it is a PHP internal class.
 Full definition:

Object (
    class = Google\\Protobuf\\GPBEmpty
    lazy = false
    __construct(
        $data = #UNDEFINED#
    )
    ) in vendor/php-di/php-di/src/Definition/Exception/InvalidDefinition.php:19
```
I tried to edit the vendor class, to get rid of PHP's reflection error but no luck.
```php
class GPBEmpty extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Google\Protobuf\GPBEmpty::initOnce();
        parent::__construct($data);
    }

}
```

rr serve -d -c .rr.yaml

```yaml
version: "2.7"
server:
  command: "php worker.php"
  relay: "unix:///tmp/my.sock"
  relay_timeout: 60s
grpc:
  listen: "tcp://0.0.0.0:9001"
  proto:
    - "../../../my/service.proto"
  max_send_msg_size: 50
  max_recv_msg_size: 50
  max_connection_idle: 0s
  max_connection_age: 0s
  max_connection_age_grace: 0s8h
  max_concurrent_streams: 10
  ping_time: 1s
  timeout: 200s
  pool:
    num_workers: 4
    max_jobs: 70000
    allocate_timeout: 3600s
    destroy_timeout: 3600
    debug: true
    supervisor:
      max_worker_memory: 120

http:
  address: 0.0.0.0:8090
  pool:
    num_workers: 1
    debug: true

```

### Version (rr --version)

2.11.1

### Relevant log output

```shell
ERROR   grpc            method call was finished with error {
  "error": "rpc error: code = Internal desc = sync_worker_exec: SoftJobError:
  sync_worker_exec_payload: DI\\Definition\\Exception\\InvalidDefinition: Entry \"Google\\Protobuf\\GPBEmpty\" cannot be resolved: The parameter \"data\" of __construct() has no type defined or guessable. It has a default value, but the default value can't be read through Reflection because it is a PHP internal class.
  Full definition:
  Object (
      class = Google\\Protobuf\\GPBEmpty
      lazy = false
      __construct(
          $data = #UNDEFINED#
      )
      ) in /home/rr/vendor/php-di/php-di/src/Definition/Exception/InvalidDefinition.php:19
  Stack trace:
  #0 /home/rr/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(156): DI\\Definition\\Exception\\InvalidDefinition::create(Object(DI\\Definition\\ObjectDefinition), 'Entry \"Google\\\\P...')
  #1 /home/rr/vendor/php-di/php-di/src/Definition/Resolver/ObjectCreator.php(71): DI\\Definition\\Resolver\\ObjectCreator->createInstance(Object(DI\\Definition\\ObjectDefinition), Array)
  #2 /home/rr/vendor/php-di/php-di/src/Definition/Resolver/ResolverDispatcher.php(71): DI\\Definition\\Resolver\\ObjectCreator->resolve(Object(DI\\Definition\\ObjectDefinition), Array)
  #3 /home/rr/vendor/php-di/php-di/src/Container.php(390): DI\\Definition\\Resolver\\ResolverDispatcher->resolve(Object(DI\\Definition\\ObjectDefinition), Array)
  #4 /home/rr/vendor/php-di/php-di/src/Container.php(199): DI\\Container->resolveDefinition(Object(DI\\Definition\\ObjectDefinition), Array)
  #5 /home/rr/vendor/my/src/Server/Input.php(39): DI\\Container->make('Google\\\\Protobuf...')
  #6 /home/rr/vendor/my/src/Server.php(186): My\\Server\\Input->makeInput(Object(ReflectionMethod), '')
  #7 /home/rr/vendor/my/src/Server.php(102): My\\Server->invoke('my.servi...', 'HealthCheck', Object(My\\Server\\Context), '')
  #8 /home/rr/vendor/my/src/Worker.php(116): My\\Server->serve(Object(My\\RoadRunner\\Worker))
  #9 /home/rr/bin/worker.php(14): My\\Worker->startEventLoop()
  #10 {main}",
  "method": "/my.Service/HealthCheck",
  "start": "2022-08-26T14:38:29.999Z",
  "elapsed": "1.195721896s"
}
```
