### ISSUE TITLE
[💡 FEATURE REQUEST]: Create NATS stream on connect if needed

### ISSUE THREAD

**Issue by pjtuxe** [roadrunner-server/roadrunner#1274]
### Plugin

JOBS

### I have an idea!

Hey Roadrunner Team,

I'm facing a problem connecting consumers to a fresh-new stream. If the stream is not created yet, the consumer won't be able to start as by design NATS Jetstream streams should be made before the first connection.

The current Roadrunner implementation throws this error:

```
handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex jobs.Plugin, stopping execution, error: jobs_plugin_serve:
        new_nats_consumer: stream not found
```

It would be much appreciated if you can create a facility to allow auto-creation of streams if needed (anyway, the process of the stream creation is idempotent, so you can call the creation as much as you want).

Thanks!
