### ISSUE TITLE
[🐛 BUG]: replacing an array config option using environment variables doesn't work.

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#1308]
### Discussed in https://github.com/roadrunner-server/roadrunner/discussions/1307

<div type='discussions-op-text'>

<sup>Originally posted by **lyt8384** September 27, 2022</sup>
Sorry about my poor English~ I am try to using the environment variables to replace a array config options, but isn`t work, like this.
```yaml
redis:
  addrs:
    - "${REDIS_HOST_1}"
    - "${REDIS_HSOT_2}"
```

but it got 
`Error 'rpc_mget:  redis_driver_mget: dial tcp: address ${REDIS_HOST_1}: missing port in address'`</div>
