### ISSUE TITLE
[💡 FEATURE REQUEST]: Kafka Topic Subscription Patterns / Regexes

### ISSUE THREAD

**Issue by joaopbnogueira** [roadrunner-server/roadrunner#1332]
### Plugin

JOBS

### I have an idea!

For setups with many Kafka topics it's very convenient to be able to subscribe to a topic pattern (e.g. `*.topic$` or `^(topic1|topic2)` under the same consumer group instead of having to specify individual configurations for each one with a lot of repeated settings yet necessarily different consumer groups and topic names.

This would allow the same consumer group to subscribe to multiple topics, as per the documentation: 
https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html

Subscription to a regex pattern
https://kafka.apache.org/10/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#subscribe-java.util.regex.Pattern-org.apache.kafka.clients.consumer.ConsumerRebalanceListener-

Hope you consider the feature!

**Comment by rustatian** [comment]
Hey @joaopbnogueira 👋🏻 
Thanks for the FR 👍🏻 

As far as I understand, Kafka doesn't have an API to consume topics by pattern. The drivers implement that feature by periodically checking the list of the available topics and, if they match the pattern - auto-subscribe on them.

**Comment by joaopbnogueira** [comment]
Thanks for considering it @rustatian. Another approach that would also work for me would be the ability to provide a list of topics instead of a single one on the configuration, i.e. supporting something like:

```
  consume:
    - kafka_topics
  pipelines:
    kafka_topics:
      driver: kafka
      config:
        topic:
            - topic1
            - topic2
            - topic3
        group_id: "${SERVICE_NAME}"
        kafka_version: 3.1.0
```

instead of the current
```
  consume:
    - topic1
    - topic2
    - topic3
  pipelines:
    topic1:
      driver: kafka
      config:
        topic: topic1
        group_id: "${SERVICE_NAME}"
        kafka_version: 3.1.0
    topic2:
      driver: kafka
      config:
        topic: topic2
        group_id: "${SERVICE_NAME}"
        kafka_version: 3.1.0
    topic3:
      driver: kafka
      config:
        topic: topic3
        group_id: "${SERVICE_NAME}"
        kafka_version: 3.1.0
```
