### ISSUE TITLE
[💡 FEATURE REQUEST]: Broadcast RR staring to another sevice

### ISSUE THREAD

**Issue by butschster** [roadrunner-server/roadrunner#1340]
### I have an idea!

I have an idea, listen to me!!!

What if RoadRunner will have the ability to send information about running to another server

```yaml
ping:
    address: http://127.0.0.1:8080
    method: POST
    data:
         name: payment-gateway
         foo: bar
```
