### ISSUE TITLE
[💡 FEATURE REQUEST]: Important configuration options for AMQP Driver

### ISSUE THREAD

**Issue by andrey-tech** [roadrunner-server/roadrunner#1351]
### Plugin

JOBS

### I have an idea!

Please add important configuration options for AMQP Driver:
- `durable exchange` for *ExchangeDeclare()* in [amqp091-go](https://github.com/rabbitmq/amqp091-go);
- `auto-deleted exchange` for *ExchangeDeclare()* in [amqp091-go](https://github.com/rabbitmq/amqp091-go);
- `auto-deleted queue` for *QueueDeclare()* in [amqp091-go](https://github.com/rabbitmq/amqp091-go).

```yaml
jobs:
  pipelines:
    example:
      driver: amqp
      config:

        # Durable exchange
        #
        # Default: true
        exchange_durable: true

        # Auto-deleted exchange
        #
        # Default: false
        exchange_auto_deleted: false

        # Auto-deleted queue
        #
        # Default: false
        queue_auto_deleted: false
```

From [amqp091-go](https://github.com/rabbitmq/amqp091-go) documentation:
```txt
Durable and Non-Auto-Deleted exchanges will survive server restarts and remain
declared when there are no remaining bindings.  This is the best lifetime for
long-lived exchange configurations like stable routes and default exchanges.

Non-Durable and Auto-Deleted exchanges will be deleted when there are no
remaining bindings and not restored on server restart.  This lifetime is
useful for temporary topologies that should not pollute the virtual host on
failure or after the consumers have completed.

Non-Durable and Non-Auto-deleted exchanges will remain as long as the server is
running including when there are no remaining bindings.  This is useful for
temporary topologies that may have long delays between bindings.

Durable and Auto-Deleted exchanges will survive server restarts and will be
removed before and after server restarts when there are no remaining bindings.
These exchanges are useful for robust temporary topologies or when you require
binding durable queues to auto-deleted exchanges.
```
