### ISSUE TITLE
[💡 FEATURE REQUEST]: Worker `reset_timeout` setting

### ISSUE THREAD

**Issue by butschster** [roadrunner-server/roadrunner#1352]
### I have an idea!

I have an idea, listen to me!!

By default, RR will kill and reallocate workers if something goes wrong after 60 sec., but in some cases, it needs to be restarted ASAP. It would be great to have the ability to change a default timeout.

```yaml
centrifuge:
    proxy_address: "tcp://127.0.0.1:10001"
    grpc_api_address: "127.0.0.1:10000"
    pool:
        reset_timeout: 10 <===============
        num_workers: 2
```
