### ISSUE TITLE
[📖 DOCS]: Datadog integration documentation and examples

### ISSUE THREAD

**Issue by matthewnessworthy** [roadrunner-server/roadrunner#1359]
### I have an idea!

We use Datadog and are looking at using Roadrunner in combination with Laravel Octane. It would be really amazing if there were some documentation available about how to integrate Roadrunner and Datadog (I saw a Changelog of Open Telemetry, but I am unsure as to how to integrate with that)

**Comment by rustatian** [comment]
Hey @matthewnessworthy 👋🏻 
Yeah, I agree with you. I guess @butschster had an example of configuration, at least.

So, basically, at the moment, PHP and RR should both report to the collector. I don't know if that's possible to configure Octane (since it only supports 15-20% of the RR functionality (no queues, some middleware isn't supported, kv, etc.).

I guess later, we will support the single point of the configuration, but the PHP-OTEL library works independently.

**Comment by rustatian** [comment]
RR itself doesn't limit you in OTEL usage. So, you may use an official opentelemetry docs: https://github.com/open-telemetry/opentelemetry-php

**Comment by butschster** [comment]
Hi @matthewnessworthy 

If you want to send data from OpenTelemetry to datadog you just need to use OpenTelemetry collector  in your application

We use it from docker container
```yaml
#docker-composer.yml
version: "3.6"

services:
  collector:
    image: otel/opentelemetry-collector-contrib
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4318:4318"
```

There is an example of collector configuration, for sending data to zipkin,datadog and newrelic below.

```yaml
#otel-collector-config.yml
receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s

exporters:
  logging:
    loglevel: debug

  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"

  datadog:
    api:
      site: datadoghq.eu
      key: ...

  otlp:
    endpoint: https://otlp.eu01.nr-data.net:443
    headers:
      api-key: ...

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ zipkin, datadog, otlp, logging ]
```

Then you just need to configure your php application to send opentelemetry trace to Otel collector

```dotenv
# OpenTelemetry
OTEL_SERVICE_NAME=php-blog
OTEL_TRACES_EXPORTER=otlp
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_EXPORTER_OTLP_ENDPOINT=http://127.0.0.1:4318 # Collector address
OTEL_PHP_TRACES_PROCESSOR=simple
```

P.S.
And, don't forget, that you may become a sponsor: https://github.com/sponsors/roadrunner-server
