### ISSUE TITLE
[💡 FEATURE REQUEST]: Custom headers in AMQP driver

### ISSUE THREAD

**Issue by ykweb** [roadrunner-server/roadrunner#1388]
### Plugin

JOBS

### I have an idea!

It would be great to be able to specify a queue type other than classic.
And the ability to pass attributes when creating a queue.

When changing the queue manually, I get a plugin error: "jobs_plugin_rmq_init: Exception (406) Reason: "PRECONDITION_FAILED - inequivalent arg 'x-queue-type' for queue 'reindex' in vhost '/': received none but current is the value 'quorum' of type 'longstr'""

**Comment by rustatian** [comment]
Hey @ykweb 👋🏻 
Yeah, an important feature; I'll try to resolve this in the `v2.12.2-beta.x`, early next week. Thanks for the contribution 👍🏻

**Comment by rustatian** [comment]
```yaml
    test-2:
      driver: amqp
      config:
        prefetch: 100
        queue: test-2-queue-headers
        priority: 2
        delete_queue_on_stop: true
        exchange: default
        exchange_type: direct
        routing_key: test-2-queue-headers
        exclusive: false
        durable: true
        multiple_ack: false
        requeue_on_fail: false
        queue_headers:
          x-queue-mode: lazy # <---------
          x-queue-type: quorum # <-------
```

Hey @ykweb 👋🏻 

Tomorrow I'll release a `2.12.2-alpha.1`; you may test a `rabbitmq` headers.
