### ISSUE TITLE
[🐛 BUG]: Extra spaces in logs in debug mode

### ISSUE THREAD

**Issue by s1lver** [roadrunner-server/roadrunner#1408]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

In debug mode, extra spaces appear in the logs, while in production they are not

**development**
```
{"level":"INFO","ts":"2023-01-10T11:09:11.245Z","logger":"grpc        ","msg":"grpc server was started","address":"tcp://0.0.0.0:9001"}
```

**production**
```
{"level":"info","ts":1673348834.3798273,"logger":"grpc","msg":"grpc server was started","address":"tcp://0.0.0.0:9001"}
```

### Version (rr --version)

2.12.1

### How to reproduce the issue?

```yaml
logs:

  mode: development

  level: debug

  encoding: json

  line_ending: "\n"

  output: ./runtime/logs/rr.log

  err_output: ./runtime/logs/rr.log
```
