### ISSUE TITLE
[🐛 BUG]: Custom header is not added to responses

### ISSUE THREAD

**Issue by speller** [roadrunner-server/roadrunner#1429]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I have the following http configuration:

```yaml
http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    allocate_timeout: 10s
    max_jobs: ${RR_MAX_JOBS}
    supervisor:
      exec_ttl: ${RR_JOB_TIMEOUT}s
  headers:
    response:
      X-App-Version: "APP_VERSION"
```

But the `X-App-Version` header is not added to responses:

<img width="594" alt="image" src="https://user-images.githubusercontent.com/1829515/214476202-9d405dbf-8225-4941-a10e-e267e2d86f10.png">

How to fix that?

### Version (rr --version)

2.12.2

### How to reproduce the issue?

```yaml
version: "2.7"

server:
  command: "php -d max_execution_time=${HTTP_TIMEOUT} public/index.php"
  env:
    - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

http:
  address: 0.0.0.0:8080
  middleware: [ "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    allocate_timeout: 10s
    max_jobs: ${RR_MAX_JOBS}
    supervisor:
      exec_ttl: ${RR_JOB_TIMEOUT}s
  headers:
    response:
      X-App-Version: "APP_VERSION"
```
