### ISSUE TITLE
[🐛 BUG]: static request is wrongly passed to PHP

### ISSUE THREAD

**Issue by speller** [roadrunner-server/roadrunner#1441]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I've configured RR to serve static files from the `public` directory. The `index.php` file is in the project root. But requests to static files still executed by PHP instead of being served by the middleware only. In the example, the `favicon.ico` file does not exist and I want to get the 404 error without invoking PHP. 

### Version (rr --version)

2.12.2

### How to reproduce the issue?

```
version: "2.7"

server:
  command: "php index.php"

http:
  address: 0.0.0.0:8080
  middleware: [ "headers", "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
```

### Relevant log output

```shell
2023-02-02T10:59:26.719Z        INFO    http            http log        {"status": 404, "method": "GET", "URI": "/favicon.ico", "remote_address": "172.28.0.1:39434", "read_bytes": 0, "write_bytes": 319800, "start": "2023-02-02T10:59:26.557Z", "elapsed": "162.753304ms"}
{"message":"Allowed exception caught (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException), the kernel will not be rebooted.","context":{"allowed_exceptions":["Symfony\\Component\\HttpKernel\\Exception\\HttpExceptionInterface","Symfony\\Component\\Serializer\\Exception\\ExceptionInterface","Symfony\\Contracts\\HttpClient\\Exception\\ExceptionInterface"]},"level":100,"level_name":"DEBUG","channel":"app","datetime":"2023-02-02T19:59:26.806999+09:00","extra":{}}
```
