### ISSUE TITLE
[🐛 BUG]: RR serve plugin cannot start if the php workers immediately start sending logs to RPC (app-logger plugin)

### ISSUE THREAD

**Issue by roquie** [roadrunner-server/roadrunner#1452]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Since `2.12.0` I am happy to use `app-logger` [plugin](https://github.com/roadrunner-server/roadrunner/releases/tag/v2.12.0). But with this feature, I found unexpected behavior.

It's okay if your application doesn't send logs during the bootload phase. But if the application sends such logs, we have a problem:

- 1: PHP can't send logs over a socket connection because the `rpc plugin` not started yet
- PHP workers can't to allocate because they're trying to send logs to RPC; goto 1;

### Version (rr --version)

`2.12.2`

### How to reproduce the issue?

Steps to reproduce:
1. Create a php worker and send logs to rpc app-logger plugin **right away**
2. `rr serve`

Configuration file:
```yaml
http:
  address: 0.0.0.0:8080
  middleware:
  - gzip
  - static
  pool:
    num_workers: 4
    supervisor:
      max_worker_memory: 100
  static:
    dir: /app/public
    forbid:
    - .php
    - .htaccess
rpc:
  listen: tcp://127.0.0.1:6001
server:
  command: php /app/app.php
  relay: pipes
temporal: # temporal not required for reproduce, this is a just my copy-pasted config
  activities:
    num_workers: 12
  address: temporal-frontend:7233
version: "2.7"
```

### Relevant log output

```shell
2023-02-07T13:56:23.024Z        INFO    temporal        connected to temporal server    {"address": "temporal-frontend:7233"}
2023-02-07T13:56:23.309Z        INFO    server          [Spiral\Goridge\Exception\RelayException]
Unable to establish connection tcp://127.0.0.1:6001
in /app/vendor/spiral/goridge/src/SocketRelay.php:281

Previous: [Spiral\Goridge\Exception\RelayException]
Connection refused
in /app/vendor/spiral/goridge/src/SocketRelay.php:278

2023-02-07T13:56:23.309Z        INFO    server          [Spiral\Exceptions\Exception\FatalException]
socket_connect(): unable to connect [111]: Connection refused
in /app/vendor/spiral/goridge/src/SocketRelay.php:269

handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex roadrunner_temporal.Plugin, stopping execution, error: temporal_plugin_serve: WorkerAllocate:
        static_pool_allocate_workers: EOF
```
