### ISSUE TITLE
[💡 FEATURE REQUEST]: Please add to job-header information about `queue` from which task was readed before processing. 

### ISSUE THREAD

**Issue by iborysenko** [roadrunner-server/roadrunner#1462]
### Plugin

JOBS

### I have an idea!

In some cases I would like to have multiple implementations for processing one task. I can split it by routing-key to different pipelines, but I never know from which queue task was readed.

**Comment by rustatian** [comment]
Hey @iborysenko 👋🏻 

A pipeline and a queue are already presented in the information RR send to the PHP worker.

**Comment by iborysenko** [comment]
Hey @rustatian  

Yes, but this is information about pipeline which used to push task to the broker.
But not about pipeline which used to read this task from the queue, is not it ?

**Comment by iborysenko** [comment]
header `pipeline` always receiving *as is* from the broker message. 
And it will be always from the `dispatching pipeline`, 
But sometimes we need information about `consuming pipeline`

**Comment by rustatian** [comment]
I don't think that I understand you correctly.

What is `which task was read before processing`? 
RR doesn't have any connection between the `push` and `consume` except headers. You may put any information in it via the and then receive it in the PHP worker.

**Comment by iborysenko** [comment]
@rustatian  

According to my well-known example 

```yaml 

jobs:
  consume: 
    - 'consume_pipeline_first' 
    - 'consume_pipeline_second' 
  pipelines:
    push_pipeline: # this pipeline using only for producing tasks to broker 
      driver: amqp
      config:
        exchange: default
        routing_key:  product.created # same routing key
        exchange_type: direct
    consume_pipeline_first: #this pipeline using only for consuming incoming tasks
      driver: amqp
      config:
        exchange: default
        routing_key: product.created # same routing key
        exchange_type: direct
        queue: product.created.action_first
        
    consume_pipeline_second: # this pipeline using only for consuming incoming tasks
      driver: amqp
      config:
        exchange: default
        routing_key: product.created # same routing key
        exchange_type: direct
        queue: product.created.action_second
```

Then I will dispatch task 
```php
   $queue = $this->jobs->connect('push_pipeline');
   $queue->dispatch(new PrepatedTask('product.created ', ['foo' => 'bar']));
```

My task will be delivered to both queues:
 - `product.created.action_first`
 - `product.created.action_first`
 
 
 But When I start consuming pipeline `consume_pipeline_first` or `consume_pipeline_second`
 Received task from RR  **will contain in pipeline header** value `push_pipeline`
 But nothing about `consume_pipeline_first` or `consume_pipeline_second`
