### ISSUE TITLE
[🐛 BUG]: Jobs amqp redial for non existed queue 

### ISSUE THREAD

**Issue by iborysenko** [roadrunner-server/roadrunner#1472]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

I have an pipeline which I'm using only for pushing tasks to the exchange
```yaml 
jobs:
  consume: [] # not consuming any queues
  pipelines:
    push_pipeline:
      driver: amqp
      config:
        exchange: default
        routing_key:  product.created 
        exchange_type: direct
```
Note that in this case `default` queue is not exists and not consumed 
In case when RabbitMQ server rebooted, RR trying to redial connection, and trying to reconnect to this `default` queue, and then fall.

### Version (rr --version)

2.12.2

### How to reproduce the issue?

```yaml 
jobs:
  consume: [] # not consuming any queues
  pipelines:
    push_pipeline:
      driver: amqp
      config:
        exchange: default
        routing_key:  product.created 
        exchange_type: direct
```
Push task 
```php 
$queue = $this->jobs->connect('push_pipeline');
 $queue->dispatch(new PrepatedTask('product.created ', ['foo' => 'bar']));
```
Rebood Rabbitmq ant try to push new one task 
```php 
$queue = $this->jobs->connect('push_pipeline');
 $queue->dispatch(new PrepatedTask('product.created ', ['foo' => 'bar']));
```

### Relevant log output

```shell
rabbitmq dial was succeed. trying to redeclare queues and subscribers
backoff operation failed","error":"rabbitmq_redial: Exception (404) Reason: \"NOT_FOUND - no queue 'default' in vhost 'dev'

{"level":"error","ts":1676970098.943889,"logger":"jobs","msg":"job push error","ID":"ec09b299-1fc7-408f-9f65-e20cd0e66295","pipeline":"product.created","driver":"amqp","start":1676970038.9437327,"elapsed":60.000149781,"error":"rabbitmq_push: Timeout:\n\trabbitmq_handle_item: context deadline exceeded"}
```
