### ISSUE TITLE
[🧹 CHORE]: Services documentation misleading

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#1473]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

https://roadrunner.dev/docs/plugins-service/2.x/en

Here in example option `exec_timeout` is int. But rr server does not start if `exec_timeout:0`.

Also warning in IDE
![image](https://user-images.githubusercontent.com/3841197/220400260-69f30422-f3ce-408a-8cbd-851f0b45c92b.png)

I think correct config must me 
```yaml
version: "2.7"

service:
  some_service_1:
    command: "php tests/plugins/service/test_files/loop.php"
    process_num: 10
    exec_timeout: 0s
    remain_after_exit: true
    env:  
       - foo: "BAR"
    restart_sec: 1

  some_service_2:
    command: "tests/plugins/service/test_files/test_binary"
    process_num: 1
    remain_after_exit: true
    restart_sec: 1s
    env:
       - foo: "BAR"
    exec_timeout: 0s
```
