### ISSUE TITLE
[🧹 CHORE]: Wrong default value for `exchange_durable` for jobs plugin in documentation and examples

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1478]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

Now i see [in example](https://github.com/roadrunner-server/roadrunner/blob/master/.rr.yaml#L1305) and [docs ](https://roadrunner.dev/docs/plugins-jobs/2.x/en#amqp-driver)exchange_durable default true, but it`s not.

`rr version 2.12.3 (build time: 2023-02-16T13:08:41+0000, go1.20), OS: linux, arch: amd6`

```
# Durable exchange (rabbitmq option: https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges)
#
# Default: true
exchange_durable: false
```

This config gives me not durable exchange:
```
jobs:
    pipelines:
        test:
            driver: amqp
            config:
                queue: test-1
                exchange: test
```

![image](https://user-images.githubusercontent.com/10486803/221493230-c2dce4c8-968d-45e7-af4c-bbe3be9bdd34.png)

If add exchange_durable: true, when got the error:

```
handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex jobs.Plugin, stopping execution, error: jobs_plugin_serve:
        new_amqp_consumer:
        jobs_plugin_rmq_init: Exception (406) Reason: "PRECONDITION_FAILED - inequivalent arg 'durable' for exchange 'test' in vhost '/': received 'true' but current is 'false'"
```
