### ISSUE TITLE
[🐛 BUG]: RR does not write logs to a file

### ISSUE THREAD

**Issue by nikolaev-dm** [roadrunner-server/roadrunner#1483]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

RR does not write logs to a file. I don't know for sure if it's a bug or my crooked hands

### Version (rr --version)

2.12.3

### How to reproduce the issue?

`.rr.yaml` 

````yaml
version: "2.7"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php worker.php"

temporal:
  address: "temporal:7233"
  activities:
    num_workers: 4

logs:
  level: debug
  mode: development
  file_logger_options:
    log_output: "log.log"
````

`worker.php`

````php
<?php

/**
 * This file is part of Temporal package.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

declare(strict_types=1);

use Temporal\WorkflowUtils\DeclarationLocator;
use Temporal\WorkerFactory;
use Temporal\Workflow\FileProcessing;

ini_set('display_errors', 'stderr');
include "vendor/autoload.php";

// finds all available workflows, activity types and commands in a given directory
$declarations = DeclarationLocator::create(__DIR__ . '/src/');

// factory initiates and runs task queue specific activity and workflow workers
$factory = WorkerFactory::create();

// Worker that listens on a task queue and hosts both workflow and activity implementations.
$worker = $factory->newWorker();

foreach ($declarations->getWorkflowTypes() as $workflowType) {
    // Workflows are stateful. So you need a type to create instances.
    $worker->registerWorkflowTypes($workflowType);
}

foreach ($declarations->getActivityTypes() as $activityType) {
    // Activities are stateless and thread safe. So a shared instance is used.
    $worker->registerActivity($activityType);
}

// We can use task queue for more complex task routing, for example our FileProcessing
// activity will receive unique, host specific, TaskQueue which can be used to process
// files locally.
$hostTaskQueue = gethostname();

$factory->newWorker($hostTaskQueue)
    ->registerActivityImplementations(new FileProcessing\StoreActivity($hostTaskQueue));

// start primary loop
$factory->run();
````

I'm starting the server
`docker-compose run --rm php-grpc /app/rr serve --config /app/.rr.yaml`
stdout:
`[INFO] RoadRunner server started; version: 2.12.3, buildtime: 2023-02-16T13:08:41+0000`
A log file is being created but it is empty

If I remove the option
````yaml
  file_logger_options:
    log_output: "log.log"
````
RR write logs to stdout
