### ISSUE TITLE
[🐛 BUG]: Queue name with dot is not working in Jobs plugin configured with YAML format

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1529]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

### Version (rr --version)

rr version 2.12.3 (build time: 2023-02-16T13:08:41+0000, go1.20), OS: linux, arch: amd64

### How to reproduce the issue?

Use this config for queue with dot in the name

```
version: '2.7'
jobs:
    consume:
        - test.dot
    pipelines:
        test.dot:
            driver: amqp
            config:
                queue: test.dot
```

After RR starts i got no queue with name `test.dot` but got warning, see below.

I found some similar problems and solvings in Spring Boot:
```
foo:
  "[bar.com]":
    a: b
  "[baz.com]":
    a: c
```

Maybe we need got an error for wrong YAML-config or support this dot-opportunity?

### Relevant log output

```shell
2023-04-07T13:25:58.461Z        WARN    jobs            can't find driver name for the pipeline, please, check that the 'driver' keyword for the pipelines specified correctly, JOBS 
plugin will try to run the next pipeline
2023-04-07T13:25:58.462Z        DEBUG   rpc             plugin was started      {"address": "tcp://127.0.0.1:6001", "list of the plugins with RPC methods:": ["informer", "resetter",
 "app", "jobs"]}
```

**Comment by rustatian** [comment]
Hey @embargo2710 👋🏻 

Unfortunately, this is not an RR problem, since `.` is a YAML key separator, you can't use this symbol in the YAML config. 
But RR supports both YAML and JSON, you can try to convert your config to JSON format.

**Comment by rustatian** [comment]
Another way is to declare the pipeline dynamically using the `Declare` RPC call.

**Comment by Kaspiman** [comment]
What about warning?

`can't find driver name for the pipeline, please, check that the 'driver' keyword for the pipelines specified correctly, JOBS 
plugin will try to run the next pipeline` does not countain useful information about driver or queue

**Comment by rustatian** [comment]
> What about warning?
> 
> `can't find driver name for the pipeline, please, check that the 'driver' keyword for the pipelines specified correctly, JOBS plugin will try to run the next pipeline` does not countain does not contain useful information about driver or queue

This is the correct YAML. Sure, we can search the whole YAML for the dots... But this could be comments that contain dots... So this is a limitation of the YAML, please try the JSON.

e.g

```json
{
  "version": "2.7",
  "jobs": {
    "consume": [
      "test.dot"
    ],
    "pipelines": {
      "test.dot": {
        "driver": "amqp",
        "config": {
          "queue": "test.dot"
        }
      }
    }
  }
}
```

EDIT: I'm not sure about the JSON btw

**Comment by Kaspiman** [comment]
I mean that exception (warning) should contain information about queue or driver.

For example:

can't find driver name **"name"** for the pipeline **"name"**, please, check that the 'driver' keyword for the pipelines specified correctly, JOBS plugin will try to run the next pipeline

**Comment by rustatian** [comment]
Your YAML with dot parsed as something like:

```yaml
version: '2.7'
jobs:
    consume:
        - test:
           - dot:
    pipelines:
        test:
          dot:
             driver: amqp # <-- this line becomes nested
             config:
                queue: test.dot
```

From RR's POV, this is the pipeline with the name `dot` but no configuration. And RR points to the problem: can't find driver name.
