### ISSUE TITLE
[🐛 BUG]:  http: superfluous response.WriteHeader

### ISSUE THREAD

**Issue by mfadul24** [roadrunner-server/roadrunner#1544]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

The ready and status endpoint are flooding the logs on the Kubernetes Cluster with entries like:

```http: superfluous response.WriteHeader call from github.com/roadrunner-server/status/v4.(*Health).ServeHTTP (health.go:72)```

```http: superfluous response.WriteHeader call from github.com/roadrunner-server/status/v4.(*Health).ServeHTTP (ready.go:77)```

### Version (rr --version)

2023.1.0

### How to reproduce the issue?

Activate status endopoint:

```
status:
  address: '0.0.0.0:2114'
```

and use it on kubernetes:
```
          livenessProbe:
            httpGet:
              path: /health?plugin=http
              port: php-status
            initialDelaySeconds: 10
            periodSeconds: 5
```

### Relevant log output

```shell
: superfluous response.WriteHeader call from github.com/roadrunner-server/status/v4.(*Health).ServeHTTP (health.go:72)

```http: superfluous response.WriteHeader call from github.com/roadrunner-server/status/v4.(*Health).ServeHTTP (ready.go:77)```
```

**Comment by joaopbnogueira** [comment]
Just a heads up that we're facing the same issue after the update (today) to 2023.01 also in K8s

```
  livenessProbe:
    httpGet:
      path: /health?plugin=http
      port: 2114
```
