### ISSUE TITLE
[🐛 BUG]: Failed Sqs plugin after updating to 2023.1.1

### ISSUE THREAD

**Issue by sergey-telpuk** [roadrunner-server/roadrunner#1550]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

```bash
handle_serve_command: Function call error:
	got initial serve error from the Vertex *jobs.Plugin, stopping execution, error: jobs_plugin_serve:
	new_sqs_consumer: operation error SQS: GetQueueUrl, failed to sign request: failed to retrieve credentials: failed to refresh cached credentials, static credentials are empty
```

### Version (rr --version)

v2023.1.1

### How to reproduce the issue?

```yaml

# queue and jobs
#
# In this section, the jobs themselves are configured
#
jobs:
  pool:
    num_workers: 2
    allocate_timeout: 60s
    destroy_timeout: 60s
  consume: [ "events" ]   # List of RoadRunner queues that can be processed by
  # the consumer specified in the "server" section.
  pipelines:
    events:
      driver: sqs
      config:
        queue: xxx-dev
        skip_queue_declaration: true
```
