### ISSUE TITLE
[💡 FEATURE REQUEST]: Add the ability to configure the user and group per Service

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1570]
### Plugin

Service

### I have an idea!

Server plugin already has user/group ability, let's add it to Service!

```
version: "3"

server:
    command: "php public/index.php"
    relay: pipes
    env:
        -   APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
    user: www-data
    group: www-data

service:
    schedule:run:
        command: "bin/console schedule:run"
        process_num: 1
        exec_timeout: 0s
        remain_after_exit: true
        service_name_in_log: false
        restart_sec: 60
        # user: www-data
        # group: www-data
```
