### ISSUE TITLE
[💡 FEATURE REQUEST]: Make a universal configuration for running commands for all plugins

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1584]
### Plugin

Server

### I have an idea!

Feature is a very similar to this https://github.com/roadrunner-server/roadrunner/issues/1570

`on_init` contained in server section but doesn't inherit user/group parameters. I want to specify these parameters explicitly.

```
server:
    command: "php public/index.php"
    user: www-data
    group: www-data
    on_init:
        command: "bin/console command:whoami" # echo whoami = root
        # user: www-data
        # group: www-data
```

In general, a more thorough improvement of the commands can be suggested. Now "command" is the simple path to the file, but it's worth turning this path into a more universal structure.

Like this:
```
server:
    command:
        path: "php public/index.php"
        user: "www-data"
        group: "www-data"
        another_param: "another_value"
    on_init:
        command:
            path: "bin/console command:whoami" # echo root
            another_param: "another_value"

service:
    schedule:run:
        command:
            path: "bin/console schedule:run"
            user: "www-data"
            group: "www-data"
            another_param: "another_value"
        process_num: 1
        exec_timeout: 0s
        remain_after_exit: true
        service_name_in_log: false
        restart_sec: 60

```

Now it is clear that there can be commands in different plugins and it is worth making a general configuration method. Thanks to this, it is not necessary to add a user and group setting to each plugin.

**Comment by rustatian** [comment]
Hey @Kaspiman 👋🏻 
This is not possible at the moment, as it would break config `v3`. Counfig should be stable between major releases. But since I like the idea, I'll put it in the `Discuss` column for `2024.1.0`. 
Thanks 👍🏻

**Comment by Kaspiman** [comment]
Hi! Maybe for now we should add user/group for on_init only?

**Comment by rustatian** [comment]
I don't think, that we need to add the `user` and `group` per every pool. All pools configuration (user and group) is located under the `server` plugin. I don't think, that we should duplicate these options all around the every command.

**Comment by rustatian** [comment]
Thanks @Kaspiman, I thought of this suggestion:
```yaml
        command:
            path: "bin/console schedule:run"
            user: "www-data"
            group: "www-data"
            another_param: "another_value"
```
Command nowaday is quite universal. I don't think that splitting command itself from it's args simplifies the use of the command. It'll also break all configs, plus it would be harder to just copy-paste the command into the RR command field.
