### ISSUE TITLE
[💡 FEATURE REQUEST]: Add the ability to configure the user and group for on_init and after_init phases

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1585]
### Plugin

Server

### I have an idea!

Feature is a very similar to this https://github.com/roadrunner-server/roadrunner/issues/1570

`on_init` contained in server section but doesn't inherit user/group parameters. I want to specify these parameters explicitly.

```
server:
    command: "php public/index.php"
    user: www-data
    group: www-data
    on_init:
        command: "bin/console command:whoami" # echo whoami = root
        # user: www-data
        # group: www-data
```

This is not a duplicate of [this issue](https://github.com/roadrunner-server/roadrunner/issues/1584). This is not intended to break backwards compatibility.
