### ISSUE TITLE
[🧹 CHORE]: Improve validation schema for .rr.yml

### ISSUE THREAD

**Issue by s1lver** [roadrunner-server/roadrunner#1586]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

**RR: 2023.1.4**
 
I would like to use variables, but in some places the inspection does not work correctly.

e.g

**HTTP section**

```yml
http:
  # Host and port to listen on (eg.: `127.0.0.1:8080`).
  #
  # This option is required.
  address: 0.0.0.0:${HTTP_PORT:-8080}
```
message
> Schema validation: String violates the pattern: '^([0-9a-zA-Z_.-]+|):[0-9]{1,5}$'

**RPC section**

```yml
rpc:
  # TCP address:port for listening.
  #
  # Default: "tcp://127.0.0.1:6001"
  listen: tcp://0.0.0.0:${RPC_PORT:-6001}
```
message
> Schema validation: String violates the pattern: '^tcp:\/\/[0-9a-zA-Z_.-]+:[0-9]{1,5}$'

**gRPC section**

```yml
grpc:
  # GRPC address to listen
  #
  # This option is required
  listen: "tcp://0.0.0.0:${GRPC_PORT:-9001}"
```
message
> Schema validation: String violates the pattern: '^(tcp://[0-9a-zA-Z_.-]+|):[0-9]{1,5}$'
