### ISSUE TITLE
[🐛 BUG]: Static middleware causes ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by tux-rampage** [roadrunner-server/roadrunner#1593]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I configured an application as follows:

```yaml
version: "2.7"

server:
  command: "php /app/backend/roadrunner.php"

logs:
  mode: development
  encoding: console
  level: info

rpc:
  listen: tcp://127.0.0.1:6001

http:
  address: 0.0.0.0:3000
  access_logs: true
  raw_body: false
  pool:
    debug: true

  middleware:
    - static
    - sendfile
    - headers

  uploads:
    dir: /var/uploads
    forbid:
      - ".php"
      - ".exe"
      - ".bat"
      - ".sh"
  headers:
    response:
      X-Powered-By: "roadrunner/php"

  static:
    dir: /app/public/dist/de
    calculate_etag: false
    response:
      X-RoadRunner-Source: Static
```

For some resources that will be served by the static middleware (identified by the header `X-RoadRunner-Source` from the config above), the browser rejects the resource with `ERR_CONTENT_LENGTH_MISMATCH` (webkit) or `NS_ERROR_NET_PARTIAL_TRANSFER` (firefox).

![grafik](https://github.com/roadrunner-server/roadrunner/assets/558326/0d6889f3-bfd0-4926-a8d3-dd9f25a51cdb)

This does not happen for all files, some are served without any problems, while others are broken. The only difference that i can currently spot is the file size. It seems to happen when a file exceeds 16k. Could this be a buffer problem?

### Version (rr --version)

- `rr version 2023.1.4 (build time: 2023-05-25T11:10:19+0000, go1.20.4), OS: linux, arch: amd64`
- `rr version 2.12.2 (build time: 2023-01-12T12:07:45+0000, go1.19.5), OS: linux, arch: amd64`

### How to reproduce the issue?

See yaml in the description
