### ISSUE TITLE
[💡 FEATURE REQUEST]: Set spiral job name in queue config

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#1639]
### Plugin

JOBS

### I have an idea!

I have a Kafka topic in which a non-roadrunner service (A) writes a messages. This message does not have a `rr_job` header. When another service (B) running with roadrunner consumes messages from the topic, I get an error in the spiral framework.

```
Spiral\\Core\\Exception\\Container\\NotFoundException: Can't resolve `DeducedByRr`: undefined class or binding `DeducedByRr`.\nContainer trace list:\n- action: 'autowire'\n  alias: 'DeducedByRr'\n  context: null
```

servise B rr.yaml
```yaml
jobs:
  pool:
    command: "php app.php"
    num_workers: 1
  consume:
    - kafka_queue
  pipelines:
    kafka_queue:
      driver: kafka
      config:
        consumer_options:
          consumer_offset: { type: AtEnd }
          topics:
            - "topic_1"
        group_options:
          group_id: "comsumer_1"
```

It will be great to have a possibility to set job name in pipeline config. Something like...

```yaml
  pipelines:
    kafka_queue:
      driver: kafka
      config:
        consumer_options:
          consumer_offset: { type: AtEnd }
          topics:
            - "topic_1"
          job_name: 'rr_job_name' ## example
        group_options:
          group_id: "comsume_1"
```

I think this option will be useful not only for Kafka driver.
