### ISSUE TITLE
[🧹 CHORE]: Docs add note about spaces in headers.

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#1655]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

I faced with problem that `allowed_origin` does not work correctly if there is a space in the string.

```yaml
http:
  middleware: [ "headers" ]
  headers:
    cors:
      debug: false
      allowed_origin: "http://localhost:3000, https://some-domain.dev"
      allowed_headers: "Accept, Accept-Language, Authorization, Content-Type"
      allowed_methods: "GET, POST, PUT, PATCH, DELETE"
      exposed_headers: "Cache-Control, Content-Language, Content-Type"
      max_age: 600
```

Can you please add a note to docs about allowing spaces in `allowed_*` strings?
