### ISSUE TITLE
[💡 FEATURE REQUEST]: Multiple pool support

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1679]
### Plugin

JOBS

### I have an idea!

We in the company actively use JOBS plugin and process a lot of tasks.

Our monolithic application has very different queue handlers with:
* a very long locks and small amount of tasks
* a very short duration and huge amount of tasks
* a regular and predictable number of tasks
* an unpredictable task spikes
* memory leaks

In the current JOBS implementation, all tasks added into one queue and processed by one pool of workers. Different queue handlers can greatly interfere with others. Problem handlers can take too many workers, requeue tasks too often, and take too long to process. 

As a result, the JOBS-cluster performance is unstable and low.

I would like to be able to configure individual pools and assign them individual settings:
* the most important queues will always be processed in a separate pools
* long tasks will run separately from fast ones
* handlers with memory leaks will be restarted more often then non-leaked
* other problematic and experimental queues will be processed regardless of stable

The new feature proposes:
* configuring many pools
* start/destroy pools in parallel
* restart certain pool in case of network error
* collect metrics from each pool separately (maybe add tag with pool name)
* manage each pool via console commands

Here is an example config for solving these problems:
```yaml
jobs:
    pools:
        predictable_pool:
            pool:
                num_workers: 80
                max_jobs: 10000
            consume:
                - predictable_queue_1
                - predictable_queue_2
            pipelines:
                predictable_queue_1:
                    driver: amqp
                    config:
                        queue: predictable_queue_1
                        prefetch: 40
                        # ...
                predictable-queue-2:
                    driver: amqp
                    config:
                        queue: predictable_queue_2
                        prefetch: 40
                        # ...
        slow_pool:
            pool:
                num_workers: 25
                max_jobs: 100 # restart more often
            consume:
                - leaked_queue_1
            pipelines:
                # ...
```

The result can be a mechanism for managing many pools in a each plugin. This mechanism can be reused in the future plugins.

Comrades, what do you think of this?

**Comment by rustatian** [comment]
Hey @Kaspiman 👋🏻 Thanks for the great idea 👍🏻
I'll plant it (initially) for the 2024.0 milestone (2023.3 is full now).

**Comment by riordorian** [comment]
when is the implementation of this feature planned?

**Comment by rustatian** [comment]
@riordorian Not planned atm.

**Comment by rustatian** [comment]
Or I'll try to implement this during this weekend. Let's see 😃

**Comment by rustatian** [comment]
However, implementation would depend on discussion 😄, as always.
I'm not sure about `pools`, because we'd have `pool` + `pools` which would confuse the users. I'm thinking about allowing to add a pool per pipeline inside the pipeline, like:
```yaml
# rest of the options
pipelines:
    foo:
        driver: kafka
        pool: 
            # here are regular pool options
        config: # config
```
The disadvantage of this approach is that you won't be able to combine pipelines per pool.
Another option is to deprecate `pool` and allow only `pools` in future versions. Without breaking changes for sure. In future versions, `pool` might be the same as `pools` but with 1 pool inside.

I'm proposing the following configuration for the `pools`:
```yaml
# rest of the options
pools:
    pool1:
        # regular pool options
    pool2:
        # regular pool options
pipelines:
    foo:
        driver: kafka
        pool: pool1
        config: # config
```

**Comment by rustatian** [comment]
Scheduled for v2025.2 💯

**Comment by Kaspiman** [comment]
Wooo hoooo!

**Comment by rustatian** [comment]
Full example configuration with a different kind of pools.
```yaml
version: "3"

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php php_test_files/jobs/jobs_ok.php"
  relay: "pipes"

kafka:
  brokers: ["127.0.0.1:9092"]

logs:
  level: debug
  encoding: console
  mode: development

jobs:
  # num logical cores by default
  num_pollers: 12
  # 1mi by default
  pipeline_size: 100000
  # worker pool configuration
  pools:
    default:
      num_workers: 10
      allocate_timeout: 60s
      destroy_timeout: 60s
    high_priority:
      num_workers: 5
      allocate_timeout: 30s
      destroy_timeout: 30s
    low_priority:
      num_workers: 10
      allocate_timeout: 60s
      destroy_timeout: 60s

  # list of broker pipelines associated with endpoints
  pipelines:
    test-1-memory:
      driver: memory
      pool: default
      config:
        priority: 10
        prefetch: 10000

    test-2-memory:
      driver: memory
      pool: high_priority
      config:
        priority: 1
        prefetch: 10000

    test-3-memory:
      driver: memory
      pool: low_priority
      config:
        priority: 2
        prefetch: 10000

  consume: ["test-1-memory", "test-2-memory", "test-3-memory"]
```

1. Pool and Pools can't be used together. By default, if no `pool` or `pools` options are defined, RR will preserve a non BC behavior - init a pool.
2. If both defined - it'll result in a startup error with an error message that both types of pools can't be used.
3. No changes required from the PHP client, since RR can deduce pool (if pools option was used) based on the pipeline name.

I'll try to finish and test this feature this weekend and release 2025.2 with that feature next week.
