### ISSUE TITLE
[🐛 BUG]: Failed logging by file_logger_options hide permission error

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#1708]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Maybe bug, i'm not sure

### Version (rr --version)

rr version 2023.2.0 (build time: 2023-07-06T19:02:11+0000, go1.20.5), OS: linux, arch: amd64

### How to reproduce the issue?

Let's say we have application in Docker container with volume for dev purpose. Log file permissions can be changed due to volume synchronization: uid:guid inside and outside has different values.

`docker-compose` fragment:

```
services:
    php:
        volumes:
            - ./:/app
```

RR logs fragment:

```
logs:
    mode: raw
    level: debug
    output: stderr
    file_logger_options:
        log_output: rr.log
```

The file `rr.log` will be created, but the owner will be changed almost immediately. Nothing will be written to the file, nor will it be written to the output. Silence.

Previous [logging settings](https://github.com/roadrunner-server/logger/blob/master/config.go#L227) are ignored if `file_logger_options` are specified.

Maybe there should be fallback to stdout or mixed logging with the previously specified parameters (output, level, mode): `zapcore.NewMultiWriteSyncer(zapcore.AddSync(os.Stdout), w)`
