### ISSUE TITLE
[💡 FEATURE REQUEST]: Jobs plugin pipelines check not works for pipelines without queues

### ISSUE THREAD

**Issue by iborysenko** [roadrunner-server/roadrunner#1723]
### Plugin

JOBS

### I have an idea!

Hi, @rustatian 
According to documentation https://roadrunner.dev/docs/lab-health/current#jobs-plugin-pipelines-check
In my project, I have two types of pipelines (push only, and process-only) 

for example:

```yaml
status:
  address: 0.0.0.0:8081
jobs:
  consume: 
     - process_pipeline 
  pipelines:
    push_pipeline: # only push pipeline
      driver: amqp
      config:
        exchange: default
        routing_key:  product.created 
        exchange_type: direct
        
     process_pipeline: # only process pipeline
      driver: amqp
      config:
        exchange: default
        routing_key:  something.happened.outside 
        exchange_type: direct
        queue:  service-name.processing.something.happened.outside 
        
 ```
 
 But when I'm trying to execute 
 ```bash 
 curl localhost:8081/jobs
 jobs plugin not found
 ```
 and log 
 ```json 
 {"level":"error","ts":1694590936456822482,"logger":"status","msg":"jobs state","error":"jobs_plugin_drivers_state: empty queue name, add queue to the AMQP configuration"}
 ```
 
 So is it possible to return pipeline statuses only from the `jobs.consume` section?

**Comment by rustatian** [comment]
Hey @iborysenko 👋🏻 
What is your RR version?

**Comment by iborysenko** [comment]
@rustatian 
```bash
 rr version 2023.2.2 (build time: 2023-08-10T16:38:29+0000, go1.21.0), OS: linux, arch: amd64
```

**Comment by iborysenko** [comment]
If I drop all `pipelines without queue-names` everything is ok, 
But at the same time my `jobs.consume` array only consists of `correct-pipelines`

**Comment by rustatian** [comment]
@iborysenko Thanks 👍🏻 
So the problem is that without a queue, you can't check the health of the pipeline. I think we can skip such a pipeline and check the health of the connection instead.
I'll fix that, thanks for the FR ⚡

**Comment by rustatian** [comment]
@iborysenko Note that in `2023.3` a new feature would be available - custom `routing_key` when pushing the JOB. So instead of creating the new pipeline (push-only pipeline), you can avoid this and push jobs with the custom `routing key`. To any existing pipeline.
More here: https://github.com/roadrunner-php/jobs/pull/58

**Comment by iborysenko** [comment]
Hi @rustatian 
I tried to reproduce it again in 
```
rr version 2023.3.0 (build time: 2023-10-05T23:30:26+0000, go1.21.2), OS: linux, arch: amd64
```

Looks like nothing changed in these case 
After  shutting down Rabbitmq , 

```
curl localhost:8081/jobs              
curl: (52) Empty reply from server
``` 
Or maybe this is expected behavior?
Thanks

**Comment by rustatian** [comment]
Hey @iborysenko 👋🏻 
Is there anything in the DEBUG logs?

**Comment by rustatian** [comment]
![image](https://github.com/roadrunner-server/roadrunner/assets/8040338/862a6373-d389-4f25-a649-f7f9c7cacef0)

**Comment by rustatian** [comment]
@iborysenko Double tested this case, result is on the screenshot. I guess you don't have RR on localhost. If it is a container, might be you made a mistake in the host:port mapping between the host and container network.

**Comment by iborysenko** [comment]
@rustatian 

```yaml
---
version: "3"
server:
  command: php public/index.php --env=prod
  env:
    APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
logs:
  mode: production
  encoding: json
  channels:
    http:
      level: info
    server:
      level: info
      mode: raw
rpc:
  listen: tcp://0.0.0.0:6001
status:
  address: 0.0.0.0:8081
metrics:
  address: 0.0.0.0:2112
amqp:
  addr: amqp://${MESSAGE_BUS_USERNAME}:${MESSAGE_BUS_PASSWORD}@${MESSAGE_BUS_HOST}:${MESSAGE_BUS_PORT}/${MESSAGE_BUS_VHOST}
jobs:
  num_pollers: 12
  pipeline_size: 100000
  pool:
    num_workers: 2
    max_jobs: 500
    supervisor:
      ttl: 18000s
  pipelines:
    produce_delivery_event_kitchen-created:
      driver: amqp
      config:
        exchange: internal
        routing_key: delivery.event.kitchen-created
        exchange_type: direct
        exchange_durable: true
        redial_timeout: 600
    produce_delivery_event_kitchen-activity-updated:
      driver: amqp
      config:
        exchange: internal
        routing_key: delivery.event.kitchen-activity-updated
        exchange_type: direct
        exchange_durable: true
        redial_timeout: 600
    produce_delivery_event_kitchen-opening-time-updated:
      driver: amqp
      config:
        exchange: internal
        routing_key: delivery.event.kitchen-opening-time-updated
        exchange_type: direct
        exchange_durable: true
        redial_timeout: 600
    produce_delivery_event_status_updated:
      driver: amqp
      config:
        exchange: internal
        routing_key: delivery.event.status.updated
        exchange_type: direct
        exchange_durable: true
        redial_timeout: 600
    produce_command_logging_add-log:
      driver: amqp
      config:
        exchange: internal
        routing_key: command.logging.add-log
        exchange_type: direct
        exchange_durable: true
        redial_timeout: 600
    process_delivery_command_wolt-drive_webhook:
      driver: amqp
      config:
        queue: delivery.processing.delivery.command.wolt-drive.webhook
        exchange: internal
        routing_key: delivery.command.wolt-drive.webhook
        exchange_type: direct
        exchange_durable: true
        durable: true
        consume_all: true
        redial_timeout: 600
    process_delivery_event_kitchen-created:
      driver: amqp
      config:
        queue: delivery.processing.delivery.event.kitchen-created
        exchange: internal
        routing_key: delivery.event.kitchen-created
        exchange_type: direct
        exchange_durable: true
        durable: true
        consume_all: true
        redial_timeout: 600
    process_oms_event_order-courier-assigned:
      driver: amqp
      config:
        queue: delivery.processing.oms.event.order-courier-assigned
        exchange: internal
        routing_key: oms.event.order-courier-assigned
        exchange_type: direct
        exchange_durable: true
        durable: true
        consume_all: true
        redial_timeout: 600
    process_oms_event_order-courier-canceled:
      driver: amqp
      config:
        queue: delivery.processing.oms.event.order-courier-canceled
        exchange: internal
        routing_key: oms.event.order-courier-canceled
        exchange_type: direct
        exchange_durable: true
        durable: true
        consume_all: true
        redial_timeout: 600
    process_oms_event_order-status-changed:
      driver: amqp
      config:
        queue: delivery.processing.oms.event.order-status-changed
        exchange: internal
        routing_key: oms.event.order-status-changed
        exchange_type: direct
        exchange_durable: true
        durable: true
        consume_all: true
        redial_timeout: 600
    process_partner_event_partner-user-created:
      driver: amqp
      config:
        queue: delivery.processing.partner.event.partner-user-created
        exchange: internal
        routing_key: partner.event.partner-user-created
        exchange_type: direct
        exchange_durable: true
        durable: true
        consume_all: true
        redial_timeout: 600
  consume:
  - process_delivery_command_wolt-drive_webhook
  - process_delivery_event_kitchen-created
  - process_oms_event_order-courier-assigned
  - process_oms_event_order-courier-canceled
  - process_oms_event_order-status-changed
  - process_partner_event_partner-user-created
...

```

Started
```
{"level":"debug","ts":1696679571819321659,"logger":"jobs","msg":"initializing driver","pipeline":"process_delivery_command_wolt-drive_webhook","driver":"amqp"}
{"level":"debug","ts":1696679571819057624,"logger":"jobs","msg":"initializing driver","pipeline":"process_delivery_event_kitchen-created","driver":"amqp"}
{"level":"debug","ts":1696679571819657018,"logger":"jobs","msg":"initializing driver","pipeline":"process_oms_event_order-courier-canceled","driver":"amqp"}
{"level":"debug","ts":1696679571819043001,"logger":"jobs","msg":"initializing driver","pipeline":"process_oms_event_order-status-changed","driver":"amqp"}
{"level":"debug","ts":1696679571819822386,"logger":"jobs","msg":"initializing driver","pipeline":"process_oms_event_order-courier-assigned","driver":"amqp"}
{"level":"debug","ts":1696679571819809560,"logger":"jobs","msg":"initializing driver","pipeline":"produce_delivery_event_status_updated","driver":"amqp"}
{"level":"debug","ts":1696679571819843409,"logger":"jobs","msg":"initializing driver","pipeline":"produce_delivery_event_kitchen-activity-updated","driver":"amqp"}
{"level":"debug","ts":1696679571819866214,"logger":"jobs","msg":"initializing driver","pipeline":"process_partner_event_partner-user-created","driver":"amqp"}
{"level":"debug","ts":1696679571819829357,"logger":"jobs","msg":"initializing driver","pipeline":"produce_command_logging_add-log","driver":"amqp"}
{"level":"debug","ts":1696679571819880741,"logger":"jobs","msg":"initializing driver","pipeline":"produce_delivery_event_kitchen-opening-time-updated","driver":"amqp"}
{"level":"debug","ts":1696679572067500687,"logger":"jobs","msg":"driver ready","pipeline":"produce_delivery_event_status_updated","driver":"amqp","start":1696679571823753431,"elapsed":0.243744397}
{"level":"debug","ts":1696679572067554891,"logger":"jobs","msg":"initializing driver","pipeline":"produce_delivery_event_kitchen-created","driver":"amqp"}
{"level":"debug","ts":1696679572067592934,"logger":"jobs","msg":"driver ready","pipeline":"process_delivery_event_kitchen-created","driver":"amqp","start":1696679571820030321,"elapsed":0.24756206}
{"level":"debug","ts":1696679572067663144,"logger":"jobs","msg":"driver ready","pipeline":"process_partner_event_partner-user-created","driver":"amqp","start":1696679571827186692,"elapsed":0.240476004}
{"level":"debug","ts":1696679572067770984,"logger":"jobs","msg":"driver ready","pipeline":"produce_delivery_event_kitchen-activity-updated","driver":"amqp","start":1696679571826961150,"elapsed":0.240809134}
{"level":"debug","ts":1696679572067802734,"logger":"jobs","msg":"driver ready","pipeline":"process_oms_event_order-courier-canceled","driver":"amqp","start":1696679571820169355,"elapsed":0.24763312}
{"level":"debug","ts":1696679572067806672,"logger":"jobs","msg":"driver ready","pipeline":"process_oms_event_order-courier-assigned","driver":"amqp","start":1696679571823004572,"elapsed":0.244801595}
{"level":"debug","ts":1696679572067533570,"logger":"jobs","msg":"driver ready","pipeline":"produce_delivery_event_kitchen-opening-time-updated","driver":"amqp","start":1696679571827542660,"elapsed":0.239989951}
{"level":"debug","ts":1696679572067865591,"logger":"jobs","msg":"driver ready","pipeline":"process_oms_event_order-status-changed","driver":"amqp","start":1696679571820377397,"elapsed":0.247487325}
{"level":"debug","ts":1696679572067505654,"logger":"jobs","msg":"driver ready","pipeline":"process_delivery_command_wolt-drive_webhook","driver":"amqp","start":1696679571819935221,"elapsed":0.247569213}
{"level":"debug","ts":1696679572072667695,"logger":"jobs","msg":"driver ready","pipeline":"produce_command_logging_add-log","driver":"amqp","start":1696679571827383254,"elapsed":0.245281892}
{"level":"debug","ts":1696679572089940787,"logger":"jobs","msg":"driver ready","pipeline":"produce_delivery_event_kitchen-created","driver":"amqp","start":1696679572067562080,"elapsed":0.022376102}
{"level":"debug","ts":1696679572114051084,"logger":"amqp","msg":"pipeline was started","driver":"amqp","pipeline":"process_oms_event_order-courier-canceled","start":1696679572067923940,"elapsed":0.0461256}
{"level":"debug","ts":1696679572114064080,"logger":"amqp","msg":"pipeline was started","driver":"amqp","pipeline":"process_delivery_event_kitchen-created","start":1696679572067632865,"elapsed":0.046430161}
{"level":"debug","ts":1696679572114016001,"logger":"amqp","msg":"pipeline was started","driver":"amqp","pipeline":"process_oms_event_order-courier-assigned","start":1696679572067977662,"elapsed":0.046035556}
{"level":"debug","ts":1696679572114073454,"logger":"amqp","msg":"pipeline was started","driver":"amqp","pipeline":"process_oms_event_order-status-changed","start":1696679572068007931,"elapsed":0.046064555}
{"level":"debug","ts":1696679572114530881,"logger":"amqp","msg":"pipeline was started","driver":"amqp","pipeline":"process_delivery_command_wolt-drive_webhook","start":1696679572068072466,"elapsed":0.046457833}
{"level":"debug","ts":1696679572114568649,"logger":"amqp","msg":"pipeline was started","driver":"amqp","pipeline":"process_partner_event_partner-user-created","start":1696679572067684291,"elapsed":0.046883677}
{"level":"debug","ts":1696679573056307977,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056398608,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056409557,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056415198,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056424690,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056421755,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056434230,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056429957,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056440407,"logger":"jobs","msg":"exited from jobs pipeline processor"}
{"level":"debug","ts":1696679573056443418,"logger":"jobs","msg":"exited from jobs pipeline processor"}
[INFO] RoadRunner server started; version: 2023.3.0, buildtime: 2023-10-05T23:30:26+0000
[INFO] sdnotify: not notified
```

CURL 
```bash 
curl localhost:8081/jobs
plugin: jobs: pipeline: produce_delivery_event_status_updated | priority: 10 | ready: false | queue:  | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: process_delivery_command_wolt-drive_webhook | priority: 10 | ready: true | queue: delivery.processing.delivery.command.wolt-drive.webhook | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: process_partner_event_partner-user-created | priority: 10 | ready: true | queue: delivery.processing.partner.event.partner-user-created | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: produce_delivery_event_kitchen-activity-updated | priority: 10 | ready: false | queue:  | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: process_oms_event_order-status-changed | priority: 10 | ready: true | queue: delivery.processing.oms.event.order-status-changed | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: produce_command_logging_add-log | priority: 10 | ready: false | queue:  | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: produce_delivery_event_kitchen-created | priority: 10 | ready: false | queue:  | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: produce_delivery_event_kitchen-opening-time-updated | priority: 10 | ready: false | queue:  | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: process_delivery_event_kitchen-created | priority: 10 | ready: true | queue: delivery.processing.delivery.event.kitchen-created | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: process_oms_event_order-courier-canceled | priority: 10 | ready: true | queue: delivery.processing.oms.event.order-courier-canceled | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  
plugin: jobs: pipeline: process_oms_event_order-courier-assigned | priority: 10 | ready: true | queue: delivery.processing.oms.event.order-courier-assigned | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  

```
Shutdown Rabbitmq

```bash 
{"level":"debug","ts":1696679970765113866,"logger":"amqp","msg":"exited from redialer"}
{"level":"debug","ts":1696679970766854528,"logger":"amqp","msg":"exited from redialer"}
{"level":"error","ts":1696679970766955700,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970769229423,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"debug","ts":1696679970769023551,"logger":"amqp","msg":"exited from redialer"}
{"level":"error","ts":1696679970769850577,"logger":"amqp","msg":"publish channel close","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970769990255,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970766968498,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970770062233,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"produce_delivery_event_kitchen-created","driver":"amqp","start":1696679970769282473}
{"level":"debug","ts":1696679970768666107,"logger":"amqp","msg":"exited from redialer"}
{"level":"debug","ts":1696679970771293928,"logger":"amqp","msg":"exited from redialer"}
{"level":"error","ts":1696679970771315161,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"debug","ts":1696679970771268833,"logger":"amqp","msg":"delivery channel was closed, leaving the rabbit listener"}
{"level":"debug","ts":1696679970771381934,"logger":"amqp","msg":"exited from redialer"}
{"level":"debug","ts":1696679970771409116,"logger":"amqp","msg":"number of listeners","listeners":0}
{"level":"error","ts":1696679970771441604,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970771392302,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"process_delivery_event_kitchen-created","driver":"amqp","start":1696679970771389326}
{"level":"error","ts":1696679970771483620,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"produce_delivery_event_kitchen-activity-updated","driver":"amqp","start":1696679970771472333}
{"level":"debug","ts":1696679970771015836,"logger":"amqp","msg":"exited from redialer"}
{"level":"error","ts":1696679970772151214,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970772182321,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"process_oms_event_order-courier-canceled","driver":"amqp","start":1696679970772179671}
{"level":"error","ts":1696679970770124336,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"produce_delivery_event_status_updated","driver":"amqp","start":1696679970770120283}
{"level":"debug","ts":1696679970768854996,"logger":"amqp","msg":"exited from redialer"}
{"level":"error","ts":1696679970768883123,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"debug","ts":1696679970772569683,"logger":"amqp","msg":"exited from redialer"}
{"level":"error","ts":1696679970772602051,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970772946845,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"process_oms_event_order-status-changed","driver":"amqp","start":1696679970772943328}
{"level":"error","ts":1696679970772901986,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"produce_command_logging_add-log","driver":"amqp","start":1696679970769256901}
{"level":"debug","ts":1696679970772507474,"logger":"amqp","msg":"delivery channel was closed, leaving the rabbit listener"}
{"level":"debug","ts":1696679970773322918,"logger":"amqp","msg":"number of listeners","listeners":0}
{"level":"debug","ts":1696679970768497645,"logger":"amqp","msg":"delivery channel was closed, leaving the rabbit listener"}
{"level":"debug","ts":1696679970773345924,"logger":"amqp","msg":"number of listeners","listeners":0}
{"level":"debug","ts":1696679970769134094,"logger":"amqp","msg":"exited from redialer"}
{"level":"error","ts":1696679970767615173,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970773366622,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"produce_delivery_event_kitchen-opening-time-updated","driver":"amqp","start":1696679970773364046}
{"level":"error","ts":1696679970770096535,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"process_delivery_command_wolt-drive_webhook","driver":"amqp","start":1696679970770014304}
{"level":"debug","ts":1696679970770851658,"logger":"amqp","msg":"exited from redialer"}
{"level":"debug","ts":1696679970770953935,"logger":"amqp","msg":"delivery channel was closed, leaving the rabbit listener"}
{"level":"debug","ts":1696679970773682411,"logger":"amqp","msg":"number of listeners","listeners":0}
{"level":"debug","ts":1696679970770693036,"logger":"amqp","msg":"delivery channel was closed, leaving the rabbit listener"}
{"level":"debug","ts":1696679970774357026,"logger":"amqp","msg":"number of listeners","listeners":0}
{"level":"error","ts":1696679970770998389,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1696679970772470104,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"process_partner_event_partner-user-created","driver":"amqp","start":1696679970772467570}
{"level":"debug","ts":1696679970768114020,"logger":"amqp","msg":"delivery channel was closed, leaving the rabbit listener"}
{"level":"debug","ts":1696679970775771830,"logger":"amqp","msg":"number of listeners","listeners":0}
{"level":"error","ts":1696679970777033128,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"process_oms_event_order-courier-assigned","driver":"amqp","start":1696679970777027182}
```

CURL 
```bash
curl localhost:8081/jobs
curl: (52) Empty reply from server
```
