### ISSUE TITLE
[🐛 BUG]: Jobs amqp redial backoff operation failed  && health-check endpoint say that everything is correct

### ISSUE THREAD

**Issue by iborysenko** [roadrunner-server/roadrunner#1724]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

JOBS && STATUS  after redial backoff operation failed status plugin report that everything is ok with jobs 

### Version (rr --version)

2023.2

### How to reproduce the issue?

1. Start the RR server 
```yaml 
status:
  address: 0.0.0.0:8081
jobs:
  consume: 
     - process_pipeline_event
  pipelines:
    process_pipeline_event:
      driver: amqp
      config:
        queue: service-name.processing.process_pipeline_event
        exchange: default
        routing_key: process_pipeline_event
        exchange_type: direct
        exchange_durable: true
        durable: true
        consume_all: true
        redial_timeout: 1 # just to emulate Redial error 
```
Logs 

```bash 
{"level":"debug","ts":1694594308835966503,"logger":"jobs","msg":"driver ready","pipeline":"process_pipeline_event","driver":"amqp","start":1694594308822999737,"elapsed":0.012961669}
{"level":"debug","ts":1694594308842897174,"logger":"amqp","msg":"pipeline was started","driver":"amqp","pipeline":"process_pipeline_event","start":1694594308836060054,"elapsed":0.006833715}
[INFO] RoadRunner server started; version: 2023.2.2, buildtime: 2023-08-10T16:38:29+0000

```

Healthchecks 
```bash 
curl localhost:8081/health?plugin=jobs
plugin: jobs, status: 200

curl localhost:8081/ready?plugin=jobs
plugin: jobs, status: 200

curl localhost:8081/jobs              
plugin: jobs: pipeline: process_pipeline_event | priority: 10 | ready: true | queue: service-name.processing.process_pipeline_event | active: 0 | delayed: 0 | reserved: 0 | driver: amqp | error:  


```

2. Shutdown rabbitmq server 
Logs 
```bash 

{"level":"debug","ts":1694594598597609300,"logger":"amqp","msg":"exited from redialer"}
{"level":"debug","ts":1694594598598822624,"logger":"amqp","msg":"delivery channel was closed, leaving the rabbit listener"}
{"level":"debug","ts":1694594598623445593,"logger":"amqp","msg":"number of listeners","listeners":0}
{"level":"error","ts":1694594598623928672,"logger":"amqp","msg":"publish channel close","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1694594598625415793,"logger":"amqp","msg":"state channel close","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1694594598625534240,"logger":"amqp","msg":"consume channel close","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1694594598625611612,"logger":"amqp","msg":"amqp connection closed","error":"Exception (504) Reason: \"channel/connection is not open\""}
{"level":"error","ts":1694594598625818289,"logger":"amqp","msg":"pipeline connection was closed, redialing","error":"Exception (320) Reason: \"CONNECTION_FORCED - broker forced connection closure with reason 'shutdown'\"","pipeline":"process_pipeline_event","driver":"amqp","start":1694594598625660912}
{"level":"error","ts":1694594599409217586,"logger":"amqp","msg":"backoff operation failed","error":"rabbitmq_redial: dial tcp: lookup local-stack-rabbitmq on 10.96.0.10:53: no such host"}

```

Healthchecks 
```bash 
curl localhost:8081/ready?plugin=jobs
plugin: jobs, status: 200  

curl localhost:8081/health?plugin=jobs
plugin: jobs, status: 200 

curl localhost:8081/jobs # timeout 
```

So as you can see, plugin status not changed. And in the same time RR will not to try to reconnect again. 
As a result, when I UP rabbitmq server consuming will not start and helthcheck always report that everything is ok
