### ISSUE TITLE
[🐛 BUG]: no amqp queues creation without consuming

### ISSUE THREAD

**Issue by Kreczat** [roadrunner-server/roadrunner#1732]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Hello!
There is no queue creation if consume section not specified.

### Version (rr --version)

2023.2.2

### How to reproduce the issue?

 ```
 pipelines:
    job-api-pipe:
      driver: amqp
      config:
        queue: job.api.pipe
        exchange: job.api
        exchange_type: direct
        routing_key: job.api.pipe
        exchange_durable: true
        durable: true
        redial_timeout: 14400
```
exchange was created, queue was not created

if I add consume section, queue and exchange bind are creating but I need no consumer for this queue in my app. There will be consumer in other app and I want to check packets in queue.
