### ISSUE TITLE
[🐛 BUG]: Unable to POST relatively chunky POST

### ISSUE THREAD

**Issue by FluffyDiscord** [roadrunner-server/roadrunner#1765]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I am trying to post relatively big payload and RR server is failing. I am not sure if this is issue on my end (somehow sending the payload wrong) or the RR server (unable to parse it)

### Version (rr --version)

rr version 2023.3.3 (build time: 2023-10-26T18:43:18+0000, go1.21.3), OS: linux, arch: amd64

### How to reproduce the issue?

.rr.yaml
```yaml
version: "3"

server:
    command: "php public/index.php"
    env:
        -   APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

kv:
    memory:
        driver: memory
        config: { }

rpc:
    listen: tcp://127.0.0.1:6001

http:
    address: 0.0.0.0:8080
    middleware: [ "sendfile", "gzip", "static" ]
    pool:
        debug: true
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    static:
        dir: "public"
        forbid: [ ".php", ".htaccess" ]

logs:
    mode: development
    channels:
        http:
            level: debug # Log all http requests, set to info to disable
        server:
            level: debug # Everything written to worker stderr is logged
            mode: raw
        metrics:
            level: debug
```

Example curl with the payload that is failing:
[example_curl.txt](https://github.com/roadrunner-server/roadrunner/files/13238077/example_curl.txt)

### Relevant log output

```shell
internal server error	{"message": "http_plugin: 2023/11/02 10:59:44 http: panic serving 192.168.160.1:33040: interface conversion: interface {} is string, not handler.dataTree\ngoroutine 16 [running]:\nnet/http.(*conn).serve.func1()\n\tnet/http/server.go:1868 +0xb9\npanic({0x1bf8740?, 0xc000dbcb40?})\n\truntime/panic.go:920 +0x270\ngithub.com/roadrunner-server/http/v4/handler.dataTree.mount(0x1c832a0?, {0xc000b151c0?, 0x2, 0x4}, {0xc0018884f0?, 0x1, 0x1})\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/parse.go:109 +0x306\ngithub.com/roadrunner-server/http/v4/handler.dataTree.mount(0x1c832a0?, {0xc000b151b0?, 0x3, 0x5}, {0xc0018884f0?, 0x1, 0x1})\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/parse.go:109 +0x2ce\ngithub.com/roadrunner-server/http/v4/handler.dataTree.mount(0x1c832a0?, {0xc000b151a0?, 0x4, 0x6}, {0xc0018884f0?, 0x1, 0x1})\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/parse.go:109 +0x2ce\ngithub.com/roadrunner-server/http/v4/handler.dataTree.mount(0x1c832a0?, {0xc000b15190?, 0x5, 0x7}, {0xc0018884f0?, 0x1, 0x1})\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/parse.go:109 +0x2ce\ngithub.com/roadrunner-server/http/v4/handler.dataTree.mount(0xc000050b80?, {0xc000b15180?, 0x6, 0x8}, {0xc0018884f0?, 0x1, 0x1})\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/parse.go:109 +0x2ce\ngithub.com/roadrunner-server/http/v4/handler.dataTree.push(0xc00093a4c8?, {0xc001898d00, 0x24}, {0xc0018884f0, 0x1, 0x1})\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/parse.go:50 +0x31d\ngithub.com/roadrunner-server/http/v4/handler.parseMultipartData(0xc0001bc800)\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/parse.go:36 +0xbc\ngithub.com/roadrunner-server/http/v4/handler.request(0xc0001bc800, 0xc00081cea0, 0x0?, 0x0?, 0x0)\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/request.go:101 +0x472\ngithub.com/roadrunner-server/http/v4/handler.(*Handler).ServeHTTP(0xc000c3c960, {0x242b180, 0xc0001bf5c0}, 0x1df2dc0?)\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/handler/handler.go:114 +0xe8\ngithub.com/roadrunner-server/http/v4.(*Plugin).ServeHTTP(0xc0000eaea0, {0x242b180, 0xc0001bf5c0}, 0xc0001bc800)\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/plugin.go:208 +0x465\ngithub.com/roadrunner-server/http/v4.(*Plugin).applyBundledMiddleware.MaxRequestSize.func1({0x242b180, 0xc0001bf5c0}, 0xffffffffffffffff?)\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/middleware/maxRequest.go:15 +0xb6\nnet/http.HandlerFunc.ServeHTTP(0xc0001bc600?, {0x242b180?, 0xc0001bf5c0?}, 0xc001037028?)\n\tnet/http/server.go:2136 +0x29\ngithub.com/roadrunner-server/http/v4.(*Plugin).applyBundledMiddleware.NewLogMiddleware.(*lm).Log.func3({0x242b2a0, 0xc00083e600}, 0x1ba7f40?)\n\tgithub.com/roadrunner-server/http/v4@v4.4.5/middleware/log.go:125 +0x17a\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x242b2a0?, 0xc00083e600?}, 0x0?)\n\tnet/http/server.go:2136 +0x29\ngithub.com/roadrunner-server/send/v4.(*Plugin).Middleware.func1({0x242b870, 0xc000c1c0a0}, 0xc0001bc600)\n\tgithub.com/roadrunner-server/send/v4@v4.2.8/plugin.go:77 +0x53a\nnet/http.HandlerFunc.ServeHTTP(0xc00091b580?, {0x242b870?, 0xc000c1c0a0?}, 0xa0?)\n\tnet/http/server.go:2136 +0x29\ngithub.com/roadrunner-server/gzip/v4.(*Plugin).Middleware.func1({0x242b870, 0xc000c1c0a0}, 0xc0001bc600)\n\tgithub.com/roadrunner-server/gzip/v4@v4.1.8/plugin.go:43 +0x472\nnet/http.HandlerFunc.ServeHTTP(0x1bfb0c0?, {0x242b870?, 0xc000c1c0a0?}, 0x1edc0cb?)\n\tnet/http/server.go:2136 +0x29\ngithub.com/klauspost/compress/gzhttp.NewWrapper.func1.1({0x242a190, 0xc0009280e0}, 0x1ba7f40?)\n\tgithub.com/klauspost/compress@v1.17.2/gzhttp/compress.go:486 +0x28b\nnet/http.HandlerFunc.ServeHTTP(0x0?, {0x242a190?, 0xc0009280e0?}, 0x1?)\n\tnet/http/server.go:2136 +0x29\ngithub.com/roadrunner-server/static/v4.(*Plugin).Middleware.func1({0x242a190, 0xc0009280e0}, 0xc0001bc600)\n\tgithub.com/roadrunner-server/static/v4@v4.1.8/plugin.go:149 +0x59e\nnet/http.HandlerFunc.ServeHTTP(0x2423910?, {0x242a190?, 0xc0009280e0?}, 0x6?)\n\tnet/http/server.go:2136 +0x29\nnet/http.serverHandler.ServeHTTP(...)\n\tnet/http/server.go:2938\nnet/http.(*conn).serve(0xc0000ead80, {0x24325e0, 0xc000c1b080})\n\tnet/http/server.go:2009 +0x65d\ncreated by net/http.(*Server).Serve in goroutine 73\n\tnet/http/server.go:3086 +0x5cb\n"}
```
