### ISSUE TITLE
[🐛 BUG]: Jobs amqp Error while producing messages with same delay and exchange type direct

### ISSUE THREAD

**Issue by fereron** [roadrunner-server/roadrunner#1792]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

..

### Version (rr --version)

2023.3.6

### How to reproduce the issue?

``` yaml
jobs:
  pipelines:
    queue1:
      driver: amqp
      config:
        durable: true
        exchange: amqp.direct
        routing_key: queue1
        exchange_type: direct
        exchange_durable: true
     queue2:
      driver: amqp
      config:
        durable: true
        exchange: amqp.direct
        routing_key: queue2
        exchange_type: direct
        exchange_durable: true
```

``` php
$this->jobs->connect('queue1')->push(
    name: 'queue1',
    payload: 'message',
    options: (new Options())->withDelay(20)
);

$this->jobs->connect('queue2')->push(
    name: 'queue2',
    payload: 'message',
    options: (new Options())->withDelay(20)
);
```

When producing RR will try to create the same queue `delayed-20000.amqp.direct.` for them, which will cause an error:
```
Error 'rpc_push:
	jobs_plugin_push:
	rabbitmq_push:
	rabbitmq_handle_item: Exception (406) Reason: "PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-routing-key' for queue 'delayed-20000.amqp.direct.' in vhost '/': received 'queue2' but current is 'queue1'"' on tcp://127.0.0.1:6001
```

I think this is happening because we have a direct exchange type and there are no queue names in the pipeline config.
Maybe we should add a check for an empty queue and use "rk" instead [at this point](https://github.com/roadrunner-server/amqp/blob/master/amqpjobs/driver.go#L645)?

### Relevant log output

```shell
2023-11-28T05:08:05+0000	INFO	server      	{"message":"Exception thrown when handling an exception (Spiral\\RoadRunner\\Jobs\\Exception\\JobsException: Error 'rpc_push:\n\tjobs_plugin_push:\n\trabbitmq_push:\n\trabbitmq_handle_item: Exception (406) Reason: \"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-routing-key' for queue 'delayed-20000.amqp.direct.' in vhost '/': received 'queue2' but current is 'queue1'\"' on tcp://127.0.0.1:6001 at /var/www/project/vendor/spiral/roadrunner-jobs/src/Queue/Pipeline.php line 47)","context":{"exception":{"class":"Spiral\\RoadRunner\\Jobs\\Exception\\JobsException","message":"Error 'rpc_push:\n\tjobs_plugin_push:\n\trabbitmq_push:\n\trabbitmq_handle_item: Exception (406) Reason: \"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-routing-key' for queue 'delayed-20000.amqp.direct.' in vhost '/': received 'queue2' but current is 'queue1'\"' on tcp://127.0.0.1:6001","code":0,"file":"/var/www/project/vendor/spiral/roadrunner-jobs/src/Queue/Pipeline.php:47","previous":{"class":"Spiral\\Goridge\\RPC\\Exception\\ServiceException","message":"Error 'rpc_push:\n\tjobs_plugin_push:\n\trabbitmq_push:\n\trabbitmq_handle_item: Exception (406) Reason: \"PRECONDITION_FAILED - inequivalent arg 'x-dead-letter-routing-key' for queue 'delayed-20000.amqp.direct.' in vhost '/': received 'queue2' but current is 'queue1'\"' on tcp://127.0.0.1:6001","code":0,"file":"/var/www/project/vendor/spiral/goridge/src/RPC/RPC.php:101"}}},"level":500,"level_name":"CRITICAL","channel":"exception","datetime":"2023-11-28T05:08:05.481257+00:00","extra":{"http_method":"GET","ip":"127.0.0.1","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36","status_code":500}}
```
