### ISSUE TITLE
[🐛 BUG]: Jobs AMQP headers with list type not mapped to RR job 

### ISSUE THREAD

**Issue by iborysenko** [roadrunner-server/roadrunner#1793]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!
Jobs AMQP headers with list type not mapped to RR job 

<img width="771" alt="Screenshot 2023-11-29 at 16 25 02" src="https://github.com/roadrunner-server/roadrunner/assets/17834238/e7e237e6-4826-4ab3-b05b-7ed104eabc9d">

### Version (rr --version)

2023.3

### How to reproduce the issue?

Publish message with list type headers

**Comment by rustatian** [comment]
Hey @iborysenko 👋 
Please attach a worker, configuration (.rr.yaml) and all the needed data to reproduce this problem.

EDIT: Also, attach your composer.json or specify versions. Also, if you push headers via separate script, attach it as well.

**Comment by iborysenko** [comment]
Hey @rustatian 
```yaml
jobs:
    pipelines:
        processing_pipeline:
            driver: amqp
            config:
              queue: my-queue
              exchange: my-exchange
              routing_key: my-queue-routing-key
              exchange_type: direct
              exchange_durable: true
              durable: true
              consume_all: true
              redial_timeout: 600
```         

1. Go to the RabbitMQ Management UI and publish a message to the `my-queue` with headers (like on screenshot above)
2. Start consuming messages via RR.
3. RR forward only headers with type `string` but not `list` 

---- 
We are using Krakend-gateway to publish webhooks to the queue, and then RR consumes them
Krakend put allowed HTTP headers to the AMQP Message Headers as List 
```go 
    headerValues := make([]interface{}, len(vs))
    for k, v := range vs {
    headerValues[k] = v
    }
    headers[k] = headerValues
```

Anyway we will fork this lib and fix it for us, but I noticed that RR does not support these header type
