### ISSUE TITLE
[🐛 BUG]: Static middleware doesn't server files without extension

### ISSUE THREAD

**Issue by m157y** [roadrunner-server/roadrunner#1813]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

It's impossible to serve static files without extension by `static` middleware.

Log output not really needed, but I attached it to show that RR handled this request and passed to worker.

### Version (rr --version)

2023.3.8 (build time: 2023-12-14T16:05:31+0000, go1.21.5), OS: darwin, arch: arm64

### How to reproduce the issue?

Put image with filename `1` and filename `1.jpg` to `public/` (in relation to config below), enable static middleware (enabled in config below) and try to open file `1` (in case of config below it'll be next url `http://localhost:8080/1`), RR will handle this request by PHP worker, but if you'll try to open `1.jpg` (`http://localhost:8080/1.jpg`), it'll be opened without any issues.

`.rr.yaml` below:

```yaml
version: '3'

rpc:
  listen: tcp://127.0.0.1:6001

server:
  command: "php src/worker.php"
  relay: pipes

logs:
  mode: development
  level: debug
  encoding: console
  output: stderr
  err_output: stderr

http:
  address: 127.0.0.1:8080
  internal_error_code: 505
  access_logs: false
  raw_body: true
  middleware: [ "static" ]
  uploads:
    dir: "/tmp"
  static:
    dir: "public/"
    forbid: [ "index.php" ]
```

### Relevant log output

```shell
2023-12-16T14:04:12+0000	INFO	http        	http log	{"status": 200, "method": "GET", "URI": "/1", "remote_address": "127.0.0.1:57121", "read_bytes": 0, "write_bytes": 2877, "start": "2023-12-16T14:04:12+0000", "elapsed": "15.843084ms"}
```
