### ISSUE TITLE
[🐛 BUG]: HTTP Queue gets too large

### ISSUE THREAD

**Issue by L3tum** [roadrunner-server/roadrunner#1841]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Not necessarily a bug, maybe a feature request, but eh. 
We've observed that the HTTP Request Queue, which is usually a good thing for small delays, can grow way too large.
In particular this seems to be happening when no workers are available anymore. What I would expect (from reading the docs) is that a few requests may be queued but most would be denied outright. Instead we observed a request queue of ~5000 requests, which is just too much.
What I would love is for this to be configurable, but it'd be a start to get some kind of documentation on what to expect from this. The only reference to a queue in the docs and issues is related to the JOBS queue.

Here's a screenshot showing a queue of 150000 requests across 30 instances (so 5000 per instance):
![{5B2CE156-CE59-48C7-AFB4-83D2745B2FE5}](https://github.com/roadrunner-server/roadrunner/assets/9307432/034c646c-a07f-451f-b9cc-063b6e905217)

I know it's kind of extreme but a circuit breaker within RR would be extremely useful.

### Version (rr --version)

Latest (v2023.3.9)

### How to reproduce the issue?

Launch RR and run a load test that is overloading the system

### Relevant log output

```shell
-
```

**Comment by rustatian** [comment]
Hey @L3tum 👋 
Could you please share your configuration as well? (`.rr.yaml`) ?

**Comment by L3tum** [comment]
Sure, although it's fairly standard I think (hope):
````yaml
version: '3'

server:
    command: "php public/index.php"
    env:
        APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime

rpc:
    listen: tcp://127.0.0.1:6001

metrics:
    address: "0.0.0.0:9180"

http:
    address: 0.0.0.0:8080
    # Maximal incoming request size in megabytes. Zero means no limit.
    max_request_size: 4
    middleware: [ "http_metrics" ]
    uploads:
        forbid: [ ".php", ".exe", ".bat" ]
    pool:
        num_workers: 4
        # Timeout for worker allocation. Zero means no limit.
        allocate_timeout: 60s
        # Timeout for worker destroying before process killing. Zero means no limit.
        destroy_timeout: 60s
        supervisor:
            # watch_tick defines how often to check the state of the workers (seconds)
            watch_tick: 10s
            # ttl defines maximum time worker is allowed to live (seconds)
            ttl: 0s
            # idle_ttl defines maximum duration worker can spend in idle mode after first use. Disabled when 0 (seconds)
            idle_ttl: 0s
            # exec_ttl defines maximum lifetime per job (seconds)
            exec_ttl: 2s
            # max_worker_memory limits memory usage per worker (MB)
            max_worker_memory: 256
    # HTTP/2 settings.
    http2:
        # HTTP/2 over non-encrypted TCP connection using H2C.
        #
        # Default: false
        h2c: true

        # Maximal concurrent streams count.
        #
        # Default: 128
        max_concurrent_streams: 128

# Health check endpoint (docs: https://roadrunner.dev/docs/beep-beep-health). If response code is 200 - it means at
# least one worker ready to serve requests. 500 - there are no workers ready to service requests.
# Drop this section for this feature disabling.
status:
    # Host and port to listen on (eg.: `127.0.0.1:2114`). Use the following URL: http://127.0.0.1:2114/health?plugin=http
    # Multiple plugins must be separated using "&" - http://127.0.0.1:2114/health?plugin=http&plugin=rpc where "http" and
    # "rpc" are active (connected) plugins.
    #
    # This option is required.
    address: 0.0.0.0:2114

    # Response status code if a requested plugin not ready to handle requests
    # Valid for both /health and /ready endpoints
    #
    # Default: 503
    unavailable_status_code: 503

logs:
    mode: production
    encoding: json
    channels:
        http:
            level: warn # debug Log all http requests, set to info to disable
        server:
            level: info # Everything written to worker stderr is logged
            mode: raw
        metrics:
            level: error

````
