### ISSUE TITLE
[🐛 BUG]: unknown flag for long config options

### ISSUE THREAD

**Issue by astronom** [roadrunner-server/roadrunner#1860]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

`unknown flag: --config .rr.temporal.prod.yaml` only happens when try to start docker container with command arguments. When inside the container all long options works. And short option names is works both inside and outside the container

### Version (rr --version)

2023.3.6+

### How to reproduce the issue?

```yaml
version: '3'

services:
    temporal-worker:
        restart: "no"
        user: "1000:1000"
        image: ghcr.io/roadrunner-server/roadrunner:2023.3.10
        command: [
          "--config .rr.temporal.prod.yaml",
          "--override temporal.address=temporal:7233",
          "--override temporal.activities.num_workers=2",
          "--override temporal.activities.supervisor.max_worker_memory=128",
          "--override endure.grace_period=120",
          "serve"
        ]
```

### Relevant log output

```shell
`unknown flag: --config .rr.temporal.prod.yaml`
```
