### ISSUE TITLE
[🐛 BUG]: File uploads exceeding "upload_max_filesize" do not have the proper error code

### ISSUE THREAD

**Issue by mariusklocke** [roadrunner-server/roadrunner#1870]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I set `upload_max_filesize=2M` for PHP-CLI. I start up my application using the PSR7 Components of Roadrunner. I check the uploaded file using `$uploadedFile->getError()` which should return one of PHPs `UPLOAD_ERR` constants. When uploading a file larger than "2M" the error code is `UPLOAD_ERR_OK`. I expected to receive `UPLOAD_ERR_INI_SIZE` in this case.

Although there is a `uploads` section in `.rr.yaml`, there doesn't seem to be something for limiting file sizes.

### Version (rr --version)

2023.3.10

### How to reproduce the issue?

* Configure PHP CLI with `upload_max_filesize=2M` 
* Start an application using `psr-worker.php` from Step 4 in Quick Start Guide for Roadrunner
* Put in some logging for `$request->getUploadedFiles()` and `ini_get('upload_max_filesize')`
* Upload a file exceeding the limit using `POST`  and `multipart/form-data` and check log outputs

**Comment by rustatian** [comment]
Hey @mariusklocke 👋 
Could you please share your `.rr.yaml` configuration?

**Comment by mariusklocke** [comment]
Hey @rustatian ,

sure:

```
version: '3'
server:
  command: "lima-worker"
  user: "www-data"
  group: "www-data"
http:
  address: "0.0.0.0:8080"
  pool:
    num_workers: 1
logs:
  channels:
    http:
      mode: raw
      level: panic
      encoding: console
      output: stdout
      err_output: stderr
    server:
      mode: raw
      level: info
      encoding: console
      output: stdout
      err_output: stderr
```
