### ISSUE TITLE
[🐛 BUG]: Incorrect name of the default AMQP exchange (should be 'amq.default')

### ISSUE THREAD

**Issue by janchaloupka** [roadrunner-server/roadrunner#1909]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

When the exchange name for the AMQP pipeline is not specified, the roadrunner defaults to exchange with the name `amqp.default`. This is incorrect as the default exchange name is `amq.default` - as evident from the RabbitMq web interface and official RabbitMq documentation:
> For convenience RabbitMQ maps AMQP 0-9-1's default exchange's blank name to 'amq.default' when performing permission checks

Source: https://www.rabbitmq.com/docs/access-control

### Version (rr --version)

2023.3.11

### How to reproduce the issue?

Define amqp job pipeline without the `exchange` key, for example:

```yml
jobs:
  consume:
    - test
  pipelines:
    test:
      driver: amqp
      config:
        durable: true
        queue: testQueue
```

Roadrunner then on startup creates a new `amqp.default` exchange, when I expected it to use the existing `amq.default` exchange.
