### ISSUE TITLE
[🐛 BUG]: hardcoded sampler-specific configuration for otel plugin

### ISSUE THREAD

**Issue by bazilmarkov** [roadrunner-server/roadrunner#1918]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

It appears that the `OTEL_TRACES_SAMPLER` and `OTEL_TRACES_SAMPLER_ARG` settings are not having any effect, and the Roadrunner `otel` plugin is still using the default `always_on` sampling method. 

I have been attempting to use `traceidratio` with a default sampling rate of 1%, but have not been successful so far. 

I have tried to configure it using the global environment variables mentioned on the [relevant page](https://opentelemetry.io/docs/languages/sdk-configuration/general/#otel_traces_sampler), but it seems that the sampler is hardcoded to always be on, as per [the code](https://github.com/roadrunner-server/otel/blob/master/plugin.go#L116)

### Version (rr --version)

2024.1.1

### How to reproduce the issue?

1. Set up basic `otel` configuration paired with `grpc` plugin.

```yaml
otel:
  resource:
    service_name: ${SERVICE}
    service_version: ${VERSION}
  insecure: true
  exporter: otlp
  endpoint: ${AGENT_HOST}:4318
```
2. Set up the tracer and sampling rate different from the default `always_on ` using env variables

```
    OTEL_TRACES_SAMPLER: 'traceidratio'
    OTEL_TRACES_SAMPLER_ARG: '0.01'
```

3. Make 100 requests to the service.

**Expected result**: 1% of the spans sent
**Current result**: 100% of the spans sent
