### ISSUE TITLE
[🐛 BUG]: High memory consumption with no load

### ISSUE THREAD

**Issue by speller** [roadrunner-server/roadrunner#1950]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Immediately after starting, RR consumes more than 1GB memory:

<img width="710" alt="image" src="https://github.com/roadrunner-server/roadrunner/assets/1829515/56597d01-f35c-49b4-81e2-24f09d59811a">

### Version (rr --version)

2024.1.5

### How to reproduce the issue?

Not sure, I'm just running it:

```yaml
version: '3.8'

server:
  command: "php -d max_execution_time=${HTTP_TIMEOUT} index.php"
  # If you are not using symfony 5.3+ and the new Runtime component:
  # remove the previous `command` line above and uncomment the line below to use the deprecated command.
  # command: "php bin/console baldinof:roadrunner:worker"
  env:
    APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
    SERVER_NAME: _web_
    XDEBUG_TRIGGER: 1

http:
  address: 0.0.0.0:${CONTAINER_PORT}
  middleware: [ "headers", "static", "gzip" ]
  uploads:
    forbid: [ ".php", ".exe", ".bat" ]
  static:
    dir: "public"
    forbid: [ ".php", ".htaccess" ]
  pool:
    debug: ${RR_RELOAD_ENABLED}
    num_workers: ${RR_NUM_WORKERS}
    allocate_timeout: ${RR_ALLOCATE_TIMEOUT}s
    max_jobs: ${RR_MAX_JOBS}
    supervisor:
      exec_ttl: ${RR_JOB_TIMEOUT}s

logs:
  mode: ${RR_LOG_MODE}
  encoding: ${RR_LOG_ENCODING}
  channels:
    http:
      level: debug # Log all http requests, set to info to disable
    server:
      level: info # Everything written to worker stderr is logged
      mode: raw
    metrics:
      level: error
```

PS: XDebug is not installed.
