### ISSUE TITLE
[🐛 BUG]: on_init command with defined user fails

### ISSUE THREAD

**Issue by rmikalkenas** [roadrunner-server/roadrunner#1974]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

I was playing around the `on_init` command and noticed that it does not work if custom `user` is passed. Attaching error output.

Related change: https://github.com/roadrunner-server/server/pull/68

### Version (rr --version)

2024.1.5

### How to reproduce the issue?

```
server:
    on_init:
        command: '/var/www/bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration'
        user: "rokas"
    command: 'php /var/www/public/index.php'
    user: "rokas"
    group: "rokas"
    env:
        - APP_RUNTIME: Baldinof\RoadRunnerBundle\Runtime\Runtime
```

### Relevant log output

```shell
root@8955c8249e90:/var/www# rr serve -c .rr.yaml 

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8a04c9]

goroutine 1 [running]:
github.com/roadrunner-server/sdk/v4/utils.ExecuteFromUser(0xc0006a49a0, {0xc00099b824?, 0xc000c18cd0?})
        github.com/roadrunner-server/sdk/v4@v4.7.3/utils/isolate.go:53 +0x3c9
github.com/roadrunner-server/server/v4.(*command).start(0xc000061af0)
        github.com/roadrunner-server/server/v4@v4.8.5/init.go:34 +0x91
github.com/roadrunner-server/server/v4.(*Plugin).Serve(0xc0009a0b00)
        github.com/roadrunner-server/server/v4@v4.8.5/plugin.go:162 +0xb6
reflect.Value.call({0xc0000c8d70?, 0xc000995c20?, 0x41841f?}, {0x1e9f6bf, 0x4}, {0xc000129bc0, 0x1, 0xc00091f738?})
        reflect/value.go:596 +0xca6
reflect.Value.Call({0xc0000c8d70?, 0xc000995c20?, 0x36b79e0?}, {0xc000129bc0?, 0x1ebb244?, 0x14?})
        reflect/value.go:380 +0xb9
github.com/roadrunner-server/endure/v2.(*Endure).serve(0xc0009a4be0)
        github.com/roadrunner-server/endure/v2@v2.4.5/serve.go:44 +0x55a
github.com/roadrunner-server/endure/v2.(*Endure).Serve(0xc0009a4be0)
        github.com/roadrunner-server/endure/v2@v2.4.5/endure.go:212 +0xd7
github.com/roadrunner-server/roadrunner/v2024/internal/cli.NewCommand.NewCommand.func3(0xc0005c0e00?, {0x1e9f64b?, 0x4?, 0x1e9f64f?})
        github.com/roadrunner-server/roadrunner/v2024/internal/cli/serve/command.go:74 +0x56c
github.com/spf13/cobra.(*Command).execute(0xc0005e0c08, {0xc00099edc0, 0x2, 0x2})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc0005e0308)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0x7ffd55267c6b?)
        github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
main.run()
        github.com/roadrunner-server/roadrunner/v2024/cmd/rr/main.go:26 +0x45
main.main()
        github.com/roadrunner-server/roadrunner/v2024/cmd/rr/main.go:16 +0x13
```
