### ISSUE TITLE
[🧹 CHORE]: Inconsistency with service logs output

### ISSUE THREAD

**Issue by rmikalkenas** [roadrunner-server/roadrunner#1993]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

While using services functionality, I noticed that if command has any output or streams logs, there is not way to show them as raw output. This is possible for http logs by passing a raw mode.

Example:

If I define channel for log service as such:
```
logs:
    mode: production
    output: stderr
    err_output: stderr
    encoding: json
    channels:
        service.rr-testing:
            level: info
            mode: raw
```

then the log stream looks like this:

```
2024-08-22T09:31:24+0000     INFO    service.rr-testing      {"message":"Testing RR logs","context":{"context":42},"level":300,"level_name":"WARNING","channel":"app","datetime":"2024-08-22T09:31:24.561570+00:00","extra":{}}
```

but if I omit channel configuration, then I get such structure:
```
{"level":"info","ts":1724318758346296596,"logger":"service.rr-testing","msg":"{\"message\":\"Testing RR logs\",\"context\":{\"context\":42},\"level\":300,\"level_name\":\"WARNING\",\"channel\":\"app\",\"datetime\":\"2024-08-22T09:25:58.346089+00:00\",\"extra\":{}}"}
```

Tried various configuration, but was not able to get a clean output of what command returns:
```
{"message":"Testing RR logs","context":{"context":42},"level":300,"level_name":"WARNING","channel":"app","datetime":"2024-08-22T09:31:24.561570+00:00","extra":{}}
```

```
version: '3'

service:
    rr-testing:
        command: "/var/www/bin/console app:q"
        process_num: 1
        remain_after_exit: true
        timeout_stop_sec: 10
        restart_sec: 1
        service_name_in_log: true
```

**Comment by rmikalkenas** [comment]
Didn't know which category to choose, as it not seem like a big, but more like inconsistency with how different log modes should behave

**Comment by rustatian** [comment]
Hey @rmikalkenas 👋 
All logs in the `service` plugin can be configured used `service` channel:
```yaml
logs:
    mode: production
    output: stderr
    err_output: stderr
    encoding: json
    channels:
        service:
            level: info
            mode: raw
```
