### ISSUE TITLE
[🧹 CHORE]: Extra spaces in logger name

### ISSUE THREAD

**Issue by Kaspiman** [roadrunner-server/roadrunner#2023]
### No duplicates 🥲.

- [X] I have searched for a similar issue.

### What should be improved or cleaned up?

Typical RR conf:
```
logs:
    encoding: json
    level: debug
    mode: development
```

Example:
```
{"level":"DEBUG","ts":"2024-10-10T13:44:06+0000","logger":"server      ","msg":"sending stop request to the worker","pid":41}
```

![Monosnap service-template – SomeController php 202](https://github.com/user-attachments/assets/80cbc199-615e-412e-b0af-8848f3a6b112)
