### ISSUE TITLE
[🐛 BUG]: errors when processing smtp commands

### ISSUE THREAD

**Issue by MihailDev** [roadrunner-server/roadrunner#2087]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

when I try to receive many letters! in single connections I have not noticed such problems

### Version (rr --version)

3

### How to reproduce the issue?

```
tcp:
  servers:
    smtp:
      addr: '127.0.0.1:1025'
      delimiter: "\r\n"
```

my handler is based on buggregator's SMTP handling implementation

I log all request commands. When processing 300 letters, this happens to me from 2 to 10 times

in logs can find commands like "NOOP\r\nQUIT\r\n" or "DATA\r\nRSET\r\n"

the delimiter(\r\n) is correct but the commands are merged
