### ISSUE TITLE
[🐛 BUG]: Downscale workers didn't work correctly

### ISSUE THREAD

**Issue by Smolevich** [roadrunner-server/roadrunner#2092]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

TEMPORAL_ROADRUNNER_MAX_WORKERS_COUNT=20
TEMPORAL_ROADRUNNER_WORKERS_COUNT=5

When starting the Roadrunner server with the configuration specified below, I observed an issue related to worker scaling:
	•	Initially, the number of workers in the configuration file was set to 5.
	•	The maximum number of workers allowed under load for Temporal Activity is 20.

During a heavy load scenario involving tens of thousands of workflows and hundreds of thousands of activities, the scaling correctly increased the worker count. The total number of Activity workers reached 28.

However, once the load dropped to zero (all activities were fully processed), the number of workers did not scale back down to the original value of 5.

### Version (rr --version)

2024.3.0 (build time: 2024-12-05T18:39:32+0000, go1.23.4), OS: linux, arch: amd64

### How to reproduce the issue?

```yaml
version: "3"

rpc:
    listen: tcp://0.0.0.0:6001

server:
    command: "php ../bin/console app:temporal-worker-run"

temporal:
    namespace: ${TEMPORAL_NAMESPACE}
    address: ${TEMPORAL_ADDRESS}
    activities:
        max_jobs: 100
        allocate_timeout: 360s
        command: "php ../bin/console app:temporal-worker-run"
        num_workers: ${TEMPORAL_ROADRUNNER_WORKERS_COUNT}
        destroy_timeout: 1s
        dynamic_allocator:
          max_workers: ${TEMPORAL_ROADRUNNER_MAX_WORKERS_COUNT}
          spawn_rate: 5
          idle_timeout: 10s
    metrics:
        address: ${TEMPORAL_ADDRESS_METRICS}
        prefix: "mars"
        type: "summary"

metrics:
    address: ${RR_ADDRESS_METRICS}

logs:
    mode: production
    level: debug
    output: stderr

otel:
  resource:
    service_name: "roadrunner"
    service_version: "1.0.0"
    service_namespace: "${OTEL_RESOURCE_NAMESPACE}"
    service_instance_id: "${HOSTNAME}"
  exporter: otlp
  endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
  headers:
    api-key: "${NEW_RELIC_API_KEY}"
```

Steps to Reproduce

        1.	Configure Roadrunner with an initial worker count of 5 and a maximum scaling limit of 20.
	2.	Create a single Workflow with at least one Activity inside it.
	3.	Submit approximately 10,000 Workflows with the corresponding Activities to Temporal.
	4.	Observe that the worker count scales up under the load (e.g., reaching 28 workers).
	5.	Allow all Activities to be processed so that the load drops completely to zero.
	6.	Check the worker count after load reduction.

### Relevant log output

```shell
{"level":"info","ts":1734352476002676546,"logger":"temporal","msg":"Activity complete after timeout.","Namespace":"stage-10","TaskQueue":"default","WorkerID":"default:20f10cbd-3161-4b99-98da-390fc6e94208","WorkflowID":"grouping_auto_pso_new_bi_main_10e6e20e-03fe-45a5-aa40-cdea46e79880_20241216","RunID":"c4af45d9-149a-4028-a2e7-110e9a91e925","ActivityType":"grouping_candidates.isOperBrandPlanLimitExceeded","Attempt":1,"Result":"<nil>","Error":"activity_pool_execute_activity:\n\tstatic_pool_exec:\n\tallocate_dynamically: failed to reset the TTL listener"}
{"level":"info","ts":1734352476002767912,"logger":"temporal","msg":"Task processing failed with client side error","Namespace":"stage-10","TaskQueue":"default","WorkerID":"default:20f10cbd-3161-4b99-98da-390fc6e94208","WorkerType":"ActivityWorker","Error":"context deadline exceeded"}
{"level":"debug","ts":1734352476002978390,"logger":"server","msg":"No free workers, trying to allocate dynamically","idle_timeout":10,"max_workers":20,"spawn_rate":5}
{"level":"debug","ts":1734352476003002985,"logger":"server","msg":"dynamic allocator listener already started, trying to allocate worker immediately with 2s timeout"}
{"level":"debug","ts":1734352476010849713,"logger":"temporal","msg":"workflow task started","time":1}
```

**Comment by rustatian** [comment]
Hey @Smolevich 👋🏻 
As I mentioned in the Discord discussion, could you please create a repo (or attach worker+activity+workflow working code) with a code to reproduce an issue?

**Comment by rustatian** [comment]
@Smolevich Friendly ping ^^

**Comment by Smolevich** [comment]
> [@Smolevich](https://github.com/Smolevich) Friendly ping ^^

I will verify everything on the latest Roadrunner release and provide feedback accordingly.

**Comment by rustatian** [comment]
@Smolevich Friendly ping :)

**Comment by Smolevich** [comment]
Thanks! We’ll try to run a load test later this week and see how it behaves.
Based on the metrics from last week, the number of workers didn’t change overall.

Previously, I observed that the upscale was triggered correctly, but the number of workers didn’t return to the initial value even after all workflows had completed.

**Comment by Smolevich** [comment]
<img width="1918" alt="Image" src="https://github.com/user-attachments/assets/e8022be4-54b0-414f-afbc-deea11f0555d" />

Initial workers size - 14 

Current workers size after down scale - 19 

```yaml
version: "3"

rpc:
    listen: tcp://0.0.0.0:6001

server:
    command: "php ../bin/console app:temporal-worker-run"

temporal:
    namespace: ${TEMPORAL_NAMESPACE}
    address: ${TEMPORAL_ADDRESS}
    activities:
        max_jobs: 100
        allocate_timeout: 60s
        command: "php ../bin/console app:temporal-worker-run"
        num_workers: ${TEMPORAL_ROADRUNNER_WORKERS_COUNT}
        destroy_timeout: 1s
        dynamic_allocator:
          max_workers: ${TEMPORAL_ROADRUNNER_MAX_WORKERS_COUNT}
          spawn_rate: 5
          idle_timeout: 10s
    metrics:
        address: ${TEMPORAL_ADDRESS_METRICS}
        prefix: "mars"
        type: "summary"

metrics:
    address: ${RR_ADDRESS_METRICS}

logs:
    mode: production
    level: error
    output: stderr

otel:
  resource:
    service_name: "mars-roadrunner"
    service_version: "1.0.0"
    service_namespace: "${OTEL_RESOURCE_NAMESPACE}"
    service_instance_id: "${HOSTNAME}"
  exporter: otlp
  endpoint: "${OTEL_EXPORTER_OTLP_ENDPOINT}"
  headers:
    api-key: "${NEW_RELIC_API_KEY}"
  insecure: true
  client: grpc
```

TEMPORAL_ROADRUNNER_MAX_WORKERS_COUNT=25
TEMPORAL_ROADRUNNER_WORKERS_COUNT=13

**Comment by rustatian** [comment]
@Smolevich could you please also attach debug logs?

**Comment by vokybykov** [comment]
@rustatian hi. Here are the debug logs

[roadrunner-mars-77db794b65-vs65p_debug_logs.txt](https://github.com/user-attachments/files/20037491/roadrunner-mars-77db794b65-vs65p_debug_logs.txt)

**Comment by rustatian** [comment]
Hey @vokybykov 👋🏻 
Unfortunately, these are regular error logs, not debug. You need to update the log level in the configuration to debug.

**Comment by Smolevich** [comment]
@rustatian These logs are from production. How is the performance affected after enabling debug mode?

**Comment by rustatian** [comment]
@Smolevich Hard to say, depends on IO on the particular pod/vm. But as far as I see, your log contains many `no free workers in the pool` messages. When RR sees this message, it can't downscale the worker's number, because it still receives `no free workers` events.

**Comment by vokybykov** [comment]
@rustatian thanks for the clarification.
I've attached the debug logs and a screenshot showing the number of workers. 
UPD Sent debug logs to email
![Image](https://github.com/user-attachments/assets/ad6ab8be-c125-46ea-b6d3-155773b08173)

**Comment by rustatian** [comment]
@vokybykov Could you please send logs to my email in my GitHub profile?

**Comment by Smolevich** [comment]
@rustatian 

Could you please clarify whether we can expect this bug to be fixed in the near future, or if it’s not currently in the roadmap?
This information would help us to plan our work around it.

**Comment by rustatian** [comment]
Hey @Smolevich 👋🏻 
Could you please create a repository with the sample to reproduce this problem (worker+starter)? This will help me to instantiate a test suite and quickly find a problem.

**Comment by Smolevich** [comment]
Hey @rustatian 

 I'm investigating a critical production issue where workers fail to scale down after load decreases.

  Demo repo: https://github.com/Smolevich/roadrunner-demo (haven't been able to reproduce yet)

  Production Impact:
  - Encountered twice this week, latest caused a production incident
  - Workers scale up correctly (10 → 25) but don't scale back down to initial count
  - Each worker holds a DB connection → exhausted pgbouncer pool (300 limit) → outage

  Production Logs Analysis:
  Before the incident, we saw:
  - 7,574 occurrences of no free workers in the pool, wait timeout exceed
  - 815 pool resets (reset signal received, resetting activity pool)
  - 152 occurrences of worker doesn't respond on stop command, killing process (in ~13 seconds)

  Production Config:
```yaml
  temporal:
    activities:
      num_workers: 10
      max_jobs: 30
      allocate_timeout: 60s
      destroy_timeout: 1s
      dynamic_allocator:
        max_workers: 25
        spawn_rate: 5
        idle_timeout: 10s
```
  Hypothesis: Under heavy load with no free workers available, workers get stuck in long-running DB operations, can't respond to SIGTERM during scale-down, get killed with SIGKILL, but remain tracked in the worker pool.

  Questions:
  1. Known issues with worker cleanup after forced SIGKILL?
  2. Should destroy_timeout: 1s be increased for workers with persistent connections?
  3. Is max_jobs: 30 too high causing worker exhaustion?

 Now we turn off dynamic_allocator

@vokybykov FYI
