### ISSUE TITLE
[🐛 BUG]: Documentation Issue for `read_buf_size` Parameter in TCP config

### ISSUE THREAD

**Issue by butschster** [roadrunner-server/roadrunner#2103]
The documentation for the `read_buf_size` parameter in the RoadRunner TCP server configuration states that the value should be provided in MB. However, upon reviewing the relevant Go code, the parameter is actually interpreted in bytes. This discrepancy can lead to confusion and misconfiguration.

#### Config Reference

```yaml
tcp:
  ...

  # The size of the read buffer in MB. Can be increased to reduce the number of read syscalls.
  # Consider using a larger buffer size if you expect to receive large payloads on the TCP server.
  # Optional; example.
  read_buf_size: 20
```

#### Code Reference
The issue is evident in the following code snippet from `Config.InitDefault`:
```go
if c.ReadBufferSize == 0 {
    c.ReadBufferSize = 1024 * 1024 * 1
}
```

This logic indicates that the buffer size is set in bytes.
