### ISSUE TITLE
[🧹 CHORE]: logger JSON. extra tabs in "logger" witn mode: development

### ISSUE THREAD

**Issue by gam6itko** [roadrunner-server/roadrunner#2134]
### No duplicates 🥲.

- [x] I have searched for a similar issue.

### What should be improved or cleaned up?

If I set logger config like this 
```yaml
logs:
  mode: development #!!!!
  level: debug
  encoding: json
```
Then value in "logger" has extra tabs.

![Image](https://github.com/user-attachments/assets/68400322-09d0-4474-9431-72c3b789809e)

If I set logger config like this 
```yaml
logs:
  mode: production #!!!!
  level: debug
  encoding: json
```
Then value in "logger" displays without extra tabs.

![Image](https://github.com/user-attachments/assets/068026a6-ef99-43a9-87c1-50d800007925)
