### ISSUE TITLE
[🐛 BUG]: panic: runtime error: invalid memory address or nil pointer dereference in 2025.1.0

### ISSUE THREAD

**Issue by Orrison** [roadrunner-server/roadrunner#2172]
### No duplicates 🥲.

- [x] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

Recent release causes runtime panic when run using Laravel Octane and the following .rr.yaml.

### Version (rr --version)

2025.1.0

### How to reproduce the issue?

```yml
version: "3"
rpc:
  listen: "tcp://127.0.0.1:6001"
server:
  command: "php app.php"
  relay: pipes
http:
  address: "0.0.0.0:8000"
  middleware:
    - gzip
    - static
  static:
    dir: public
    forbid:
      - .php
      - .htaccess
  pool:
    num_workers: 1
    supervisor:
      max_worker_memory: 256
jobs:
  pool:
    num_workers: 2
  consume: []
kv:
  local:
    driver: memory
    config: {}
metrics:
  address: "127.0.0.1:2112"
```

Starting `rr`, possibly in general but my usecase was by using [Laravel Octane](https://laravel.com/docs/12.x/octane)

### Relevant log output

```shell
ERROR  panic: runtime error: invalid memory address or nil pointer dereference.  
app-1  | 
app-1  |    ERROR  [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1ac2dfc].  
app-1  | 
app-1  |    ERROR  goroutine 513 [running]:  
app-1  | 
app-1  |    ERROR  github.com/redis/go-redis/extra/redisprometheus/v9.(*Collector).Describe(0x0, 0xc0004905b0).  
app-1  | 
app-1  |    ERROR  github.com/redis/go-redis/extra/redisprometheus/v9@v9.8.0/collector.go:76 +0x1c.  
app-1  | 
app-1  |    ERROR  github.com/prometheus/client_golang/prometheus.(*Registry).Register.func1().  
app-1  | 
app-1  |    ERROR  github.com/prometheus/client_golang@v1.22.0/prometheus/registry.go:279 +0x25.  
app-1  | 
app-1  |    ERROR  created by github.com/prometheus/client_golang/prometheus.(*Registry).Register in goroutine 1.  
app-1  | 
app-1  |    ERROR  github.com/prometheus/client_golang@v1.22.0/prometheus/registry.go:278 +0x1a9.
```
