### ISSUE TITLE
[BUG] strip space from name of post parameters

### ISSUE THREAD

**Issue by dimon-ukr** [roadrunner-server/roadrunner#775]
I tried this code:

```html
<form>
<input type="checkbox" name="Размер обуви[]" value="39">39<br/>
</form>
```

```php
$array = $request->getParsedBody();
```

I expected to see this happen: 

```php
$array = [
    "Размер обуви[]" => "39"
];

```

Instead, this happened:
```php
$array = [
    "Размеробуви[]" => "39"
];
```

The version of RR used: 2.3.2
  
My `.rr.yaml` configuration is: 

```yaml
rpc:
  listen: tcp://localhost:6001

metrics:
  address: 0.0.0.0:9121

status:
  address: localhost:2114

server:
  command: "php public/index.php"

http:
  address: 0.0.0.0:8080
  middleware: ["headers", "static", "gzip"]
  headers:
    cors:
      allowed_origin: "*"
      allowed_headers: "*"
      allowed_methods: "GET,POST,PUT,DELETE"
      allow_credentials: true
      exposed_headers: "Cache-Control,Content-Language,Content-Type,Expires,Last-Modified,Pragma"
      max_age: 600
  static:
    dir: "public"
    forbid: [".php", ".htaccess"]
    calculate_etag: true
    weak: true

logs:
  channels:
    static:
      mode: development
      level: info
      encoding: console
      output: stdout
      err_output: stderr
```

Errortrace, Backtrace or Panictrace
```
<backtrace>
```

</p>
</details>
