### ISSUE TITLE
[BUG] Could not start server because of gzip error

### ISSUE THREAD

**Issue by hotrush** [roadrunner-server/roadrunner#837]
RR version - v2.5.0

RR config file looks like:

```
server:
  command: "php worker.php"

grpc:
  listen: "tcp://:50051"
  proto: "/app/proto/app.proto"
  pool:
    num_workers: 1
    max_jobs: 1000
    supervisor:
      watch_tick: 1s
      ttl: 0s
      idle_ttl: 0s
      max_worker_memory: 128
      exec_ttl: 5s

logs:
  mode: development
  output: stderr
  level: debug
```

But server couldn't start with the next error:

```
DEBU[0000] [http]: disabled
DEBU[0000] [metrics]: disabled
DEBU[0000] [headers]: disabled
DEBU[0000] [static]: disabled
DEBU[0000] [health]: disabled
Error: [gzip]: http service should be defined properly in config to use gzip
```
