### ISSUE TITLE
[💡 FEATURE REQUEST]: Options to disable selective features.

### ISSUE THREAD

**Issue by iKevinShah** [roadrunner-server/roadrunner#887]
### Plugin

Config

### I have an idea!

First of all, really thank you for this piece of software. I have been in touch (over at /r/PHP) on each thread for roadrunner and spiral.

Recently, I was moving my setups from a dedicated VM to WSL. I am using the outdated WSL1 based images (solely as it is easier from a networking perspective) but I hit a roadblock while trying to make my sites work with roadrunner instead of the usual (nginx+php-fpm). 

HAProxy + Nginx & PHP - FPM work fine. But when I try to serve static  / php or anything via rr, it dies stating the following:

```
handle_serve_command: Serve error:
        endure_start:
        endure_serve_internal: Function call error:
        endure_call_serve_fn: got initial serve error from the Vertex fileserver.Plugin, stopping execution, error: cannot enable TCP_FASTOPEN(qlen=16384): protocol not available

```

I understand this is with regards to lack of TCP_FASTOPEN  in the Linux build which I have running on WSL1.

```
[root@PC app]# sysctl -w net.ipv4.tcp_fastopen=2
sysctl: cannot stat /proc/sys/net/ipv4/tcp_fastopen: No such file or directory
[root@PC app]#
[root@PC app]# cat /proc/sys/net/ipv4/tcp_fastopen
cat: /proc/sys/net/ipv4/tcp_fastopen: No such file or directory
[root@PC app]#
```

So, my understanding was that a feature detection happens before using FASTOPEN but it doesnt seem so. Nor did I find any config value via which I could change / control use of TCP_FASTOPEN.  I am not sure what is the flow here. Definitely this wouldn't happen in production systems (or even in WSL2 unless I am mistaken , I havent tried though)

Looking forward to your comments.

Edit: in `/utils/network.go` we have this:

```

func createTCPListener(addr string) (net.Listener, error) {
	cfg := tcplisten.Config{
		ReusePort:   true,
		DeferAccept: false,
		FastOpen:    true,
	}
```

I think configuration or any way to control the `FastOpen: true` bit would help
