### ISSUE TITLE
[💡 FEATURE REQUEST]: Add possibility storage for application metrics

### ISSUE THREAD

**Issue by Smolevich** [roadrunner-server/roadrunner#896]
### Plugin

metrics

### I have an idea!

I suggest to allow save application metrics using kv-storage
For example, in config of roadrunner 
```
metrics:
  # Prometheus client address (path /metrics added automatically).
  #
  # Default: "127.0.0.1:2112"
  address: "127.0.0.1:2112"

  # Application-specific metrics (published using an RPC connection to the server).
  collect:
    app_metric:
      storage: <redis|in_memory|memcached>
```
