### ISSUE TITLE
[💡FEATURE REQUEST]: Authorization plugin

### ISSUE THREAD

**Issue by OO00O0O** [roadrunner-server/roadrunner#912]
**Describe the solution you'd like**
For example: EMQX has multiple authorisation plugins - http, mysql, redis etc. Considering that a lot of people use RR for microservices with JWT, authorization could be moved to it too.

**Example config**
```yaml
auth:
    config: // this could be for each auth method, there for you can have multiple auth methods at once.
        header: Authorization
        query: token
        body: token
        timeout: 180 // ttl for cached authorization
    jwt: // does check jwt, append decoded info to attributes
        config:
            public: ...
    worker: ~ // send auth request over worker like Broadcast plugin does. Everything that workers returns is appended to user "session" and that data is appended to attributes in next request
    http: ~ // append headers etc and send further and wait for 2** response
    kv: ~ // key found and append its content to attributes
    sql:
        config:
            table: token
    passwd: ~
    list: ~ // basic auth
        config:
            hash: md5
        users:
            - username: SomeUser
              password: 5f4dcc3b5aa765d61d8327deb882cf99
      
       
```

For now only JWT makes sense. Example in practice: https://docs.emqx.io/en/broker/v4.3/advanced/auth.html#password-salting-rules-and-hash-methods
