### ISSUE TITLE
[💡FEATURE REQUEST]: Per-plugin server (command)

### ISSUE THREAD

**Issue by rustatian** [roadrunner-server/roadrunner#916]
At the moment, for the RR2 is impossible to run `php` workers per plugin with its own command, all plugins use the same `server.command` to fire a PHP process. User is forced to use multiply RR instances to run different types of workers if needed to separate `http` worker from the `jobs` for example.
To use both types of messages in one worker, the user should write worker.php with a bunch of conditionals like `if http ... else if jobs ... else if temporal`.  It's harder to maintain and read such a kind of worker's code. One big `worker.php` will be responsible for the many types of responses rather than have smaller workers with their own domain responsibilities. 
It's also impossible to use different users/groups or even relays for the different plugins.

My proposal is to include an optional `server` section into the every plugin which may use workers to have precise control over the plugin worker allocations as well as the elimination of `supervisor` section and merge its options to the pool options.

```yaml
http:
    address: 127.0.0.1:8080
    max_request_size: 256
    middleware: ["headers", "gzip"]
    trusted_subnets: []

    server:
        command: "php psr-worker.php"
        user: "www"
        group: ""
        env:
            - SOME_KEY: "SOME_VALUE"
            - SOME_KEY2: "SOME_VALUE2"
        relay: pipes
        relay_timeout: 60s
 
    # Workers pool settings.     
    pool:           
        debug: false
        num_workers: 0
        max_jobs: 64
        allocate_timeout: 60s
        destroy_timeout: 60s
        watch_tick: 1s
        ttl: 0s
        idle_ttl: 10s
        max_worker_memory: 128
        exec_ttl: 60s     
```
