### ISSUE TITLE
[🐛 BUG]: Omit the bugfix version for the config version check

### ISSUE THREAD

**Issue by sergey-telpuk** [roadrunner-server/roadrunner#958]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?
```bash
config_plugin_init: RR version is older than configuration version, RR version: %!s(func() string=0x972b20), configuration version: 2.7.3 
```
```yaml
version: "2.7.3"

rpc:
  listen: tcp://:6001

server:
  command: "php /app/index.php"
  relay: pipes

http:
  address: "0.0.0.0:3001"
#  middleware: []
  pool:
    num_workers: 1
    debug: true
    max_jobs: 1
```

### Version

2.7.3

**Comment by rustatian** [comment]
Hey @sergey-telpuk. Version should be `version: "2.7"`, w/o the bugfix.

**Comment by rustatian** [comment]
The issue with the printing pointer instead of the function return value was fixed, will be released in the rr 2.7.4.

**Comment by sergey-telpuk** [comment]
@rustatian Hi, It doesn't work with `2.7` too, My custom build
```bash
#!/usr/bin/env bash

# shellcheck disable=SC2206
# shellcheck disable=SC2181

RR_VERSION=${RR_VERSION:-"2.7.3"}
PLATFORMS=${PLATFORMS:-"linux/amd64, linux/arm64"}

package=$1
if [[ -z "${package}" ]]; then
  echo "usage: $0 <package-name>"
  exit 1
fi

package_split=(${package//\// })
package_name=${package_split[-1]}

IFS=', ' read -r -a platforms <<<"${PLATFORMS}"

for platform in "${platforms[@]}"; do
  platform_split=(${platform//\// })

  GOOS=${platform_split[0]}
  GOARCH=${platform_split[1]}

  output_name="build/$package_name-${GOOS}-${GOARCH}"

  if [ "$GOOS" = "windows" ]; then
    output_name+='.exe'
  fi

  LDFLAGS="-s \
  -X github.com/roadrunner-server/roadrunner/v2/internal/meta.version=${RR_VERSION} \
  -X github.com/roadrunner-server/roadrunner/v2/internal/meta.buildTime=$(date +%FT%T%z)"

  echo "building ${output_name}"
  CGO_ENABLED=0 GOOS="${GOOS}" GOARCH="${GOARCH}" \
    go build -trimpath -ldflags "${LDFLAGS}" -o "${output_name}" "${package}"

  if [ $? -ne 0 ]; then
    echo 'An error has occurred! Aborting the script execution...'
    exit 1
  fi
done
```

**Comment by rustatian** [comment]
I guess, that smt wrong with your version. Try to execute the binary `./rr` and verify it.

**Comment by rustatian** [comment]
the version in the `.rr.yaml` should be `version: "2.7"`, version from the binary should be `2.7.3`

**Comment by sergey-telpuk** [comment]
@rustatian 
```bash
 rr version 2.7.3 (build time: 2022-01-21T20:14:52+0000, go1.17.6)
config_plugin_init: RR version is older than configuration version, RR version: %!s(func() string=0x972b20), configuration version: 2.7.3

```

**Comment by rustatian** [comment]
The configuration version should be `2.7`. Configuration is not a RR version. It's the `.rr.yaml` version.
```yaml
version: "2.7"
```

**Comment by sergey-telpuk** [comment]
How to set configuration version. It isnt clear now

**Comment by rustatian** [comment]
```yaml
version: "2.7.3" <------------------------ THIS IS CONFIGURATION VERSION. It should be 2.7

rpc:
  listen: tcp://:6001

server:
  command: "php /app/index.php"
  relay: pipes

http:
  address: "0.0.0.0:3001"
#  middleware: []
  pool:
    num_workers: 1
    debug: true
    max_jobs: 1
```
