### ISSUE TITLE
[🐛 BUG]: Case-sensitive attributes for SQS

### ISSUE THREAD

**Issue by paulermo** [roadrunner-server/roadrunner#994]
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

A bug happened!

AWS expects case-sensitive attributes of SQS queues which can be specified in rr.yaml.

Example: 
When we want to create fifo queue, we need to specify FifoQueue attribute alongside with the name of queue something.fifo
Because of unmarshalling FifoQueue becomes fifoqueue and is not recognized by AWS API, the rules for queue naming without this attribute stay unchanged ("do not include dot") and response 400 on CreateQueue with this attribute + name with .fifo is received.

### Version

2.7.4

### Relevant log output

```shell
handle_serve_command: Serve error:
    endure_start:
    endure_serve_internal: Function call error:
    endure_call_serve_fn: got initial serve error from the Vertex jobs.Plugin, stopping execution, error: jobs_plugin_serve:
    new_sqs_consumer: operation error SQS: CreateQueue, https response error StatusCode: 400, RequestID: 66c8affb-4d9b-5e4f-a193-f5d9fcda9f11, api error InvalidParameterValue: Can only include alphanumeric c haracters, hyphens, or underscores. 1 to 80 in length
```

**Comment by rustatian** [comment]
Hey @paulermo, got u. I've missed this `viper` behavior ([link](https://github.com/spf13/viper#does-viper-support-case-sensitive-keys)). I have planned the bug fix for the `2.7.7` to release this Thursday.

**Comment by rustatian** [comment]
@paulermo This issue will be fixed in the `v2.7.7`. I've also added experimental FIFO support (only `ContentBasedDeduplication` is supported at the moment). `MessageDeduplicationId` is not supported at the moment.
`MessageGroupId` can be passed via configuration:
```yaml
  pipelines:
    test-1:
      driver: sqs
      config:
        prefetch: 1000
        visibility_timeout: 0
        wait_time_seconds: 0
        message_group_id: 'foo'
        queue: default.fifo
        attributes:
          FifoQueue: 'true'
          MaximumMessageSize: 262144
          MessageRetentionPeriod: 345600
          ReceiveMessageWaitTimeSeconds: 0
          VisibilityTimeout: 30
          ContentBasedDeduplication: 'true'
```
